### ISSUE TITLE
ARPs not getting loaded

### ISSUE THREAD

**Issue by rudarobson** [pancakeswap/pancake-frontend#1001]
The ARPs values are not showing up on the syrup pools page nor in the farm pools.
This morning Farming pools ARPs were showing, but not anymore.
Stays "Loading" forever on farm pools or the Dash "-" forever.

It happens on chrome, mozila on pc and mobile also using Dapps tab on trust-wallet or metamesk with connected or not connected wallets. (The screen I submited was with a connected metamesk wallet on chrome).

![Issue Lps](https://user-images.githubusercontent.com/2481621/115999508-70d24900-a5c2-11eb-9fcb-5500a1b7f4fb.png)
![Issue syrup](https://user-images.githubusercontent.com/2481621/115999521-7a5bb100-a5c2-11eb-86c6-308219a77675.png)

**Comment by Chef-Cheems** [comment]
@rudarobson RPC node is chosen randomly out of 3 nodes we use each time you refresh the page, sometimes nodes are overloaded or have some other issues and stuff doesn't load. There's nothing really we can do, its up to Binance to sort that stuff out. Fortunately just refreshing the page works, but since node is chosen randomly you could refresh into the same node, in this case just refresh again. 🙂

**Comment by Chef-Cheems** [comment]
@rudarobson maybe you get super unlucky 20 times in a row, heh. The only other reason I can imagine is that your ISP is blocking all nodes. 🤔

**Comment by rudarobson** [comment]
Might be blocking, getting that unlucky is 0% chance. But yesterday and a few days before it was working, even this morning, I got almost 93% of ARP on Cake-Cake Syrup pool showing on my screen, and now, just a "-". Maybe tomorrow it gets unstuck, I'd just like to add some cakes to a Lp pool but I guess it won't happen xD. But thanks anyway!

**Comment by rudarobson** [comment]
Not even the cake current value is showing at the bottom left of the screen...it used to show...

**Comment by Chef-Cheems** [comment]
Hopefully it will sort out for you soon :)
Will close this issue since its not something we can affect.

**Comment by DexteraInstrumenta** [comment]
Hi
This problem is now existing for pools APRs
They remain on loading status!!!
