### ISSUE TITLE
[BUG] Potential Assignment Error in getAmount0Delta and getAmount1Delta

### ISSUE THREAD

**Issue by dirname** [pancakeswap/pancake-frontend#10192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Trade

### Current Behavior

In the v3-sdk, under `SqrtPriceMath`, there appears to be a potential assignment error in the `getAmount0Delta` and `getAmount1Delta` functions.

https://github.com/pancakeswap/pancake-frontend/blob/6d8a30b8fe4c2f0172d847fdf3118cc165495769/packages/v3-sdk/src/utils/sqrtPriceMath.ts#L30-L33

After `sqrtRatioAX96 = sqrtRatioBX96` is executed, `sqrtRatioAX96` now holds the value of `sqrtRatioBX96`. Consequently, the subsequent assignment `sqrtRatioBX96 = sqrtRatioAX96` is equivalent to `sqrtRatioBX96 = sqrtRatioBX96`.

The same issue exists in the `getAmount1Delta` function as well.

https://github.com/pancakeswap/pancake-frontend/blob/6d8a30b8fe4c2f0172d847fdf3118cc165495769/packages/v3-sdk/src/utils/sqrtPriceMath.ts#L49-L51

### Expected Behavior

This is the implementation in the uniswap-v3-sdk:

https://github.com/Uniswap/v3-sdk/blob/4e16fe8e56c8c26541545f138c89133794c7ce72/src/utils/sqrtPriceMath.ts#L25-L46

### Steps To Reproduce

https://github.com/pancakeswap/pancake-frontend/blob/6d8a30b8fe4c2f0172d847fdf3118cc165495769/packages/v3-sdk/src/utils/sqrtPriceMath.ts

### Environment

```markdown
- Device: -
- OS: -
- Browser: -
- Wallet: -
```

**Comment by chefjackson** [comment]
Hey thanks for spotting the issue! It's now fixed.
https://github.com/pancakeswap/pancake-frontend/pull/10194

**Comment by dirname** [comment]
> Hey thanks for spotting the issue! It's now fixed. #10194

There are still some same issues:

https://github.com/pancakeswap/pancake-frontend/blob/3e1fa25fa843d08b89c0182ed3787c0cc815ee2f/packages/v3-sdk/src/utils/maxLiquidityForAmounts.ts#L16-L19

https://github.com/pancakeswap/pancake-frontend/blob/3e1fa25fa843d08b89c0182ed3787c0cc815ee2f/packages/v3-sdk/src/utils/maxLiquidityForAmounts.ts#L33-L36

https://github.com/pancakeswap/pancake-frontend/blob/3e1fa25fa843d08b89c0182ed3787c0cc815ee2f/packages/v3-sdk/src/utils/maxLiquidityForAmounts.ts#L52-L55

https://github.com/pancakeswap/pancake-frontend/blob/3e1fa25fa843d08b89c0182ed3787c0cc815ee2f/packages/v3-sdk/src/utils/maxLiquidityForAmounts.ts#L78-L81
