### ISSUE TITLE
[BUG] <title> Missing function in @pancakeswap/swap-sdk-core

### ISSUE THREAD

**Issue by Degensoft-vlad** [pancakeswap/pancake-frontend#10222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

swap-sdk-core v1.1.0 missing function sortCurrencies for new v3-sdk v.3.8.10 version, and all packages link with new v3.8.10 version, gauge too

ERROR in ./node_modules/@pancakeswap/v3-sdk/dist/index.mjs 1705:33-47
export 'sortCurrencies' (imported as 'sortCurrencies') was not found in '@pancakeswap/swap-sdk-core' (possible exports: BaseCurrency, CurrencyAmount, FIVE, Fraction, InsufficientInputAmountError, InsufficientReservesError, MINIMUM_LIQUIDITY, MaxUint256, NativeCurrency, ONE, Percent, Price, Rounding, TEN, THREE, TWO, Token, TradeType, VMType, VM_TYPE_MAXIMA, ZERO, _100, _10000, _9975, computePriceImpact, getTokenComparator, sortedInsert, sqrt, validateVMTypeInstance)

### Expected Behavior

Add sortCurrencies in swap-sdk-core

### Steps To Reproduce

1. yarn
2. yarn start

### Environment

```markdown
- Device: MacBook Pro
- OS: Big Sur 11.3.1
- Browser: -
- Wallet: -
```

**Comment by Degensoft-vlad** [comment]
#9407 This is Possible Solution

**Comment by chefjackson** [comment]
Hi thanks for flagging. We've pushed a new tag. Please upgrade to use the latest versions
