### ISSUE TITLE
Lotterry time wrong and never start to sale ticket

### ISSUE THREAD

**Issue by dtompichayut** [pancakeswap/pancake-frontend#1025]
**Bug Description**
Time count in lottery page always show wait for tickets sale in xx minutes, despite it pass many hours.
The counter always show the minutes of the current hours when the round time count normally and make user cannot buy the tickets. 

**Steps to Reproduce**

1. Go to Lottery page
2. See the time counter and you can see it mismatched
   ...

**Expected Behavior**
Time is count correctly and can buy tickets.

**Additional Context**
![Screenshot_20210429-013516_Trust Wallet](https://user-images.githubusercontent.com/25883281/116455481-4f57b280-a88b-11eb-81a9-285ceafa030f.jpg)
![Screenshot_20210429-013525_Trust Wallet](https://user-images.githubusercontent.com/25883281/116455491-51ba0c80-a88b-11eb-87f8-141ff472e55c.jpg)

**Comment by Chef-Cheems** [comment]
@dtompichayut lottery is now suspended due to upcoming changes and ongoing voting, read more on [voting page](https://voting.pancakeswap.finance/#/pancake/proposal/QmU8pcbmBrfbfVQXMMxmkExDq3mYq4s5cbBuFe6uCZzdmX) and [twitter](https://twitter.com/PancakeSwap/status/1387419063454896130).
