### ISSUE TITLE
Minor UI issue on Pools Page 

### ISSUE THREAD

**Issue by viktordev01** [pancakeswap/pancake-frontend#1051]
**Bug Description**
The "Add to Metamask" link doesn't have an hover style like other links in the ExpandedFooter component.
Other links in that component use LinkExternal component from the uikit while MetaMask link use Text component.
I was thinking to fix this by myself and make a pull request but i'm not sure which component you prefer to use for this one.
While reading the uikit code i found that besides LinkExternal there is Link component too, so probably it could be easily solved replacing Text component with Link.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/33573324/116682731-ec5f3c00-a9ae-11eb-90a1-9f240f566d62.gif)

**Comment by memoyil** [comment]
I would do that directly in that component by using styledcomponents, since changing text to link add also to arror at the end

`const MetamaskText = styled(Text)
  :hover {
    text-decoration: underline;
    cursor: pointer;
  }
`

and then

`   <MetamaskText
            color="primary"
            small
            onClick={() => registerToken(tokenAddress, earningToken.symbol, earningToken.decimals, imageSrc)}
          >
            Add to Metamask
          </MetamaskText>`

**Comment by viktordev01** [comment]
> I would do that directly in that component by using styledcomponents, since changing text to link adds also arrow at the end
> 
> `const MetamaskText = styled(Text) :hover { text-decoration: underline; cursor: pointer; } `
> 
> and then
> 
> ` <MetamaskText color="primary" small onClick={() => registerToken(tokenAddress, earningToken.symbol, earningToken.decimals, imageSrc)} > Add to Metamask </MetamaskText>`

Link component doesn't have the arrow icon (the component for that icon is called OpenNewIcon).
ExpandedFooter component use LinkExternal instead of Link,  because LinkExternal is essentially Link component + "arrow icon"(OpenNewIcon). 
So i don't see the reason to use styledcomponents just for this, while there's an already written component for these situations.

**Comment by viktordev01** [comment]
> Yes, you can use `Link` but that link will not have `href` just `onClick` that means you will have to add hover style to make the cursor pointer when hovering. It is up to you this is just my proposal 👍

Yeah you're right, i didn't think about that. But could be better to create a component in the uikit? Something like this could happen in the future in other components too.

**Comment by memoyil** [comment]
I would first do it in frontend directly, if we have more usage we can extract to uikit in the future

**Comment by ChefHutch** [comment]
Thanks both, we've caught this one in a tiny UI fix https://github.com/pancakeswap/pancake-frontend/pull/1058

**Comment by memoyil** [comment]
@Chef-Chungus Can be closed, pr has been merged
