### ISSUE TITLE
Liquidity disappeared after migration to V2

### ISSUE THREAD

**Issue by chasingkirkjufell** [pancakeswap/pancake-frontend#1060]
I migrated my liquidity from V1 and V2 and it was showing all the balances. Checking back a week later, the website does not show the liquidity. If you select wnav, contract address is 0xBFEf6cCFC830D3BaCA4F6766a0d4AaA242Ca9F3D, and eth, the website now shows there is no liquidity. Here is the smart contract address for the liquidity of wnav-eth. https://bscscan.com/address/0x0cc53e35801947c94de0be338b03c188f9ddd117#tokentxns

Same with my BNB-WNAV liquidity.

Please advise.

**Comment by Chef-Chungus** [comment]
@chasingkirkjufell your liquidity didn't disappear. It's likely you added it into the wrong location. 

I'll close this for now, but if you're still having this issue please feel free to open this ticket again
