### ISSUE TITLE
incorrect data on the ALICE-BNB farm

### ISSUE THREAD

**Issue by realDahu** [pancakeswap/pancake-frontend#1061]
**Bug Description**
After succefull contract, the amount stacked on ALICE-BNB LP is not visible on my farm.
![image](https://user-images.githubusercontent.com/83493816/116776708-4ffa6f80-aa6a-11eb-8dec-d1b4dad1958f.png)

But the total amount is clearly visible on yieldwatch
![image](https://user-images.githubusercontent.com/83493816/116776786-bbdcd800-aa6a-11eb-8d58-5bd22bedad1a.png)

**Steps to Reproduce**
1. Go to ALICE-BNB LP farm
2. Convert and stack ALICE-BNB LP tokens.
3. Check for successful contract.
4. The amount of the investment does not appear in the farm

**Expected Behavior**
that the amount of my investment is visible on my farm.

**Comment by memoyil** [comment]
This is not a bug. As of now only lp token amount is shown in farms page. It can be a feature request.

**Comment by realDahu** [comment]
I probably misspoke, please compare the stacked values on the two different sites. The value on yieldwatch (50.09 ALICE/1.34 BNB) does not equal to 0.000008132782983642 ALICE-BNB LP on pancakeswap

**Comment by Chef-Chungus** [comment]
Please share your address

**Comment by memoyil** [comment]
As you can see there LP-Tokens section you purchased 0.00 lp token (which should show you more decimals since ALICE-BNB price is so high) . Pancake shows you the exact amount of tokens without removingg the decimals.

**Comment by realDahu** [comment]
> Please share your address

https://bscscan.com/tx/0xae445e2b66f8830a8cb399f328b88257b1c2716fa98488032e365b31a622f487

**Comment by memoyil** [comment]
The amount of LP-Token you have is correct. As you can see it in transaction details. This is because LP Token price is so high in ALICE-BNB farm.

<img width="1112" alt="Screenshot 2021-05-01 at 16 10 59" src="https://user-images.githubusercontent.com/2213635/116785100-06287e00-aa98-11eb-9a9b-0f1e3a0128f1.png">

**Comment by realDahu** [comment]
> The amount of LP-Token you have is correct. As you can see it in transaction details. This is because LP Token price is so high in ALICE-BNB farm.

you say that : 0.000008132782983642 LP = 50 ALICE + 1.3 BNB = $1680 ?

**Comment by memoyil** [comment]
Not exactly, it depends on the liquidity pool (you should read ‘impermanent loss’ in liquidity pools)  but approximately yes you have that amount you wrote.

**Comment by realDahu** [comment]
thank you for the explanation and sorry for my mistake
