### ISSUE TITLE
[BUG] Incorrect Liquidity Calculation

### ISSUE THREAD

**Issue by gades** [pancakeswap/pancake-frontend#10778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

The liquidity volume is being calculated incorrectly. The account holds 110.4 ZEC with an exchange rate of $26.011 per ZEC. However, instead of showing the expected value of $110.4, the system displays an incorrect value of $16,768.26.

https://pancakeswap.finance/liquidity/1318667?chain=bsc&persistChain=1

### Expected Behavior

The liquidity volume is being calculated incorrectly. The account holds 110.4 ZEC, with an exchange rate of $26.011. It is expected to display $2871.6144, but in fact, it shows $16,768.26.

https://pancakeswap.finance/liquidity/1318667?chain=bsc&persistChain=1

### Steps To Reproduce

1. Please create LP ZEC/USDT 1%
2. Open LP and check 

https://pancakeswap.finance/liquidity/1318667?chain=bsc&persistChain=1

### Environment

```markdown
- Device: Mac
- OS: v15 
- Browser: Chrome Version 129.0.6668.90 (Official Build) (arm64)
- Wallet: Metamask
```

### Anything else?

This issue only with ZEC 0x1Ba42e5193dfA8B03D15dd1B86a3113bbBEF8Eeb

**Comment by gades** [comment]
API - https://wallet-api.pancakeswap.com/v1/prices/list/56%3A0x1ba42e5193dfa8b03d15dd1b86a3113bbbef8eeb 
Doesn't work correctly it't return {"56:0x1ba42e5193dfa8b03d15dd1b86a3113bbbef8eeb":70921408984.36331} instead of real price

**Comment by chefjackson** [comment]
Hi thanks for the report. The price issue has been resolved.
