### ISSUE TITLE
[BUG] Incorrect APR and ROI calculation

### ISSUE THREAD

**Issue by alexeysmovzh** [pancakeswap/pancake-frontend#10842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Farms

### Current Behavior

Current APR calculation displays 10 trillion percent of interest rate

![Screenshot from 2024-10-19 20-00-09](https://github.com/user-attachments/assets/d4b86996-9506-42ac-b9a8-30280f18d902)

Current ROI displayed also incorrect
![Screenshot from 2024-10-19 19-59-58](https://github.com/user-attachments/assets/02f61150-7e14-48d4-a7fb-ba263e2a9b3e)

### Expected Behavior

Correct calculation of APR and ROI

### Steps To Reproduce

1. enter to pancakeswap website
2. go to Pool and open your liquidity position (please see screenshots attached)

### Environment

```markdown
- Device: Lenovo laptop AMD Ryzen 5 5500U, 16Gb ram
- OS: Ubuntu 22.04
- Browser: Brave Version 1.69.168 Chromium: 128.0.6613.138 (Official Build) (64-bit)
- Wallet: Metamask
```

**Comment by gades** [comment]
It's related to issues with API prices 

https://wallet-api.pancakeswap.com/v1/prices/list/56%3A0x1ba42e5193dfa8b03d15dd1b86a3113bbbef8eeb

**Comment by chefjackson** [comment]
Hi thanks for the report. The price issue has been resolved.
