### ISSUE TITLE
[BUG] <title>'@pancakeswap/v4-sdk@0.1.4' is not in this registry.

### ISSUE THREAD

**Issue by xiaozhu001** [pancakeswap/pancake-frontend#10888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Trade

### Current Behavior

When I was doing the import of smart-router, I found that v4-sdk doesn't exist in the npm repository, and the version of smart-router is "@pancakeswap/smart-router":"^6.1.0",the error message is put below
![image](https://github.com/user-attachments/assets/5b0e3485-a70e-40d5-9c73-a922e2cec50e)

### Expected Behavior

Please add @pancakeswap/v4-sdk@0.1.4 to the npm repository

### Steps To Reproduce

This is reproduced by introducing the @pancakeswap/smart-router module in the project

### Environment

```markdown
- Device:windows
- OS:windows
- Browser:Chome
- Wallet:Metamask
```

### Anything else?

![image](https://github.com/user-attachments/assets/38ed3b36-166f-44b2-94a9-488df6703a72)

**Comment by chefjackson** [comment]
Hi thanks for the report. It's been fixed in `@pancakeswap/smart-router@6.2.1`. Please upgrade to the latest version
