### ISSUE TITLE
Predictions collect winning transaction bug

### ISSUE THREAD

**Issue by viktordev01** [pancakeswap/pancake-frontend#1094]
**Bug Description**
Hi, because i didn't find any repo with the predictions contracts source code, i'm posting here this bug.
When trying to collect winnings, sometimes after collecting them, the button for claim winnings doesn't disappear. If i try to collect them again, instead of an error, there's a transaction with an abnourmous gas fee. I don't know what can happen if someone try to accept and pay that transaction, so i'm posting here a screenshot. Can i ask why there isn't still a repo with predictions smart contracts source code?

![Cattura](https://user-images.githubusercontent.com/33573324/116874223-4105ef80-ac19-11eb-829e-9f686c767d2a.PNG)

**Comment by memoyil** [comment]
On which button are you collecting the winnings?

**Comment by viktordev01** [comment]
in this example the one in the Prediction card and not from history. But it happened multiple times. Even if i collect from history, sometimes the collect winnings button in the Prediction card doesn't disappear and if i try to collect winnings two times in a row there's always a transaction (like the one in the screenshot) with 0.2+BNB  gas fee.

**Comment by memoyil** [comment]
Are you sure you successfully collect you winnings when you do the first transaction?

**Comment by viktordev01** [comment]
> Are you sure you successfully collect you winnings when you do the first transaction?

Yes. It happens only when i succesfully claimed my winnings. I checked multiple times because it was really strange. And as i said it happened multiple times.

**Comment by viktordev01** [comment]
I noticed that you have made many updates, but this bug still happen atleast to me.

**Comment by memoyil** [comment]
It has not merged yet

**Comment by viktordev01** [comment]
I was playing a round of predictions and markets stopped again. When trying to claim the refund, instead of refund transactions there's a transaction with 0.22+ gas fee (similar to the one of double claim bug).
So i can't claim my 0.01BNB refund for that round. I don't know if it happened to other people too. 
![Cattura](https://user-images.githubusercontent.com/33573324/117141444-d4245e00-adae-11eb-9303-e02de513dc72.PNG)

**Comment by memoyil** [comment]
Have you tried changing your gas limit?

**Comment by viktordev01** [comment]
Yes but it reject the transaction. Anyways, now that predictions are online again it worked and i claimed my refund. I

**Comment by viktordev01** [comment]
I'm sorry to say this, but this bug appeared again.
The error in metamask says "ALERT: Transaction Error. Exception thrown in contract code.".
![Cattura](https://user-images.githubusercontent.com/33573324/117286541-9c2e2100-ae69-11eb-8e6c-77127e45ac8d.PNG)

**Comment by memoyil** [comment]
Collect Winnings button seen again after you collected successfully?

**Comment by viktordev01** [comment]
yeah.

**Comment by memoyil** [comment]
Immediately or after some time?

**Comment by viktordev01** [comment]
immediately and if i cancel it and try to make a bet on another round it displays the old balance. If i refresh the page most of the times it disappear (but not always).

**Comment by memoyil** [comment]
Ok but thats another bug "if i cancel it and try to make a bet on another round it displays the old balance (and not the updated one with winnings claimed)" can you open another bug report for it?

**Comment by viktordev01** [comment]
what i want to say is that when the claim button appear two times in a row, balance in the next round card doesn't update.
The old bug is still here, but i noticed this other one too (and when i said "if i cancel the transaction", i meant the one with 0.2+ gas fee).
Because history works fine (the claim button appear only one time), i'm thinking that probably the error is inside the code that update the round cards. 
The winning claim button bug doesn't appear always. Probably is something related to data sync of on-chain data.

**Comment by memoyil** [comment]
@viktordev01 there is a fix has been merged lately, can you check it again? (the issue of button appears again)

**Comment by viktordev01** [comment]
I played some rounds and for now it works without problems.

**Comment by viktordev01** [comment]
Unfortunately, it happened again, but before it was almost every round, now it happen slightly less.

**Comment by memoyil** [comment]
Could that be a leftover code on your cache maybe? Can you clean your browser cache and try it again?

**Comment by viktordev01** [comment]
Yeah. And i forgot to add that instead of round cards, now it happen inside of history tab because of claim winning button popup.
The popup doesn't appear always and when it appear there's a slightly delay between the appearing of claim button inside the round card and the popup. This is why i said that now it happen slightly less. There's something wrong with the popup.

**Comment by memoyil** [comment]
If it is just a delay, I think there should not be a problem no?
