### ISSUE TITLE
Predictions balance discrepancy between round cards and actual balance

### ISSUE THREAD

**Issue by viktordev01** [pancakeswap/pancake-frontend#1154]
**Bug Description**
Sometimes when placing a bet after claiming prize, the balance inside the round card doesn't update so it is less than the actual balance.

![Cattura1_LI](https://user-images.githubusercontent.com/33573324/117445786-6b1e2100-af3b-11eb-996f-af6af32ac355.jpg)

**Comment by ChefKai** [comment]
Hello, this issue has been fixed; feel free to open a new issue if this happens again. Thanks for your report
