### ISSUE TITLE
Add DaftCoin logo on Pancakeswap :)

### ISSUE THREAD

**Issue by daftpump** [pancakeswap/pancake-frontend#1159]
Hello guys!

I'm the Dev of DaftCoin we are listed on CoinMarketCap and Coingecko, here : 
https://coinmarketcap.com/currencies/daftcoin/
https://www.coingecko.com/en/coins/daftcoin

We contacted your support for add our logo on Pancakeswap with no response!
Can you have a look please for add our logo on Pancakeswap! Thanks !

http://daftco.in/images/logo200x200.jpg

If you need to contact me you can ask me on dev@daftco.in

Thanks for our community !

**Comment by daftpump** [comment]
![Capture d’écran 2021-05-10 à 23 21 47](https://user-images.githubusercontent.com/5670968/117735870-af891580-b1f6-11eb-86bb-91926d0ed339.png)

**Comment by ChefKai** [comment]
Hello, please refer to this [link](https://docs.pancakeswap.finance/contact-us/business-partnerships#how-can-i-add-my-tokens-logo-icon) in order to add your logo on PancakeSwap. Thanks.
