### ISSUE TITLE
Add Liquidity stuck approving.

### ISSUE THREAD

**Issue by mrkwskiti** [pancakeswap/pancake-frontend#1175]
**Bug Description**
When I add liquidity between BNB and ALPA that has a bsc transaction fail but add liquidity page stuck in approving.

**Steps to Reproduce**

1. Go to Add liquidity page
2. Select inputs is BNB and ALPA
3. Click on max button in ALPA section
4. Create transaction form trust wallet
5. Transaction has failed [transaction ref](https://bscscan.com/tx/0x8cc5020d451c6586464b988438b726a869b194ffc509ac94e3eb18fa6506df4a)

**Expected Behavior**
Should can be re approve when bsc transaction failed.

**Additional Context**
Add any other context about the problem here (screenshots, whether the bug only occurs only in certain mobile/desktop/browser environments, etc.)
![image](https://user-images.githubusercontent.com/31288625/117740923-a8302f00-b22b-11eb-8d91-06b0685b7a39.png)
![image](https://user-images.githubusercontent.com/31288625/117741041-afefd380-b22b-11eb-9901-f116aa40c2d7.png)

**Comment by snapple42** [comment]
I don't know if I'm having the same issue,but when I click on supply liquidity, I'm getting the following error in the console:
, message: "Internal JSON-RPC error.", data: {…} }
​
code: -32603
​
data: Object { code: 3, message: "execution reverted: TransferHelper: TRANSFER_FROM_FAILED", data: "0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000245472616e7366657248656c7065723a205452414e534645525f46524f4d5f4641494c454400000000000000000000000000000000000000000000000000000000" }
​
message: "Internal JSON-RPC error."
​
<prototype>: Object { … }
main.09ef0ae4.chunk.js:1:178850
    e main.09ef0ae4.chunk.js:1
    (Async: promise callback)
    e main.09ef0ae4.chunk.js:1
    l runtime.js:63
    _invoke runtime.js:293
    C runtime.js:118
    Babel 4
    Ne main.09ef0ae4.chunk.js:1
    Se main.09ef0ae4.chunk.js:1
    React 11
    unstable_runWithPriority scheduler.production.min.js:18
    React 14
    unstable_runWithPriority scheduler.production.min.js:18
    React 13
    487 main.09ef0ae4.chunk.js:1
    u (index):1
    t (index):1
    r (index):1
    <anonymous> main.09ef0ae4.chunk.js

**Comment by Chef-Chungus** [comment]
This tends to happen due to periods of high network congestion on BSC. I'll close this now as it should be resolved, however, if you're still experiencing this, please feel free to open another ticket.
