### ISSUE TITLE
Liquidity is locked : could you migrate our LP ?

### ISSUE THREAD

**Issue by daftpump** [pancakeswap/pancake-frontend#1186]
Hi,

People ask us that they can't buy DAFT on Pancakeswap V1.

Our liquidity is locked until September.. : as you can see here : https://cryptexlock.me/pair/0x97adfd64293cD7356abc5a89C9F3736728358bDB

Could you migrate the LP to Pancakeswap V2 ? please.

**Comment by T-V-N** [comment]
https://www.youtube.com/watch?v=dQw4w9WgXcQ

> Hi,
> 
> People ask us that they can't buy DAFT on Pancakeswap V1.
> 
> Our liquidity is locked until September.. : as you can see here : https://cryptexlock.me/pair/0x97adfd64293cD7356abc5a89C9F3736728358bDB
> 
> Could you migrate the LP to Pancakeswap V2 ? please.

https://www.youtube.com/watch?v=dQw4w9WgXcQ check the video on how to migrate it yourself

**Comment by Chef-Chungus** [comment]
@daftpump we can not migrate liquidity for projects. Only projects can migrate their own liquidity.

**Comment by daftpump** [comment]
@Chef-Chungus you migration has dump our token volume, with this message alerting of LP migratio
