### ISSUE TITLE
TESTNET Unhandled Rejection (Error): call revert exception (method="balanceOf(address)"...

### ISSUE THREAD

**Issue by masterkain** [pancakeswap/pancake-frontend#1191]
trying to run the interface on testnet

![screencapture-localhost-3000-2021-05-12-18_49_10](https://user-images.githubusercontent.com/12844/118013868-de1c0300-b352-11eb-83fc-d88c8061ac86.png)

**Comment by RabbitDoge** [comment]
Some contracts are not available on testnet

**Comment by Mjavala** [comment]
I was able to solve this (assuming you have correctly added necessary contracts) by changing the dev environment RPC urls to the testnet.

**Comment by Chef-Chungus** [comment]
@masterkain - I'll be closing this now as there hasn't been any action in a couple months. IF you're still experiencing this issue, please let us know in a new issue.
