### ISSUE TITLE
Logout won't work on mobile safari

### ISSUE THREAD

**Issue by chenxsan** [pancakeswap/pancake-frontend#1213]
**Bug Description**
`Logout` button wont work on mobile safari.

**Steps to Reproduce**

1. Open the site in safari
2. `Connect` with `WalletConnect` and use Trust Wallet to login
3. After loginned, click the address button at the top to open the modal to `Logout`, the page would be redirected indicating I'm signed out.
4. Click the `Connect` again, it just login automatically which is wrong.

**Expected Behavior**
`Logout` button should work as expected.

**Additional Context**

**Comment by xvalentino** [comment]
I'm curious to look into this too, I've had some weirdness around logging in and out on mobile and on my macbook. Loggin in throught the Dapps on trust wallet works fine.

**Comment by namirpapi** [comment]
I do swap on pancake and you transferrred my token to another guys why ? 
![Uploading 8B5161C5-3519-4B69-95BA-318F39DA0105.jpeg…]()

**Comment by claasahl** [comment]
I am having the same issue when using PanCakeSwap (in the Trust Walltet app on my android smartphone).

1. open Trust Wallet app and switch to "DApps" tab
2. open PanCakeSwap
3. I see that I am logged in (top right button shows my wallet address)
4. press the top right button and press "Logout"
5. the top right button changes to "Connect"
6. refresh page
7. I see that I am logged in (top right button shows my wallet address)

**Comment by Chef-Chungus** [comment]
This has been resolved a couple weeks ago
