### ISSUE TITLE
how to custom default theme 

### ISSUE THREAD

**Issue by TimberTang** [pancakeswap/pancake-frontend#1220]
import { MimoTheme } from '../theme'

declare module 'styled-components' {
  /* eslint-disable @typescript-eslint/no-empty-interface */
  export interface DefaultTheme extends MimoTheme {}
}

export const baseColors = {
  failure: "#ED4B9E",
  primary: "#FF0000",
  primaryBright: "#53DEE9",
  primaryDark: "#0098A1",
  secondary: "#7645D9",
  success: "#31D0AA",
  warning: "#FFB237",
};

and i setting primary color to red . but the theme display defalut pancake theme .

**Comment by Chef-Cheems** [comment]
You mean in the UIKit storybook or front-end?
If you're talking about front-end then you need to build the UIKit and use updated kit in the FE. In storybook it should happen automatically of course.

**Comment by TimberTang** [comment]
emmm. future will implement the feature?

**Comment by TimberTang** [comment]
> You mean in the UIKit storybook or front-end?
> If you're talking about front-end then you need to build the UIKit and use updated kit in the FE. In storybook it should happen automatically of course.

emmm. future will implement the feature?

**Comment by Chef-Cheems** [comment]
There is nothing to implement, its just about how you handle the packages locally. If you changed something in UIKit it will not reflect in the front-end cause you probably just use UIKit from npm there.
So for now you just build and link local package to front-end, easiest is just copy dist to FE node_modules, or you can try yarn link (but it might be really flaky).

**Comment by TimberTang** [comment]
emmm . iam useing pancakeswap-libs/uikit/
and can i use custom theme replace in ThemeContext
