### ISSUE TITLE
Lottery History Chart - Tooltip color

### ISSUE THREAD

**Issue by ciruz** [pancakeswap/pancake-frontend#1336]
Hey guys,

with this PR https://github.com/pancakeswap/pancake-frontend/pull/1245#issue-647038375 I improved the lottery history tooltip (notice the label border/bg - color).

Before:
![image](https://user-images.githubusercontent.com/987947/119462358-ec99ef80-bd40-11eb-9628-ab5da883ffe6.png)

After:
![image](https://user-images.githubusercontent.com/987947/119461932-81501d80-bd40-11eb-9e19-c7c593233550.png)

Right now the colors in the tooltip are gone again:
![image](https://user-images.githubusercontent.com/987947/119462420-fde2fc00-bd40-11eb-9c9a-e71ffe05e3e3.png)

I think it's because of this commit: https://github.com/pancakeswap/pancake-frontend/commit/b99e1dc030ac354a8b93346d3ed4c5683b94fce6 ( @hachiojidev ).

**Comment by memoyil** [comment]
@hachiojidev we can close this issue

**Comment by ChefNina** [comment]
@ciruz @memoyil Thank you for your supports!
