### ISSUE TITLE
Can’t connect to MetaMask wallet in Chrome on iOS

### ISSUE THREAD

**Issue by krugster** [pancakeswap/pancake-frontend#1337]
**Bug Description**
Trying to connect pancakeswap to my MetaMask wallet via Chrome on iOS (latest versions installed). I have the MetaMask app installed. 

Error received: Provider Error: No provider was found

**Steps to Reproduce**

1. Go to pancakeswap.finance
2. Click on Connect
3. Select MetaMask
4. Receive error: No provider was found

**Additional Context**
Works fine from desktop, issue seemingly only on iOS. Tested with chrome and safari.

**Comment by memoyil** [comment]
You should use Embedded Browser inside the Metamask app

**Comment by krugster** [comment]
Thanks for the quick response, that definitely works. 

The issue still remains though that I can’t do it from Chrome as my browser of choice. And also that the error message isn’t very helpful.

**Comment by memoyil** [comment]
If you want the connect your wallet to the app with your standalone browser, you have to select WalletConnect and then select MetaMask.

**Comment by krugster** [comment]
Also looks like using "WalletConnect" from within pancakeswap on Chrome
works perfectly as expected, so perhaps the error message just needs
updating or for it to auto-redirect to WalletConnect

**Comment by krugster** [comment]
Yup, and that all works great...just isn't obvious to a newbie like me.

**Comment by memoyil** [comment]
@krugster you can close the issue, if it is resolved for you

**Comment by krugster** [comment]
Well I'm not sure it's actually resolved since you still can't connect by
clicking the very obvious "MetaMask" option from a 3rd party browser and
there's no error message pointing you towards the WalletConnect option
instead.

**Comment by Chef-Chungus** [comment]
This is a general crypto wallet usability issue. We're trying to work out ways to resolve this, but it's not really a simple task to solve. I'll close this as your initial question is resolved, but the enhancement suggestion can be broken into a new issue.
