### ISSUE TITLE
Buying token errors out adding a 1 to the final digit of the bought amount solves it

### ISSUE THREAD

**Issue by eldiegod** [pancakeswap/pancake-frontend#1383]
Buying token errors out but adding a 1 to the final digit of the bought token amount solves it for some reason?
Anyone knows how to fix this issue, I encounter it so often and we have left quite a bit of new holders on the table due to this.

**Steps to Reproduce**

1. Go to https://exchange.pancakeswap.finance/#/swap?outputCurrency=0x1a46d794ea19d9b93828fe5a1b96bfab5eed015a

2. Try to buy a small amount at around 5% slippage, it will often error out

3. Adding a one to the last digit of the bought token solves it magically

**Expected Behavior**
You are able to execute the buy order without adding the 1 to the last digit, as it is not intuitive at all, or at least there is some kind of text to warn the users how to solve this issue

**Additional Context**
I have seen some tokens have some kind of custom dialog on pancake that warns about this could be a possible solution if anyone knows how to add that?

**Comment by Chef-Chungus** [comment]
@eldiegod - This happens on tokens with high fees. For example, safemoon with a 12% fee. You need to simply increase your slippage higher to prevent the errors from occuring. 

Regarding adding one decimal onto it resulting in bypassing the error, we are aware of this and are investigating. I'll create a separate issue for this.
