### ISSUE TITLE
[Prediction] Implicit error message when setting position with a long digits

### ISSUE THREAD

**Issue by iketiunn** [pancakeswap/pancake-frontend#1441]
**Bug Description**
When you input/slide a number like "0.0016734964032423141" will cause an error in console:
```
Uncaught Error: Error: [number-to-bn] while converting number "1673496403242314.1" to BN.js instance, error: invalid number value. Value must be an integer, hex string, BN or BigNumber instance. Note, decimals are not supported. Given value: "1673496403242314.1"
    at f (3.a046cbe4.chunk.js:1)
    at Object.m (3.a046cbe4.chunk.js:1)
    at 3.a046cbe4.chunk.js:1
    at Array.forEach (<anonymous>)
    at c (3.a046cbe4.chunk.js:1)
    at h.inputTransactionFormatter (3.a046cbe4.chunk.js:1)
    at 3.a046cbe4.chunk.js:1
    at Array.map (<anonymous>)
    at h.formatInput (3.a046cbe4.chunk.js:1)
    at h.toPayload (3.a046cbe4.chunk.js:1)
```

**Steps to Reproduce**

1. Go to Set Position
2. Input / Slide a number with digits length > 18
3. Click on  "Confirm"

**Expected Behavior**
Should expect we bet successfully or prompt an error message instead of print in console.

**Additional Context**
- This error is rare but might occur when just clicking on the `percentShortcuts` buttons
- This error might occur when web3 transforming the bet value
- Just new to web3, but I think to restrict value under 18 digits when input or slide is good for UX

![Screen Shot 2021-06-05 at 11 42 54 AM](https://user-images.githubusercontent.com/10249208/120879048-331a0480-c5f3-11eb-95bc-a433547a62f7.png)

**Comment by Chef-Chungus** [comment]
Bnb only has 18 decimals. 

You can't bet with greater than 18 decimals

**Comment by iketiunn** [comment]
Yes, and probably input should restrict that too.
