### ISSUE TITLE
Successful wrapping of BNB into WBNB shows ETH to WETH message

### ISSUE THREAD

**Issue by philiparthurmoore** [pancakeswap/pancake-frontend#1445]
**Bug Description**
After successfully wrapping BNB into WBNB the following message appears.

<img width="260" alt="CleanShot 2021-06-05 at 20 32 23@2x" src="https://user-images.githubusercontent.com/28684/120893382-42be3b00-c63d-11eb-9a94-b74c18ce2728.png">

**Steps to Reproduce**

1. Go to https://exchange.pancakeswap.finance/#/swap?outputCurrency=0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c
2. Wrap BNB
3. Done.

**Expected Behavior**
I expect to see `Wrap 1 BNB to WBNB` there.

**Comment by ChefKai** [comment]
Hello; thank you for your report, this issue has been fixed!
