### ISSUE TITLE
estimateGas failed removeLiquidityETHWithPermitSupportingFeeOnTransferTokens

### ISSUE THREAD

**Issue by aress31** [pancakeswap/pancake-frontend#1455]
I am unable to remove liquidity, could you please assist with:

```
react_devtools_backend.js:2560 estimateGas failed removeLiquidityETHWithPermitSupportingFeeOnTransferTokens (10) ["0xb39F4312C467F622AAbbD1eB39C890011fD7085E", "5000000000000000000000000", "38106063120433605503178534460745", "173303421098493821", "0x7F87bBc2Eb7911c8961c8506032d31d624894725", 1623062548, false, 27, "0xebd72effa8e0104ac466956e40f12460706630dfafbfc963d494f2dde11ba588", "0x442410f44cff5bcc74a8271a6a44a6bcc2e5c6399bece7ce07f34bdfb65442ab"]0: "0xb39F4312C467F622AAbbD1eB39C890011fD7085E"1: "5000000000000000000000000"2: "38106063120433605503178534460745"3: "173303421098493821"4: "0x7F87bBc2Eb7911c8961c8506032d31d624894725"5: 16230625486: false7: 278: "0xebd72effa8e0104ac466956e40f12460706630dfafbfc963d494f2dde11ba588"9: "0x442410f44cff5bcc74a8271a6a44a6bcc2e5c6399bece7ce07f34bdfb65442ab"length: 10__proto__: Array(0) {code: -32603, message: "Internal JSON-RPC error.", data: {…}}
```

![image](https://user-images.githubusercontent.com/11601622/121001084-d188a000-c782-11eb-8b3a-076230d54f34.png)

**Comment by aress31** [comment]
It is an urgent issue, help?!

**Comment by Chef-Chungus** [comment]
This is an issue with the node you were connecting to. I'm assuming this is resolved now. Please re-open if you are still experiencing this issue

**Comment by devacer11** [comment]
Getting same error when I click Continue button
![pcs_Capture](https://user-images.githubusercontent.com/74443899/129685070-b548d3a0-f446-42fe-b787-608b7484726c.PNG)

This is my contract on BSC
https://bscscan.com/address/0x8add0afad6f2617c0fa5cc4ebac1162b8ab2a07c#code

Pls help, thanks!

**Comment by easy2020i** [comment]
Same Error :(

![pcs_Capture](https://user-images.githubusercontent.com/75439352/129690516-8b55b5ae-015d-4950-9173-5cf66f8a090a.PNG)

This is my contract on BSC
https://bscscan.com/address/0x8add0afad6f2617c0fa5cc4ebac1162b8ab2a07c#code

Pls help, thanks!

**Comment by Waltarb** [comment]
![image](https://user-images.githubusercontent.com/19947202/131843840-5644f8d8-f550-41c8-a48a-99744efdf89b.png)
same problem here have been trying this for months now, same problem when I try with wbnb/high slippage or through the pancake router contract manually..
