### ISSUE TITLE
i hope to work with you in this project

### ISSUE THREAD

**Issue by MohammedALREAI** [pancakeswap/pancake-frontend#1480]
### Hello Everybody. 

 I'm looking for a developer proficient in **React+Typescript** to get functions from open source.
Here is the git link. Plz check and if you are confident, let's chat via PM.
really I Hope to work with you.

**Comment by matbrgz** [comment]
?

**Comment by MohammedALREAI** [comment]
![image](https://user-images.githubusercontent.com/31209091/121614418-4ac81180-ca67-11eb-806c-31d8ea3ed4da.png)

**Comment by ChefNina** [comment]
Hello Mohammed, 
I don't think it's our offer. You can check ours here:
https://docs.pancakeswap.finance/hiring/become-a-chef
