### ISSUE TITLE
Blank screen when trying to load farms

### ISSUE THREAD

**Issue by devakrishna33** [pancakeswap/pancake-frontend#1493]
**Bug Description**
Blank screen appears when I search for a "bmxx-bnb" pair on farms page, I looked at the console and it showed "TypeError: Cannot read property 'pid' of undefined".

**Comment by memoyil** [comment]
What is your steps to reproduce the problem?

**Comment by memoyil** [comment]
@devakrishna33 Use farm table view for now, issue will be fixed in farm cards view

**Comment by memoyil** [comment]
<img width="1154" alt="Screenshot 2021-06-13 at 15 40 56" src="https://user-images.githubusercontent.com/2213635/121809701-1f5b4780-cc5e-11eb-83c7-c9aa70ae0dea.png">

Click this button to enable table view

**Comment by devakrishna33** [comment]
@memoyil Thaks, that seems to work
