### ISSUE TITLE
Blank white page when loading farms section

### ISSUE THREAD

**Issue by Wolfthorne** [pancakeswap/pancake-frontend#1496]
**Bug Description**
When navigating to farms it initially loads but goes to a blank white page.

**Steps to Reproduce**

1. Go to farms
2. Wait for page to turn white

**Expected Behavior**
Page should load

**Additional Context**
Add any other context about the problem here (screenshots, whether the bug only occurs only in certain mobile/desktop/browser environments, etc.)
![image](https://user-images.githubusercontent.com/5700166/121814360-98e33d80-cc3e-11eb-9c67-d08ffe5f99ce.png)

**Comment by memoyil** [comment]
@Wolfthorne Use farm table view for now, issue will be fixed in farm cards view

<img width="1154" alt="Screenshot 2021-06-13 at 15 40 56" src="https://user-images.githubusercontent.com/2213635/121816624-fb5b2e80-cc7c-11eb-8fdc-6094f0e7a665.png">

**Comment by memoyil** [comment]
@hachiojidev issue is fixed, we can close it

**Comment by ChefKai** [comment]
Thanks for fixing!
