### ISSUE TITLE
The tooltips do not work in the desktop version

### ISSUE THREAD

**Issue by danielomontero** [pancakeswap/pancake-frontend#1576]
**Bug Description**
When placing the pointer over the texts that contain tooltips, they do not work in the desktop version.

**Steps to Reproduce**

Go to any view where there are texts with tooltips and try to position the pointer over one of those texts
   ...

**Expected Behavior**

Tooltips are very helpful to help understand information that is sometimes not visible to the naked eye, therefore, this should work as expected and provide the information that it is supposed to show.

**Additional Context**

I was able to validate that this only happens in the desktop version

**Comment by Chef-Cheems** [comment]
@danielomontero what browser (and OS) are you using? I just checked on Chrome, Brave, Firefox and Safari and they all work for me 🤔 
Can you also provide browser version in case this is the issue with old browser.

**Comment by danielomontero** [comment]
@Chef-Cheems  It's true, I just verified that this only happens on one of my laptops, I tried on another laptop that I have available, and if it works, then I think the problem is me.
