### ISSUE TITLE
Can't use npm-link with pancake-frontend

### ISSUE THREAD

**Issue by Shofol** [pancakeswap/pancake-frontend#1622]
**Bug Description**
I'm trying to use ```@pancake-uikit``` locally with ```pancake-frontend```. Wanted to see how the UI changes with uikit component changes. But after linking the frontend can't find the ```@pancake-uikit``` module. 

**Steps to Reproduce**

1. Go to ```@pancake-uikit``` package from ```@pancake-toolkit```
2. Run ```npm-link``` on ```@pancake-uikit``` folder
3. After finishing linking run ```npm-link``` on ```pancake-frontend``` root directory.

**Expected Behavior**
The ```@pancake-uikit``` should be usable after ```npm-link```

**Environment:**
Device and OS: Windows 10.
Browser: Google Chrome
Node Version: 14.16.0
IDE: VSCode

**Comment by trungnqpro** [comment]
should use yarn link instead of npm link, but i got this error, dont know why
`Type 'DefaultTheme' is not assignable to type 'DefaultTheme | ((theme: DefaultTheme) => DefaultTheme)'.
  Type 'DefaultTheme' is not assignable to type '(theme: DefaultTheme) => DefaultTheme'.
    Type 'DefaultTheme' provides no match for the signature '(theme: DefaultTheme): DefaultTheme'`
    
    `<ThemeContext.Provider value={{ isDark, toggleTheme }}>
      <SCThemeProvider theme={isDark ? dark : light}>{children}</SCThemeProvider>
    </ThemeContext.Provider>`

**Comment by Shofol** [comment]
Tried with '''yarn-link''' too. But couldn’t run the application.

**Comment by surendrapathak01** [comment]
> should use yarn link instead of npm link, but i got this error, dont know why
> `Type 'DefaultTheme' is not assignable to type 'DefaultTheme | ((theme: DefaultTheme) => DefaultTheme)'. Type 'DefaultTheme' is not assignable to type '(theme: DefaultTheme) => DefaultTheme'. Type 'DefaultTheme' provides no match for the signature '(theme: DefaultTheme): DefaultTheme'`
> 
> ```
> `<ThemeContext.Provider value={{ isDark, toggleTheme }}>
>   <SCThemeProvider theme={isDark ? dark : light}>{children}</SCThemeProvider>
> </ThemeContext.Provider>`
> ```

+1
Same case here

**Comment by surendrapathak01** [comment]
> Tried with `yarn-link` too. But couldn’t run the application.

In my case, I had to install types manually after running yarn link.

**Comment by Shofol** [comment]
> > Tried with `yarn-link` too. But couldn’t run the application.
> 
> In my case, I had to install types manually after running yarn link.

Didn't ```styled-components``` make any error? Can you please describe your procedure?

**Comment by surendrapathak01** [comment]
> > > Tried with `yarn-link` too. But couldn’t run the application.
> > 
> > 
> > In my case, I had to install types manually after running yarn link.
> 
> Didn't `styled-components` make any error? Can you please describe your procedure?

Yes it did, installing types fixed some errors. But there was another error with ThemeProvider after that, this is not solved yet.

**Comment by Chef-Chungus** [comment]
@hachiojidev is there any guidance you can provide?

**Comment by hachiojidev** [comment]
We have had an ongoing issue with typing the default theme. Try declaring the theme like so

```
import { PancakeTheme } from '@pancakeswap/uikit/dist/theme'

declare module 'styled-components' {
  export interface DefaultTheme extends PancakeTheme {}
}
```
