### ISSUE TITLE
Subgraph is Very Slow

### ISSUE THREAD

**Issue by Flaming19** [pancakeswap/pancake-frontend#1645]
Current Subgraph is very slow 
https://bsc.streamingfast.io/subgraphs/name/pancakeswap/exchange-v2

Could you please provide some way so that we can use subgraph of pancake to build some thing for users.

**Comment by ChefKai** [comment]
Hello, we managed to improve the performance of the subgraph queries; please let us know if you have any issue! Thanks.

**Comment by Flaming19** [comment]
Thankyou,
Our App is using 3queries [Top Tokens, New Tokens, Hot Tokens].
New and Hot token queries are working fine now. But Top Tokens queries are still taking more time. 
Query For top tokens:
{
  pairs(first: 50 orderBy:volumeUSD 
    orderDirection:desc){
      id
      token0{
      symbol
      name
      id
      derivedBNB
      derivedUSD
      tradeVolumeUSD
      totalLiquidity
      }
    token1{
      symbol
      name
      id
      derivedBNB
      derivedUSD
      tradeVolumeUSD
      totalLiquidity
      }
    volumeUSD
    }
}

Thanks:
Goswapp Team
