### ISSUE TITLE
https://profile.pancakeswap.com or https://pancake-profile-api.vercel.app/

### ISSUE THREAD

**Issue by jcosta191** [pancakeswap/pancake-frontend#1647]
Please guys, with you are a decentralized dApp you must show all your code to people know where is putting the money!
Do you can share the vercel code app from the url "https://profile.pancakeswap.com" to get information about the profile, leaderboard, teams, that connect to thegraph "Profile" and "TradingComepetitionV1"?
Continue with the great job!
Thanks

**Comment by jcosta191** [comment]
When i say vercel code i'm talking about the repo "pancake-profile-api"

**Comment by RabbitDoge** [comment]
It's already OS

**Comment by jcosta191** [comment]
Where is the source code of pancake-profile?
Can you send the link please?
Very thankful
