### ISSUE TITLE
Where is the source code of pancake-profile-api?

### ISSUE THREAD

**Issue by jcosta191** [pancakeswap/pancake-frontend#1708]
Where is the source code of pancake-profile-api?
Can you send the link please?
Very thankful

_Originally posted by @jcosta191 in https://github.com/pancakeswap/pancake-frontend/issues/1647#issuecomment-878968131_

**Comment by RabbitDoge** [comment]
@ChefKai

**Comment by KurtBoltHelp** [comment]
Hello, have you been able to rectify this ?

**Comment by chimpydev** [comment]
> Hello, have you been able to rectify this ?

No, they dont care at all! They dont share the repo!

**Comment by jcosta191** [comment]
> Hello, have you been able to rectify this ?

Sir they don't share with us

**Comment by KurtBoltHelp** [comment]
Don’t get you ?

**Comment by ChefKai** [comment]
Hello, thanks for your interest; the codebase will be released this week! 🎉

**Comment by ChefKai** [comment]
Repository has been open-sourced at [pancakeswap/pancake-profile-api](https://github.com/pancakeswap/pancake-profile-api)
