### ISSUE TITLE
TrustWallet Connection on Mobile Browers

### ISSUE THREAD

**Issue by 0xMaxim** [pancakeswap/pancake-frontend#1710]
I just installed trustwallet app on both iPhone and iPad, and it is unable to connect with trustwallet, and just showing `Provider Error`.

**Comment by ChefNina** [comment]
You have TrustWallet app newer than v6.0?
Then that does not have dapp browser and you can't connect if you choose "TrustWallet" directly from browser UI but you have to use WalletConnect.
Here is the guide: 
https://community.trustwallet.com/t/using-walletconnect-to-access-pancakeswap/212307

If you have the further question, please ask at our telegram community:
https://t.me/PancakeSwap
Remember Chefs/Admins never send DM you first.
