### ISSUE TITLE
The application isn't running, some error 

### ISSUE THREAD

**Issue by sahajkedia** [pancakeswap/pancake-frontend#1719]
C:/USER/Desktop/f2/src/state/hooks.ts
TypeScript error in C:/Users/Sahaj Kedia/Desktop/f2/src/state/e/hooks.ts(63,14):
Argument of type 'AsyncThunkAction<Farm[], number[], {}>' is n not assignable to parameter of type 'AnyAction'.
  Property 'type' is missing in type 'AsyncThunkAction<Farm[],], number[], {}>' but required in type 'AnyAction'.  TS2345   

    61 |     const pids = farmsToFetch.map((farmToFetch) => fa
farmToFetch.pid)
    62 |
  > 63 |     dispatch(fetchFarmsPublicDataAsync(pids))        
       |              ^
    64 |
    65 |     if (account) {
    66 |       dispatch(fetchFarmUserDataAsync({ account, pidsds }))

**Comment by medeirosfalante** [comment]
in src/state.ts have line typedof define 
export const useAppDispatch = () => useDispatch<AppDispatch>()

**Comment by Mjavala** [comment]
Ran into the same error, based on @medeirosfalante reply here's how I fixed it
- go to ``src/state/index.ts``
- change the following line: ``export const useAppDispatch = () => useDispatch<AppDispatch>()`` to
- export const useAppDispatch = () => useDispatch()

**Comment by Chef-Chungus** [comment]
@sahajkedia - are you still experiencing this issue?

**Comment by hachiojidev** [comment]
@sahajkedia What version of node are you running? Are you sure you have installed the latest dependencies (most importantly Typescript)?
