### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by hnovellaapps** [pancakeswap/pancake-frontend#1724]
Dear friends
I have some problems for test the web in local mode.
I install yarn and some dependencies, but when I do the yarn start (yarn run v1.22.10 / nodejs 14), I got this error:

"Failed to compile.

Failed to load config "@pancakeswap/eslint-config-pancake" to extend from.
Referenced from: E:\MEGA\Trading\swap\pancake-frontend-develop\.eslintrc  "

The web is launched in local port: http://localhost:3000/ and the favicon is loaded, but all the web is in blank.

I didn't find this issue in closed issues also

Please can anyone help me?

Thank you so much
Regards
Héctor

**Comment by KurtBoltHelp** [comment]
Hello, have you found a solution to it ?

**Comment by hnovellaapps** [comment]
Yes, installing and using GIT:

https://git-scm.com/download/win
