### ISSUE TITLE
[BUG] Pancakeswap profile setup isn't working

### ISSUE THREAD

**Issue by subham9777** [pancakeswap/pancake-frontend#1745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to setup pancakeswap's nft profile and while the part where we need to submit a name comes i write a non taken name and after clicking on submit it keeps loading forever. I tried this 7 times now and i have been charged more than 4$ for approving my nft now. 

### Expected Behavior

I expect this to take the name and create a profile for me as it is supposed to.

### Steps To Reproduce

Go to profile creation and try submitting a name

### Environment

```markdown
- Device: Rog Strix Scar 3
- OS: Windows 11
- Browser: Chrome
- Wallet: Metamask
```

**Comment by Chef-Chungus** [comment]
What is the error you receive?

**Comment by Chef-Chungus** [comment]
@ChefKai is there anything wrong with the API at the moment?

**Comment by subham9777** [comment]
Console shows this and the submit button keeps on going


Uncaught (in promise) Error: Extension context invalidated.
    at content.js:1
    at new Promise (<anonymous>)
    at g (content.js:1)
    at Object.apply (content.js:1)
    at content.js:1
    at content.js:1
    at Object.next (content.js:1)
    at content.js:1
    at new Promise (<anonymous>)
    at t (content.js:1)

**Comment by subham9777** [comment]
@Chef-Chungus  i removed the cache files and all the cookies and then tried again. It worked. I can close this now. Thanks
