### ISSUE TITLE
[BUG] Tooltips outside the screen

### ISSUE THREAD

**Issue by kashirin-dm** [pancakeswap/pancake-frontend#1748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have problems with tooltips anywhere. But in the screenshot problem on the Swap page. There I try to select any token and tap on the question button.
As a result, I get the help tooltip, but outside the screen.

![photo_2021-07-18_11-58-46](https://user-images.githubusercontent.com/40428935/126057325-fb379eac-d8f7-4cb3-b81b-5025d3802963.jpg)

### Expected Behavior

Tooltips should be intelligent and consider the position of anchor, show only inside of the screen.

### Steps To Reproduce

1. Find any tooltip button nearby the right screen corner. 
2. Tap on this.

### Environment

```markdown
- Device: Samsung S20
- OS: Android 11
- Browser: DApp browser
- Wallet: Trust Wallet
```

**Comment by Chef-Chungus** [comment]
@kashirin-dm - I've just tested, can't reproduce so this seems to be resolved now. I'll close for now, If the issue still exists for you, please reopen this ticket.
