### ISSUE TITLE
The undefined error occurred in the swapping

### ISSUE THREAD

**Issue by ryan85118** [pancakeswap/pancake-frontend#1755]
This state will happen when I use BNB(BSC-1) to swap to any coin.
![image](https://user-images.githubusercontent.com/54787650/126115963-540d4372-b0e4-4ffc-80c2-69cbf5169d0d.png)

**Comment by Chef-Chungus** [comment]
@RabbitDoge - Is this still an issue, do you know?

**Comment by Chef-Chungus** [comment]
@ryan85118 - I'm unable to reproduce this issue, so i'll close this for now. If this still exists, would you please create another issue?
