### ISSUE TITLE
heavy load pancakeswap

### ISSUE THREAD

**Issue by MrFatoni** [pancakeswap/pancake-frontend#1788]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

browser sending 2000++ request to rpc

![image](https://user-images.githubusercontent.com/47595359/127099517-ee3b943f-7504-4631-aab6-e1816e99b5cb.png)

### Expected Behavior

.

### Steps To Reproduce

.

### Environment

```markdown
Device: MacBook Pro
OS: Big Sur 11.3.1
Brower: Chome
Wallet: Metamask
===============
Device: IPhone 11
OS: IOS 14
Brower: Trustwallet
Wallet: Trustwallet
```

**Comment by Chef-Chungus** [comment]
@MrFatoni - This isn't an issue as far as I can tell from your report. 

There is high load because there is lots of data to load.

If you think there are unnecessary requests, please be more descriptive.
