### ISSUE TITLE
PANCAKE.INFO - PAIR STATS

### ISSUE THREAD

**Issue by matilareo** [pancakeswap/pancake-frontend#1800]
Hi guys, where can i found the code for this page?

https://pancakeswap.info/pool/0xD171B26E4484402de70e3Ea256bE5A2630d7e88D
![Screenshot from 2021-07-29 01-08-26](https://user-images.githubusercontent.com/57819962/127430251-dfc63d57-2af8-4eea-bc8d-24ab502dd5ce.png)

**I need to know how to calculate the "LP REWARD APR" and the "LP REWARD FEES 24H", THANK YOU !**

**Comment by Chef-Cheems** [comment]
Hi!
We're in the process of migrating info site code into this repository. Right now it's temporarily in private repo. Please check back in a week or so.

**Comment by matilareo** [comment]
> e process of migrating info site code into this repository. Right now it's temporarily in private repo. Please check back in a week or so.

Hi! thanks for answering me. It would be very helpful if you can provide me the way that **LP REWARD APR** is calculated. Is for an exercise of a job interview :)

**Comment by Chef-Cheems** [comment]
@matilareo APR is based on past week trading volume `const lpApr7d = (volumeUSDWeek * LP_HOLDERS_FEE * WEEKS_IN_YEAR * 100) / LPLiquidity` where LP_HOLDERS_FEE is `0.0017` , i.e. 0.17% you earn by being aliquidity provider. Other data received from StreamingFast.
`LP REWARD FEES 24H` is just `volumeUSDinLast24hours * LP_HOLDERS_FEE`

**Comment by matilareo** [comment]
@Chef-Cheems Awesome! Thank you so much!
