### ISSUE TITLE
[BUG] Removing avatar breaks the page

### ISSUE THREAD

**Issue by chef-bun** [pancakeswap/pancake-frontend#1824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Page goes blank

Console log errors:
<img width="535" alt="MBP3-2021 08 02-092701PM-Google Chrome_Your Profile | PancakeSwap - $15 859" src="https://user-images.githubusercontent.com/87682841/127871749-f0218ff4-ef38-45d1-8623-400cd3a47123.png">

### Expected Behavior

Page loads correctly

### Steps To Reproduce

- Remove avatar and deactivate profile
- Refresh the page or navigate to any page 

### Environment

```markdown
- Device: MacBook Pro
- OS: Big Sur 11.3.1
- Browser: Chrome
- Wallet: MetaMask

- Device: iPhone SE 2nd Gen
- OS: iOS 15
- Browser: MetaMask built-in DApp browser
- Wallet: MetaMask
```

**Comment by ChefKai** [comment]
Fixed with #1825, closing.
