### ISSUE TITLE
[BUG] Text colour of "tokenA/tokenB Burned" is too dark on remove liquidity window at night mode

### ISSUE THREAD

**Issue by ChefNina** [pancakeswap/pancake-frontend#1848]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Text colour of "tokenA/tokenB Burned" is too dark on remove liquidity window at night mode, it's a bit hard to see.

![image](https://user-images.githubusercontent.com/82930772/128328670-4f76a9cf-62f2-464b-b9f9-167619f121fa.png)

### Expected Behavior

The colour of all texts are enough clear to read. No issues at day mode.

![image](https://user-images.githubusercontent.com/82930772/128328710-3fc63bfe-0b83-4fdd-a820-49e95dd1107e.png)

### Steps To Reproduce

1. Follow "Remove liquidity" step
2. Click "Remove", then we can see this on confirmation window.

### Environment

```markdown
This is not environment specific issue.
- Device: PC
- OS: Windows 10
- Browser: Chrome any version
- Wallet: Not relevant with wallet
```

**Comment by Chef-Chungus** [comment]
@ChefHutch assigning this to you fam. Please clear within 7 days.

**Comment by ChefHutch** [comment]
Nice one thanks Nina - simple fix here https://github.com/pancakeswap/pancake-frontend/pull/1866
