### ISSUE TITLE
[BUG] External swap URL links fail to load output currency

### ISSUE THREAD

**Issue by jjs2484** [pancakeswap/pancake-frontend#1860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,

Have noticed external swap URL links recently began to fail to load the output currencies. Has the URL format changed?

### Expected Behavior

Click external URL swap links and it loads input and output currencies.

### Steps To Reproduce

1. Click external links to load swap output currency

example 1 - [https://pancakeswap.finance/swap#/swap?outputCurrency=0xcf9f991b14620f5ad144eec11f9bc7bf08987622](https://pancakeswap.finance/swap#/swap?outputCurrency=0xcf9f991b14620f5ad144eec11f9bc7bf08987622)

example 2 - [https://pancakeswap.finance/swap#/swap?outputCurrency=0xdb8d30b74bf098af214e862c90e647bbb1fcc58c](https://pancakeswap.finance/swap#/swap?outputCurrency=0xdb8d30b74bf098af214e862c90e647bbb1fcc58c)

2. No output currency is added.

### Environment

```markdown
- Device: Desktop
- OS: Mint or Windows
- Browser: Firefox or Chrome
- Wallet: Metamask
```

**Comment by fleon** [comment]
You have `swap` twice in the URL. The URLs should be:

example 1 - https://pancakeswap.finance/swap?outputCurrency=0xcf9f991b14620f5ad144eec11f9bc7bf08987622

example 2 - https://pancakeswap.finance/swap?outputCurrency=0xdb8d30b74bf098af214e862c90e647bbb1fcc58c

These URLs work.

**Comment by jjs2484** [comment]
thanks
