### ISSUE TITLE
[Feature Request] Make it load faster

### ISSUE THREAD

**Issue by quentincaffeino** [pancakeswap/pancake-frontend#1881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem you are facing?

I'm always frustrated with how long it takes to load even a landing page.

### Describe the solution you'd like

I'm not very familiar with the project to give any advice. But decreasing bundle size is a pretty obvious idea.

### How does this feature benefit PancakeSwap users and CAKE holders?

- Faster load time
- App will have a better feel to it since it feels faster
- Less battery usage
- Less CO2 emission (for people who care)

**Comment by aldoromo88** [comment]
Is it really too slow on your end?
It feels quite good to me even that I have a pretty bad connection speed, also considering that a lot of data is being queried from BSC I don't think there is too much room for improvement.

**Comment by quentincaffeino** [comment]
I would say I have okayish connection. We can look at [pagespeed rating](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fpancakeswap.finance%2F), I think it perfectly shows that the problem is present. Theoretically the improvement should be possible. Not sure if it is possible technically with this project though.

**Comment by Chef-Cheems** [comment]
Hi!
We're actually discussed it a lot recently. As mentioned in the [July recap medium post](https://pancakeswap.medium.com/pancakeswap-july-recap-a-lot-o-lotto-e285518fb874):
>As with any fast-growing project, as we’ve added more and more great stuff to PancakeSwap, we’ve also gathered a bit of technical debt.
We’ll be taking a short break from pumping out new features to spend a few weeks focusing on code maintenance and performance updates, so we can keep scaling efficiently without compromising on performance.

We have identified several performance issues and are going to work on it in the upcoming several weeks.
Will probably do some update on that when its live.

**Comment by aldoromo88** [comment]
Hey @Chef-Cheems, make a bounty list for those performance issues that are already identified 
I'll be glad to participate, and a lot of other devs over here for sure

**Comment by RabbitDoge** [comment]
As Cheems mentioned , the team is currently working on the performances issues
