### ISSUE TITLE
[BUG] cannot get current network on create profile

### ISSUE THREAD

**Issue by sites-hubix** [pancakeswap/pancake-frontend#1882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

IFO

### Current Behavior

Error cannot get current network in the last pass on create profile (developer console), after select my available user stay freeze and do not enable the confirm button 

After the error can not confirm the creation successful of my profile. 

I try two times and i have to pay the confirmation of avatar on both selection, but i only pay the avatar only the first time.

### Expected Behavior

Creation of profile successful.

### Steps To Reproduce

Basic steps of create a profile. 

I select the avatar, the team and the available user, nevertheless stay freeze on confirmation

### Environment

```markdown
- Device: Macbook pro
- OS: Big Sur 11.5
- Browser: Firefox
- Wallet: Metamask
```

### Anything else?

<img width="1616" alt="Captura de Pantalla 2021-08-11 a la(s) 00 25 19" src="https://user-images.githubusercontent.com/87125169/128969735-8c4f92e8-d1f8-4402-97f5-999b8c11cd9c.png">

**Comment by hachiojidev** [comment]
@sites-hubix Is there any other information you can give us? I just tried myself and had no issue (using basically the same setup you have).

**Comment by sites-hubix** [comment]
Hi, Thanks, I put all my cake coins in the farm, give me a couple hours to buy and try again, i get the same error but under the complete profile button show the message that i need 0.5 cake
