### ISSUE TITLE
Cannot add new token in farms section

### ISSUE THREAD

**Issue by uzair-ropstam** [pancakeswap/pancake-frontend#1883]
Hi,
I have to add PUG-BUSD in farms section.How I can get the process identifier (PID) of PUG token ?

PUG: https://bscscan.com/token/0xd7753a812f57C7A55197844193B49c3d93aD06A4

Also did not found PUG in https://github.com/pancakeswap/pancake-frontend/blob/master/src/config/constants/farms.ts

Following are current code changes.
// farms.ts
{
    pid: [ID], // where to get this pid
    lpSymbol: 'PUG',
    lpAddresses: {
      97: '',
      56: '0xd7753a812f57C7A55197844193B49c3d93aD06A4',
    },
    token: tokens.pug,
    quoteToken: tokens.busd,
  },
  
  
  // token.ts
   pug: {
    symbol: 'PUG',
    address: {
      56: '0xd7753a812f57C7A55197844193B49c3d93aD06A4',
      97: '',
    },
    decimals: 18,
    projectLink: 'https://pug.cash/',
  },
  
  
  
<img width="1677" alt="Screen Shot 2021-08-11 at 11 10 57 AM" src="https://user-images.githubusercontent.com/82560568/128978520-9089f8e9-6054-45dc-bbf1-a009a678c02d.png">

**Comment by RabbitDoge** [comment]
The farm config file contains on chain data. If there is not existing farm for a pair, adding it to the config file won't work

**Comment by foletrim** [comment]
@RabbitDoge, Thanks for your response.Can you please guide, How can i add PUG in chain data ?
It is already added in token list.
<img width="1473" alt="Screen Shot 2021-08-12 at 9 19 04 AM" src="https://user-images.githubusercontent.com/82560568/129138053-5541a42e-6293-4d45-9360-207af6885478.png">

**Comment by Chef-Chungus** [comment]
@foletrim -  the farms are business agreements with projects. 
If you wish to apply for a farm, you can apply for the farm auctions

**Comment by foletrim** [comment]
@Chef-Chungus , 
I'm trying for farm auctions but the form is for V2. currently project is running on v1.
when will v2 added in open source code ? or any migration guide ?
Thanks

<img width="1670" alt="Screen Shot 2021-08-13 at 9 48 18 AM" src="https://user-images.githubusercontent.com/82560568/129307486-11a26fa5-38da-4ffc-af7d-48227e8ff468.png">
<img width="1680" alt="Screen Shot 2021-08-13 at 10 05 52 AM" src="https://user-images.githubusercontent.com/82560568/129307501-7b094afe-885d-4a01-94ba-249c02c74840.png">

**Comment by foletrim** [comment]
@Chef-Chungus ,
I'm using following repositories:
front-end: https://github.com/pancakeswap/pancake-frontend
swap: https://github.com/pancakeswap/pancake-swap-interface-v1 (**archived now**)

Do I need to change the swap repository ?
