### ISSUE TITLE
Failed to compile src\hooks\useAuth.ts & src\utils\web3React.ts  / NOOB NEEDS HELP FROM GENIUSES

### ISSUE THREAD

**Issue by 56vgamer** [pancakeswap/pancake-frontend#1891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Open Admin Powershell in pancakeswap-frontend-develop folder > npm run start > localhost:3000 browser page shows up with 

Failed to compile
src\hooks\useAuth.ts
  Line 3:36:  Unable to resolve path to module '@binance-chain/bsc-connector'  import/no-unresolved

src\utils\web3React.ts
  Line 3:30:  Unable to resolve path to module '@binance-chain/bsc-connector'  import/no-unresolved

Search for the keywords to learn more about each error.

### Expected Behavior

I was expecting the pancakeswap front end to load

I am extremley new to using Powershell and source code editors. I have installed WSL, node.js , truffle, web3 following A youtube tutorial

### Steps To Reproduce

1. Open Admin Powershell in pancakeswap-frontend-develop folder
2. npm run start

### Environment

```markdown
- Device: Asus
- OS: Windows 10
- Browser: Chrome
- Wallet: MetaMask app
```

**Comment by RabbitDoge** [comment]
- Uses yarn and not npm
- Install dependencies before running the app
- If you are on Windows, uses gitbash

**Comment by AndriKusumaBhakti** [comment]
i got the same thing. i am using ubuntu 16:04 and yarn. is there any solution regarding my case?
