### ISSUE TITLE
SPA links don't work

### ISSUE THREAD

**Issue by chris-iwolf** [pancakeswap/pancake-frontend#1897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

Direct links like `https://domains.com/swap` don't work.
It worked on localhost but when I uploaded to hosting / vps, it shows 404.
It seems `_redirects` doesn't work.

### Expected Behavior

Go to direct link https://domain.com/pool or refresh, the SPA would load content.

### Steps To Reproduce

1. Build and upload to hosting
2. Go to direct link: https://domain.com/swap

### Environment

```markdown
- Device: Macbook
- OS: MacOS
- Browser: Any
- Wallet: Any
```

### Anything else?

It works perfect on localhost.

**Comment by RabbitDoge** [comment]
Hard to help without seing your code, but it's mostly related to a misuse of create-react-app or react-router. 
Internal linking should be done with react-router, external linking should be done with `<a>` tag/

**Comment by hachiojidev** [comment]
@chris-iwolf Are you redirecting all your traffic to `index.html`?

**Comment by chris-iwolf** [comment]
> Hard to help without seing your code, but it's mostly related to a misuse of create-react-app or react-router.
> Internal linking should be done with react-router, external linking should be done with `<a>` tag/

It's original code from pancakeswap repo. The only thing changed is domain settings.



> @chris-iwolf Are you redirecting all your traffic to `index.html`?

Yes, `/*    /index.html   200` in `_redirects`
