### ISSUE TITLE
Translations not approved and translations missing

### ISSUE THREAD

**Issue by RichardPK** [pancakeswap/pancake-frontend#19]
The Crowdin translation PR: https://github.com/pancakeswap/pancake-frontend/pull/16 implements all changes currently within Crowdin.

**Issues**

- [x] All translations in the `origin-UI` file need to be approved again, currently there are no approved translations for any language (meaning fallbacks will be used across the site).
- [x] The source string for 1 CAKE = 1 SYRUP is wrong @Chef-Chungus https://crowdin.com/translate/pancakeswap/8/en-en#326
- [ ] All translations within the file `origin-UI.csv` as of 14:27 UTC 10/20 have been implemented. But - there is definitely text in the app that isn't included in that file.
Note: I have included details in the readme of how to add a translation to the code once it has been added to Crowdin

**Comment by Chef-Chungus** [comment]
Closing due to issue age. Not sure if relevant anymore lol
