### ISSUE TITLE
[BUG] Link to trade on PancakeSwap (from INFO) is incorrect

### ISSUE THREAD

**Issue by Chef-Chungus** [pancakeswap/pancake-frontend#1909]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Info

### Current Behavior

https://pancakeswap.info/token/0x7130d2a12b9bcbfae4f2634d864a1ee1ce3ead9c

Click "Trade" it links to: https://exchange.pancakeswap.finance/#/swap?inputCurrency=0x7130d2a12b9bcbfae4f2634d864a1ee1ce3ead9c

This link does not pre-load the currency. 

### Expected Behavior

https://pancakeswap.info/token/0x7130d2a12b9bcbfae4f2634d864a1ee1ce3ead9c

Click "Trade" it links to: https://exchange.pancakeswap.finance/swap?inputCurrency=0x7130d2a12b9bcbfae4f2634d864a1ee1ce3ead9c

This link pre-loads the currency. 

### Steps To Reproduce

1. go to https://pancakeswap.info
2. Click on a token
3. Click trade button

### Environment

```markdown
Not Relevant.
```

### Anything else?

Adding this in here because we're in the process of merging INFO

**Comment by ChefKai** [comment]
Deployed today; closing.
