### ISSUE TITLE
[BUG] Searching a token using a checksummed address doesn't work

### ISSUE THREAD

**Issue by ChefKai** [pancakeswap/pancake-frontend#1911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Info

### Current Behavior

Searching a token using his *checksummed* smart contract address doesn't work

### Expected Behavior

Smart contract address should be lower-cased before being included in the search query to the subgraph, allowing the token to be found

### Steps To Reproduce

1. Go to https://pancakeswap.info/
2. Try to search for a token using his smart contract address

e.g.: 
`0x0E09FaBB73Bd3Ade0a17ECC321fD13a19e81cE82`: No results
`0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82`: Results

### Environment

```markdown
- Device: Any
- OS: Any
- Browser: Any
- Wallet: Any
```

### Anything else?

Priority TBD

**Comment by jasonrsadler** [comment]
Is `pancakeswap-info-v2` private?

**Comment by Chef-Cheems** [comment]
Fixed with #1951 merge.
