### ISSUE TITLE
Help to understand what is sousId in pools config

### ISSUE THREAD

**Issue by gomel-tdl1** [pancakeswap/pancake-frontend#1940]
I researched your repository for educational purposes and came across the config of the pools, for a long time I could not understand what this array consists of and especially could not understand what it is sousId. Please help me guys.
![image](https://user-images.githubusercontent.com/61886955/129930802-519fc9ec-2257-4cfc-9f0a-385ea4573d07.png)

**Comment by hachiojidev** [comment]
@gomel-tdl1 It is just a unique identifier to get a pool config.

**Comment by gomel-tdl1** [comment]
thank you)
