### ISSUE TITLE
[BUG] Failed to compile

### ISSUE THREAD

**Issue by alcyada** [pancakeswap/pancake-frontend#2006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

TypeScript error in /home/kingui/pancake-frontenit/src/hooks/useApproveCallback(86.7)

Argument of type "import("/home/kingui/pancake-frontend/node nodules/gethersproject/contracts/lib/index").Contract is not assignable to parameter of type import("/home/kingul/pancake-frontend
/node_modules/ethers/node_sodules/gethersproject/contracts/lib/index").Contract.

Types of property runningevents are incompatible.

Type [eventTag: string]: RunningEvent: 1 is not assignable to type [eventTag: string]:Running Event: }'. Two different types with this name exist, but they are unrelated.

Index signatures are incompatible.

Type 'Running Event is not assignable to type RunningEvent. Two different types with this name

exist, but they are unrelated. Types have separate declarations of a private property listeners". 152345

851

87 1

// estint-disable-next-tine consistent-return

return callWithGasPricel tokenContract.

"approve

[spender, useExact amount ToApprove.raw.toString(): Max256),

### Expected Behavior

It's supposed to compile

### Steps To Reproduce

npm install
npm run start

### Environment

```markdown
- Device: kvm 
- OS: ubuntu 20
- Browser: Firfox
- Wallet:
```

**Comment by alcyada** [comment]
> did you get this running?

No I didn't

**Comment by alcyada** [comment]
@tom-bowern can you help us with this?

**Comment by tom-bowern** [comment]
Unfortunately not I have the same issue :(

> @tom-bowern can you help us with this?

**Comment by alcyada** [comment]
> Unfortunately not I have the same issue :(
> 
> > @tom-bowern can you help us with this?
Sad to hear.

**Comment by alcyada** [comment]
@tom-bowern do you know of any alternative

**Comment by Nikhil1419** [comment]
Use Yarn instead!!

**Comment by chef-jojo** [comment]
Try following steps:
1. remove node_modules and package-lock.json (if you have)
2. yarn install

Free feel to re-open this issue if you still encounter this.

**Comment by farhanali2325** [comment]
I have done the above steps, but still, I am getting the same error. Can somebody guide me?
