### ISSUE TITLE
[BUG] <title>Cannot switch to BSC test network

### ISSUE THREAD

**Issue by AyuOKExChain** [pancakeswap/pancake-frontend#2024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Farms

### Current Behavior

https://github.com/pancakeswap/pancake-frontend
I got the latest front-end code from the warehouse, and downloaded it locally for yarn.
Established the local env.local configuration file
An error is reported when switching to the testnet network after yarn start
I didn't make any changes to other files, and all reported errors directly.

### Expected Behavior

https://github.com/pancakeswap/pancake-frontend
I got the latest front-end code from the warehouse, and downloaded it locally for yarn.
Established the local env.local configuration file
An error is reported when switching to the testnet network after yarn start
I didn't make any changes to other files, and all reported errors directly.

### Steps To Reproduce

https://github.com/pancakeswap/pancake-frontend
I got the latest front-end code from the warehouse, and downloaded it locally for yarn.
Established the local env.local configuration file
An error is reported when switching to the testnet network after yarn start
I didn't make any changes to other files, and all reported errors directly.

### Environment

```markdown
- Device: NA
- OS: NA
- Browser:NA
- Wallet:NA
```

### Anything else?

Error: call revert exception (method="aggregate((address,bytes)[])", errorArgs=["Multicall aggregate: call failed"], errorName="Error", errorSignature="Error(string)", reason="Multicall aggregate: call failed", code=CALL_EXCEPTION, version=abi/5.4.0)
multicall
src/utils/multicall.ts:27
  24 | 
  25 |     return res
  26 |   } catch (error) {
> 27 |     throw new Error(error)
  28 |   }
  29 | }
  30 | 
View compiled
async fetchBalances
src/views/Home/hooks/useFarmsWithBalance.tsx:30
  27 |   params: [farm.pid, account],
  28 | }))
  29 | 
> 30 | const rawResults = await multicall(masterChefABI, calls)
     | ^  31 | const results = farmsConfig.map((farm, index) => ({ ...farm, balance: new BigNumber(rawResults[index]) }))
  32 | const farmsWithBalances = results.filter((balanceType) => balanceType.balance.gt(0))
  33 | const totalEarned = farmsWithBalances.reduce((accum, earning) => {
View compiled
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.

**Comment by AmadeusStargazer** [comment]
running into this exact issue.

**Comment by ofirthedev** [comment]
> running into this exact issue.

Same. maybe it doesn't support testnet.
