### ISSUE TITLE
[BUG] Failed to compile src\components\Modal\ModalInput.tsx, Line 12:3:  'placeholder' PropType is defined but prop is never used  react/no-unused-prop-types

### ISSUE THREAD

**Issue by arbin304** [pancakeswap/pancake-frontend#2025]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

Pancake-Frontend is throwing random Type errors when uikit is installed from symlinked project.
It runs fine when @pancake-uikit is installed from npm.
The errors I'm getting right now is given below.

```
src\components\Modal\ModalInput.tsx
  Line 12:3:  'placeholder' PropType is defined but prop is never used  react/no-unused-prop-types

src\components\PageSection\CurvedDivider.tsx
  Line 7:3:  'svgFill' PropType is defined but prop is never used  react/no-unused-prop-types

src\views\AddLiquidity\index.tsx
  Line 254:9:  JSX props should not use functions  react/jsx-no-bind

src\views\FarmAuction\components\AuctionDetailsCard\AuctionSchedule.tsx
  Line 18:3:  'showForClosedAuction' PropType is defined but prop is never used  react/no-unused-prop-types

src\views\Pools\components\PoolCard\CardFooter\index.tsx
  Line 13:3:  'totalCakeInVault' PropType is defined but prop is never used  react/no-unused-prop-types

src\views\Predictions\components\RoundCard\CardHeader.tsx
  Line 11:3:  'blockNumber' PropType is defined but prop is never used  react/no-unused-prop-types

src\views\Profile\components\ConfirmProfileCreationModal.tsx
  Line 16:3:  'userName' PropType is defined but prop is never used  react/no-unused-prop-types

src\views\RemoveLiquidity\index.tsx
  Line 378:93:  JSX props should not use functions  react/jsx-no-bind
  Line 447:48:  JSX props should not use functions  react/jsx-no-bind
  Line 447:73:  JSX props should not use functions  react/jsx-no-bind
  Line 637:19:  JSX props should not use functions  react/jsx-no-bind

Search for the keywords to learn more about each error.
```

### Expected Behavior

Being able to run pancake-uikit repo along with pancake-frontend to tweak the components. 

### Steps To Reproduce

1. Clone pancake-frontend and pancake-toolkit repos.
2. Run yarn install and yarn build.
3. Create symlink for @pancakeswap/uikit using `yarn link` in pancake-toolkit/packages/pancake-uikit .
4. Run `yarn link '@pancakeswap/uikit'` in pancake-frontend project.
5. Run `yarn install --force`
6. Run `yarn start`

### Environment

```markdown
- Device: Asus
- OS: Windows 10
- Browser: Chrome
- Wallet: Metamask
```

### Anything else?

There actually are few errors with types in the pancake-frontend project, but doesnt show up unless I run symlinked uikit.

**Comment by nslog11** [comment]
+1

**Comment by Squiji** [comment]
+1

**Comment by Jokers-Exchange** [comment]
+1

**Comment by Jokers-Exchange** [comment]
Having the same problem here and I can't seem to fix it.

**Comment by CRuzylo** [comment]
> Having the same problem here and I can't seem to fix it.
> 
> (edit) I was able to finally fix the problem.
Curious how?
