### ISSUE TITLE
Unable to get farms to work with masterchef & website crashes when changing the masterchef address. 

### ISSUE THREAD

**Issue by Kryptedbbkick** [pancakeswap/pancake-frontend#2034]
Ok so I managed to quickly get pancake swap front end up and running. I deployed my own Factory and Router using pancakes contracts with no changes. I am able to trade, sell, add liquidity to a token, remove liquidity from a token.

What I can not seem to do is get farm's to work. All farms that appear display there information from pancakes side. So when I deploy my MasterChef.sol contract with no changes and change the address within (frontend>src>config>constants>contracts.ts) and reload my page all of the values nullify.

But if I reload the page on the "Home" the website will crash and display an error

`Error: call revert exception (method="aggregate((address,bytes)[])", errorArgs=["Multicall aggregate: call failed"], errorName="Error", errorSignature="Error(string)", reason="Multicall aggregate: call failed", code=CALL_EXCEPTION, version=abi/5.4.0)
`

My goal is to take it slow as I pick through the code but changing every line of code that references the pancake address and changing it to my own (also with no changes to the actual .sol code) it does not fix anything other then adding the word "Infinity" to the pancake price listed at the bottom right of the screen.

I've noticed the error only appears when the profile part of the home page loads. I know this is a request issue from it but I can not pin point where it is coming from.

**Using windows with Bash and Yarn**
Windows 10 pc, as well as tested with linux raspbian OS
Edge/Chrome

**Steps to reproduce trading:**
(In order of how I got everything setup step by step)
1. Download frontend, toolkit, and sdk then extract all 3 in the same folder.
2. Launch my router, factory, cake token, Masterchef, Syrup contracts without any changes. Then verify each contract.
3 Install each project (frontend, toolkit, & sdk) using "yarn install".
4. Change factory address and INIT_CODE_HASH in (sdk root>src>constants) then build the project with "yarn build".
5. Copy the dist file created in the root folder into the front end folder (front end> node_modules>@pancakeswap>sdk) .

Now we have a working trading system that runs on my own factory and router. You can do anything at this point from trading to selling and adding liquidity to tokens. 

**Steps to reproduce crash on farming:**

1. Make sure all values and addresses punched into the contracts are set correctly.
2. Change masterchef contract address from "Panckeswaps" to ours. (front end>src>config>constants>contracts.ts)
3. Reload home page.
4. As page reloads everything looks normal until the profile located at the top starts to load then we are presented with a crash.

**Expectations**
I had assumed changing this value alone would be enough to redirect values to my Masterchef contract. If anyone can assist me with figuring this out that would be awesome.

Note: I did add the liquidity tokens into the masterchef "add" function to see if this would resolve the issue. Normally I would not be able to add anything to a farm without getting the error "Do you add enough gas?" but that is after I hit "activate farm" then "Stake". 

Update: 

I managed to get everything up and running! What I was missing was the hooks.ts file. Within it you can find pid 251 and 252. Changing these to match both my cake-busd and bnb-busd as well as changing the cake token address within tokens.ts managed to fix all of my issues. Tho some of my tokens will not display their APR 3 will however. 

The only thing I can't get my head around is that my price is always stuck at 1.000 on the bottom left hand side. Does anyone know a fix for this? Is this just due to how small the liquidity is? (14 cents). 
![Screenshot (63)](https://user-images.githubusercontent.com/22475186/131494908-17558961-30a2-4b79-8b18-305d1947bb5c.png)

**Comment by Kryptedbbkick** [comment]
I managed to get staking to work tho the website still will not show stuff such as "APR and X value".

**Comment by Kryptedbbkick** [comment]
Put a few more hours into it and managed to fix the issue with the multiplier not displaying for the Farms and the crashing that occurs on the home screen. Though the last two issues I am still trying to resolve is the APR not displaying for my farms and home screen profile display not showing total
![01](https://user-images.githubusercontent.com/22475186/131452306-8b7c6c9c-18a5-420e-84f6-f9e92f598642.PNG)
![02](https://user-images.githubusercontent.com/22475186/131452309-a8e9aff0-930b-4fe9-8aad-464f203dae2b.PNG)
.

**Comment by rkpapps** [comment]
I Stuck at same situation like you as you told i not found where is hooks.ts please clear how you solve the issue

**Comment by Kryptedbbkick** [comment]
> I Stuck at same situation like you as you told i not found where is hooks.ts please clear how you solve the issue

You can find hooks.ts at (frontend>src>state>farms>hooks.ts)

The required lines needing change are on line (52)(109)(113)

Make sure these pids match your pids accordingly. So 251 should be Cake/BUSD and 252 BNB/BUSD. Though I have not fully figured out some other issues I am facing this is how I managed to get APR, and value of my token to finally appear. Though the value is incorrect. I am currently starting from scratch with the knowledge on how I have changed everything so far to attempt to fix it.

**Comment by Kryptedbbkick** [comment]
I believe I have finally cracked it and got everything up and running perfectly. I will be creating a step by step guide for those who are interested as well as adding a step by step on here incase you just want to follow simple text. I will continue to update as I move along and finish up my goal of just getting a simple working pancake swap clone. 

If I run in to anymore errors I will update the thread.

**Comment by rkpapps** [comment]
Can we connect via telegram @techcsc i need you help

**Comment by Kryptedbbkick** [comment]
So I documented all changes I made. Started everything from scratch to test it out once more. I'm back to a crashing home screen, price being $0.000, and APR still not showing for some farms. With that changing the farm pid within the fetchFarmPrices and hooks file I am able to make it say $1.000 for some reason. The price should appear as just over $9.XXX. If anyone is able to assist with some bug fixes please let me know!

**Comment by mirufa1211** [comment]
Hi ! Thank you for your sharing! I want to ask about how to determine the pid for the Farms I created from the liquidity Pool or add a farm.

**Comment by Kryptedbbkick** [comment]
I managed to get it up and running with Trading, Farming, and Pools. All work and display correct information. I narrowed down the crash on the home page that I previously thought to be that the website was trying to pull farm data and could not for some reason so it would crash. Truthfully it was pulling pool information that was requesting pid numbers from the farm's that did not exist within Masterchef.sol. I plan to make a full doc on how to accomplish setting up your own Pancake Hard Fork.

**Comment by mirufa1211** [comment]
if as you describe , pid may be custom by owner but not has defined in masterchef. if i want using it , i can defined for cake-busd , bnb-busd custom pid and setting in hook.ts.
lpAddress i can get it on liquidity Pools for swaps ???
I using clone pancake for bsc testnet  

Thanks you help me .

**Comment by rkpapps** [comment]
Finely crash has been fixed can you please guide on how to show apr

**Comment by rkpapps** [comment]
Still Waiting for your Guide https://github.com/Kryptedbbkick

**Comment by AmadeusStargazer** [comment]
any news on the guide?

**Comment by DiornanR** [comment]
Go src/state/farm/fetchFarmsPrices.ts 

const bnbBusdFarm = farms.find((farm) => farm.pid === 6)

**Comment by 0x-m1cro** [comment]
Hi @Kryptedbbkick would you be kind to drop the links for frontend, uikit & sdk with commit id. Appreciate it guys.

Thanks!
