### ISSUE TITLE
Not possible to run in bsc testnet

### ISSUE THREAD

**Issue by mastercheff-alfajor** [pancakeswap/pancake-frontend#2076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

I run pancake swap frontend but when I try to switch to bsc testnet it doesn't work.

### Expected Behavior

Working with testnet.

### Steps To Reproduce

BSC testnet
metamask connect
It doesn't allow me to run testnet in metamask

### Environment

```markdown
- Device: 
- OS: 
- Browser:
- Wallet:
```

**Comment by mastercheff-alfajor** [comment]
Hi @Chef-Chungus , do you have an update of this ticket?

**Comment by Chef-Chungus** [comment]
@mastercheff-alfajor - We are aware of this and the PCS frontend doesn't currently support testnet. It's in our plans to add testnet support in the future once we have some time.

**Comment by ngthtung** [comment]
@Chef-Cheems
I wanna run my project in local and use testnet, I set up REACT_APP_CHAIN_ID in file .env.development is 97. It's seem like not work,
Do you have any document about setup local testnet ?

Thank you.
