### ISSUE TITLE
[BUG] Voting totals not accurate

### ISSUE THREAD

**Issue by R-K-H** [pancakeswap/pancake-frontend#2088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

The current vote for HERO https://pancakeswap.finance/voting/proposal/QmVAAiVqeLSTZtSzMVHEwwAHoCKkZS9AM3FnH9rEX5V8oW is not reflective of the true voting total.

<img width="829" alt="Screen Shot 2021-09-05 at 7 20 46 PM" src="https://user-images.githubusercontent.com/1007667/132144150-dbe23c5a-b4de-4eeb-bc4a-a311d7908183.png">
<img width="369" alt="Screen Shot 2021-09-05 at 7 20 39 PM" src="https://user-images.githubusercontent.com/1007667/132144152-6381a416-d83a-43f7-bc06-65ec0b63507a.png">

### Expected Behavior

The vote totals should show the total in aggregate of the vote tally.

### Steps To Reproduce

Visit https://pancakeswap.finance/voting/proposal/QmVAAiVqeLSTZtSzMVHEwwAHoCKkZS9AM3FnH9rEX5V8oW

### Environment

```markdown
- Device: MacBook Pro
- OS: Big Sur 11.5.1
- Brower: Chome, Brave
- Wallet: Metamask
```

**Comment by R-K-H** [comment]
PR in to fix this https://github.com/pancakeswap/pancake-frontend/pull/2090

**Comment by R-K-H** [comment]
Fix merged.

**Comment by R-K-H** [comment]
Sorry to re-open this. I should have waited for build to complete and verify. This is working for the approval votes, but it snaps back the declined.

See screenshot and video below:

<img width="409" alt="Screen Shot 2021-09-05 at 10 10 41 PM" src="https://user-images.githubusercontent.com/1007667/132151158-45c7390e-ad0e-4d06-80e7-698cc4f950a9.png">

https://user-images.githubusercontent.com/1007667/132151223-8f83b05b-7e3c-4631-a6e4-5e52553028ff.mov

**Comment by hachiojidev** [comment]
@R-K-H Nice catch, let me see what is going on.

**Comment by R-K-H** [comment]
Also the vote totals are changing as well.. 


<img width="611" alt="Screen Shot 2021-09-05 at 10 18 57 PM" src="https://user-images.githubusercontent.com/1007667/132151416-0d7cec70-a41f-4eba-96ad-9c988e919682.png">

**Comment by R-K-H** [comment]
It seems that is changes once the verify request is made.

<img width="1056" alt="Screen Shot 2021-09-05 at 10 22 38 PM" src="https://user-images.githubusercontent.com/1007667/132151641-81962500-6824-40b1-b26a-ce6ec5b30678.png">

**Comment by R-K-H** [comment]
Even the original number returned is bizarre looking at snapshot.org so seems like this might be deeper.

https://snapshot.org/#/cake.eth/proposal/QmVAAiVqeLSTZtSzMVHEwwAHoCKkZS9AM3FnH9rEX5V8oW
