### ISSUE TITLE
[BUG] Collectibles - Claim button is visible even after the claiming deadline passed.

### ISSUE THREAD

**Issue by ChefNina** [pancakeswap/pancake-frontend#2098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

The claiming deadline is passed already, but collectibles page still shows “Claim” button.
![image](https://user-images.githubusercontent.com/82930772/132593194-ee5f7040-5495-49b5-b4dc-be7d65cf1ba0.png)

### Expected Behavior

Once the claiming deadline is passed, "Claim" button is not shown on collectibles page.

### Steps To Reproduce

Go to collectibles page with the claiming right for NFT which claiming deadline is passed.

### Environment

```markdown
- Device: any
- OS: any
- Browser: any
- Wallet: any
```

**Comment by memoyil** [comment]
the image is missing

**Comment by ChefNina** [comment]
re-updated the image!

**Comment by memoyil** [comment]
> re-updated the image!

Fix is ready you can test it
