### ISSUE TITLE
[BUG] TypeScript error in pancake-frontend/src/hooks/useApproveCallback.ts(86,7)

### ISSUE THREAD

**Issue by MAhmedSaeedi** [pancakeswap/pancake-frontend#2125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

pancake-frontend/src/hooks/useApproveCallback.ts
TypeScript error in pancake-frontend/src/hooks/useApproveCallback.ts(86,7):
Argument of type 'import("C:/pancake-frontend/node_modules/@ethersproject/contracts/lib/index").Contract' is not assignable to parameter of type 'import("C:/pancake-frontend/node_modules/ethers/node_modules/@ethersproject/contracts/lib/index").Contract'.
  Types of property '_runningEvents' are incompatible.
    Type '{ [eventTag: string]: RunningEvent; }' is not assignable to type '{ [eventTag: string]: RunningEvent; }'. Two different types with this name exist, but they are unrelated.
      Index signatures are incompatible.
        Type 'RunningEvent' is not assignable to type 'RunningEvent'. Two different types with this name exist, but they are unrelated.
          Types have separate declarations of a private property '_listeners'.  TS2345

    84 |     // eslint-disable-next-line consistent-return
    85 |     return callWithGasPrice(
  > 86 |       tokenContract,
       |       ^
    87 |       'approve',
    88 |       [spender, useExact ? amountToApprove.raw.toString() : MaxUint256],
    89 |       {

### Expected Behavior

Frontend running.

### Steps To Reproduce

1. Clone repo
2. Install npm modules
3. execute npm start

### Environment

```markdown
- Device: Laptop
- OS: Win 10
- Browser: Chrome
- Wallet: Metamask
```

**Comment by ls-jordan** [comment]
Running npm update resolved this issue for me.

**Comment by MAhmedSaeedi** [comment]
npm update does get rid of this error but now there are new  errors
#2126

**Comment by ngocanhth** [comment]
How to fix this bug: Type 'RunningEvent' is not assignable to type 'RunningEvent'. Two different types with this name exist, but they are unrelated.
Types have separate declarations of a private property '_listeners'. TS2345

I ran this code before about 2 months ago and it worked fine, until today I run it again it doesn't work, I guess there is some package update so it is no longer compatible with the old version, but my reactjs capabilities are limited

**Comment by ngocanhth** [comment]
Fuck, It was a bug with the package setting, now it's working fine

**Comment by MAhmedSaeedi** [comment]
> Fuck, It was a bug with the package setting, now it's working fine

Can you share your fix ? Still stuck on this error. Thank you

**Comment by Mur-Token-BSC** [comment]
me to same error

**Comment by cornerdev23** [comment]
Same error here, please share the fix

**Comment by MAhmedSaeedi** [comment]
Cloning this repo again and using **yarn** instead of **npm install** , fixed this error for me.
