### ISSUE TITLE
[Dev Question] Run pancake in testnet

### ISSUE THREAD

**Issue by ngthtung** [pancakeswap/pancake-frontend#2165]
Hi team,

Currently, I'm clone this project and change REACT_APP_CHAIN_ID is my chain id but it's not work. Should I do some thing else? Do you have any document about setup local testnet like BSC testnet ?

I'm looking forward to hearing from you
Thank you.

**Comment by ShaunLWM** [comment]
I have tried just changing the chain id to testnet but I think there are some things that are not set up for testnet yet. It just kept on crashing. Or maybe I'm wrong.

**Comment by ngthtung** [comment]
I change Ropsten, Kovan testnet -> it's work.
but cannot change my testnet

**Comment by ngthtung** [comment]
It's turn out I have a problem when config function pair address. So I need change init code hash in my custom, and it's work fine.
I will close this issues
