### ISSUE TITLE
Cannot add new images

### ISSUE THREAD

**Issue by mrparkersson** [pancakeswap/pancake-frontend#2170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Farms

### Current Behavior

App Doesn't permit an addition of images because it is too nested

### Expected Behavior

A simple challenge to test the mind skills and flow

### Steps To Reproduce

Make components clear and other features editable 

### Environment

```markdown
- Device: 
- OS: 
- Browser:
- Wallet:
```

**Comment by Chef-Chungus** [comment]
This issue isn't reporting a bug? I'll be closing this - Bugs are for user-facing issues.
