### ISSUE TITLE
[BUG] Duplicate navigation tab bar in swap page 

### ISSUE THREAD

**Issue by memoyil** [pancakeswap/pancake-frontend#2198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

It has duplicate tab bar.

<img width="877" alt="image" src="https://user-images.githubusercontent.com/2213635/133411233-891cb1dc-4eff-4ad3-94f4-f2d386f0768d.png">

### Expected Behavior

It should show only one

### Steps To Reproduce

Go to swap
See duplicate tab bar

### Environment

```markdown
- Device: 
- OS: 
- Browser:
- Wallet:
```

**Comment by Chef-Chungus** [comment]
@0xCorgi please remove these buttons
![image](https://user-images.githubusercontent.com/71833681/133567558-0dc678ed-e367-40b6-8475-ba4fb3e93192.png)
