### ISSUE TITLE
[BUG] Footer navigation not working properly

### ISSUE THREAD

**Issue by memoyil** [pancakeswap/pancake-frontend#2199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

Footer navigation bar not working properly. When click nothing happens. 3 dot also shows nothing

<img width="381" alt="image" src="https://user-images.githubusercontent.com/2213635/133411631-40904b16-160b-49d1-9118-683f30c68f71.png">

### Expected Behavior

It should navigate 

### Steps To Reproduce

1. Go to webpage
2. Navigate through footer bar menu
3. See it doesn't response

### Environment

```markdown
- Device: 
- OS: 
- Browser:
- Wallet:
```

**Comment by Chef-Chungus** [comment]
@memoyil I can't reproduce this - please provide more contextual information

**Comment by memoyil** [comment]
@Chef-Chungus I checked again,  It only doesn't work on desktop firefox, I tried in firefox mobile and it works. I am closing the issue
