### ISSUE TITLE
[BUG] Uncaught Exception Fetching data of Pools

### ISSUE THREAD

**Issue by dxblouie** [pancakeswap/pancake-frontend#2395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Info

### Current Behavior

Pools and Token Info pages fail to load data, and developer console repeatedly shows an uncaught exception
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'number')
    at 24.a623d601.chunk.js:1
    at l (3.a97bdabe.chunk.js:1)
    at Generator._invoke (3.a97bdabe.chunk.js:1)
    at Generator.next (3.a97bdabe.chunk.js:1)
    at r (3.a97bdabe.chunk.js:1)
    at s (3.a97bdabe.chunk.js:1)
    at 3.a97bdabe.chunk.js:1
    at new Promise (<anonymous>)
    at 3.a97bdabe.chunk.js:1
    at 24.a623d601.chunk.js:1
```

### Expected Behavior

Page should populate and load pool data

### Steps To Reproduce

1. go to https://pancakeswap.finance/
2. click on ...
3. click on info
4. pools won't load in this page
5. pools also won't load if you click on Pools subnav
6. token info page fails to load completely

additionally, i tried on a fork made of pancakeswap and changed the RPC Backend under `REACT_APP_NODE_1/2/3/4` with no difference.

example direct links:
https://pancakeswap.finance/info/token/0x0255af6c9f86F6B0543357baCefA262A2664f80F
https://pancakeswap.finance/info/pool/0xB506424EA3aC7a907f8411a842B8A895D739Df0F

### Environment

```markdown
- Device: PC and Phone
- OS: Windows and Android
- Browser: Chrome
- Wallet: Metamask (same behavior if connected or disconnected)
```

**Comment by ChefKai** [comment]
This bug is dependent on TheGraph and the `Blocks` subgraph, it's being working on

**Comment by dxblouie** [comment]
Thank you @ChefKai 
do you have their bug reports handy?
also is this global affecting all pools/tokens? or is there a workaround?

You guys are awesome.. thank you :)

**Comment by ChefKai** [comment]
> Thank you @ChefKai do you have their bug reports handy? also is this global affecting all pools/tokens? or is there a workaround?
> 
> You guys are awesome.. thank you :)

No we don't, this was a localized issues with a few subgraphs hosted on `bsc` network. It has been restarted, blocks have synced to head, and .info is working again! Thank you for opening the issue! 🎉
