### ISSUE TITLE
Pancakeswap documentation is returning 404

### ISSUE THREAD

**Issue by lawweiliang** [pancakeswap/pancake-frontend#2495]
Hi Admin,
Something wrong with your documentation page.
![image](https://user-images.githubusercontent.com/34936929/136687246-c1a5e729-5986-4895-ba64-08f3ccfdcaf9.png)

**Comment by ChefNina** [comment]
Hi @lawweiliang , @philiparthurmoore 
Thanks for raising the issue ticket. It is working fine for me too now, so let me close this ticket.
From next time, please create the doc-relevant issue tickets in doc repository.
https://github.com/pancakeswap/pancake-document/issues

**Comment by lawweiliang** [comment]
I see, I think the website is under maintenance just now. Thanks @ChefNina @philiparthurmoore .
Both of you are super efficient. Love it. Thanks
