### ISSUE TITLE
[BUG] Token showing up as "unknown" in the analytics page.

### ISSUE THREAD

**Issue by sharp2448** [pancakeswap/pancake-frontend#2520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Info

### Current Behavior

The token name for my token on the analytics page are displayed as "unknown". Also the price doesn't match.
![image](https://user-images.githubusercontent.com/30528303/137228491-387bceee-2b29-42b8-9e0d-abc6e7d7cdfb.png)

https://pancakeswap.finance/info/token/0x43a0c5eb1763a211aa3c05849a617f2ee0452767

### Expected Behavior

Show the correct name of token and right price.

### Steps To Reproduce

Go to https://pancakeswap.finance/info/token/0x43a0c5eb1763a211aa3c05849a617f2ee0452767 and see.

### Environment

```markdown
- Device: For everybody
- OS: For everybody
- Browser: For everybody
- Wallet: For everybody
```

### Anything else?

I'm not only one. Found some people with same issue while I was googling.
https://www.reddit.com/r/BinanceSmartChain/comments/pm5pvk/why_my_token_name_and_symbol_are_not_displayed_on/
https://www.reddit.com/r/pancakeswap/comments/pq1hua/does_anyone_know_why_unknown_appeared_as_the_name/
https://www.reddit.com/r/pancakeswap/comments/pwyou3/token_showing_up_as_unknown_in_the_analytics_page/

**Comment by ChefNina** [comment]
@sharp2448 
This issue has been resolved. Please cross check at your end.

**Comment by Alferdize** [comment]
Token Shown up as "Unknown". My token address https://pancakeswap.finance/info/token/0xc36ce2209f1824c47bb9a6c40b43a5326a0f5c0a
