### ISSUE TITLE
front end giving error in arch linux with firefox and node v16.10.0 and npm 7.24.1

### ISSUE THREAD

**Issue by dannyc2702** [pancakeswap/pancake-frontend#2527]
Failed to compile.

src/components/ExpandableSectionButton/ExpandableSectionButton.tsx
  Line 36:3:  defaultProp "expanded" has no corresponding propTypes declaration  react/default-props-match-prop-types

src/components/Modal/ModalInput.tsx
  Line 13:3:  'placeholder' PropType is defined but prop is never used  react/no-unused-prop-types

src/components/PageSection/CurvedDivider.tsx
  Line 7:3:  'svgFill' PropType is defined but prop is never used  react/no-unused-prop-types

src/components/Toast/DescriptionWithTx.tsx
  Line 9:3:  'description' PropType is defined but prop is never used  react/no-unused-prop-types

src/views/AddLiquidity/index.tsx
  Line 251:9:  JSX props should not use functions  react/jsx-no-bind

src/views/FarmAuction/components/AuctionDetailsCard/AuctionSchedule.tsx
  Line 18:3:  'showForClosedAuction' PropType is defined but prop is never used  react/no-unused-prop-types

src/views/Home/components/CompositeImage.tsx
  Line 74:3:  'animate' PropType is defined but prop is never used  react/no-unused-prop-types

src/views/PancakeSquad/components/Buttons/EndEvent.tsx
  Line 11:3:  'userStatus' PropType is defined but prop is never used  react/no-unused-prop-types

src/views/PancakeSquad/components/Buttons/Mint.tsx
  Line 18:3:  'numberTokensOfUser' PropType is defined but prop is never used  react/no-unused-prop-types

src/views/PancakeSquad/components/Header/SaleProgress.tsx
  Line 9:3:  'userStatus' PropType is defined but prop is never used  react/no-unused-prop-types

src/views/Pools/components/PoolCard/CardFooter/index.tsx
  Line 13:3:  'totalCakeInVault' PropType is defined but prop is never used  react/no-unused-prop-types

src/views/ProfileCreation/ConfirmProfileCreationModal.tsx
  Line 18:3:  'userName' PropType is defined but prop is never used  react/no-unused-prop-types

src/views/RemoveLiquidity/index.tsx
  Line 378:93:  JSX props should not use functions  react/jsx-no-bind
  Line 447:48:  JSX props should not use functions  react/jsx-no-bind
  Line 447:73:  JSX props should not use functions  react/jsx-no-bind
  Line 640:19:  JSX props should not use functions  react/jsx-no-bind

Search for the keywords to learn more about each error.

**Comment by chef-jojo** [comment]
duplicated see https://github.com/pancakeswap/pancake-frontend/issues/2006#issuecomment-978816885
