### ISSUE TITLE
always staying at confirming "set your name"

### ISSUE THREAD

**Issue by yonger1516** [pancakeswap/pancake-frontend#2558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

always staying at confirming "set your name" more than for 12 hours 

### Expected Behavior

success to confirm and complete profile activation 

### Steps To Reproduce

setup profile 

### Environment

```markdown
- Device: 
- OS: 
- Browser:
- Wallet:
```

**Comment by yonger1516** [comment]
![image](https://user-images.githubusercontent.com/6733760/139589691-cb57fd65-3d95-4b7a-9b3e-b57dc97b9e31.png)

**Comment by memoyil** [comment]
Can you refresh your page and go to the set name step again and paste your username at one go (instead of typing it).

**Comment by yonger1516** [comment]
pasting username didn't works too.  Any other workarounds to resolve it  ?

**Comment by memoyil** [comment]
Which browser are you using?

**Comment by yonger1516** [comment]
chrome with latest version
