### ISSUE TITLE
Refactoring: fetch status enums

### ISSUE THREAD

**Issue by Chef-Cheems** [pancakeswap/pancake-frontend#2580]
Right now we have several enums throughout the app that do basically the same thing - indicate whether or not something is IDLE, LOADING, LOADED or FAILED.
For some reason we never standardized this behavior so there are lots of duplicated enums that do the same thing but defined in multiple different files and have different names for statuses.

Would be great to update all this to have 1 standard `FetchStatus` enum used everywhere.
It might also require some additional logic as some places don't handle FAILED as I remember.

A bit of a serious task as it will touch a lot of places, but ultimately it has to be done, we can't redefine same thing over and over again for every new fetch request 😅

**Comment by bariOmymen** [comment]
hello. I found enums that have loadingStatus and these enum have states as LOADING and LOADED and also found fetchStatus enums with states as FETCHING and FEATCHED. 
so I a couple of questions:
are fetchStatus and loadingStatus have the same uses? if yes, do we change LOADING and LOADED states to FETCHING and FETCHED? because I think this will result in 1 standard FetchStatus enum.
do we locate the standard FetchStatus enum in state/types file or have it located in a different place?

**Comment by Chef-Cheems** [comment]
Yeah, I believe the use case for all of them is the same. let's rename `LOADING` & `LOADED` = to => `FETCHING` & `FETCHED`. 🙂 
I think `src/config/constants/types.ts` is a good place for such enum. Most loading stuff is in `state` but I believe there were couple of places outside of state where we use it. Need to check.
In any case if during the move we find out that its only in `state` then we can move this enum to `state/types`. But I think its not necessary, even if its just in `state` we can import from `constants/types`, not a big deal 🤷‍♂️

**Comment by bariOmymen** [comment]
Thank you for clearing that up

**Comment by bariOmymen** [comment]
hey @Chef-Cheems. I'm having an issue with eslint and prettier when I try to commit my changes. 
this is the error
yarn run v1.22.17
$ prettier --check '**/*.{js,jsx,ts,tsx}'
Checking formatting...
[error] No files matching the pattern were found: "'**/*.{js,jsx,ts,tsx}'".
All matched files use Prettier code style!
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
husky - pre-commit hook exited with code 2 (error)
do you know how to fix it?

**Comment by bariOmymen** [comment]
> hey @Chef-Cheems. I'm having an issue with eslint and prettier when I try to commit my changes. this is the error yarn run v1.22.17 $ prettier --check '**/*.{js,jsx,ts,tsx}' Checking formatting... [error] No files matching the pattern were found: "'**/*.{js,jsx,ts,tsx}'". All matched files use Prettier code style! error Command failed with exit code 2. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. husky - pre-commit hook exited with code 2 (error) do you know how to fix it?

i fixed this issue, i didn't give myself time to think

**Comment by Chef-Cheems** [comment]
> hey @Chef-Cheems. I'm having an issue with eslint and prettier when I try to commit my changes.

Are you on windows? We have this PR (https://github.com/pancakeswap/pancake-frontend/pull/2544) hanging around but I don't have Windows machine to test at the moment. 😬 
Maybe try to see if changes in that PR solve your problem.
If you're on windows of course, if you're on Mac/Linux then idk what's up with that 🤔 

> i fixed this issue, i didn't give myself time to think

What was the fix?

**Comment by bariOmymen** [comment]
i deleted single quotes in the package.json file in the yarn commands that i needed

so from '**/*.{js,jsx,ts,tsx}' to **/*.{js,jsx,ts,tsx}
