### ISSUE TITLE
execution reverted: TransferHelper: TRANSFER_FROM_FAILED

### ISSUE THREAD

**Issue by yegor256** [pancakeswap/pancake-frontend#2616]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Farms

### Current Behavior

Trying to swap SQUID to BNB

### Expected Behavior

Successful swap

### Steps To Reproduce

I just click "swap", select the amount, and get the error. While I see other successful transactions in the pool with the same token: https://pancakeswap.finance/info/token/0x87230146e138d3f296a9a77e497a2a83012e9bc5

### Environment

```markdown
- Device: 
- OS: 
- Browser:
- Wallet:
```

**Comment by memoyil** [comment]
Have you tried to increase the slippage?

**Comment by tao2581** [comment]
It's a scam token
