### ISSUE TITLE
[BUG] Redux getDefaultMiddleware function is depreciated

### ISSUE THREAD

**Issue by ClemFournier** [pancakeswap/pancake-frontend#2645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

middleware: [...getDefaultMiddleware({ thunk: true }), save({ states: PERSISTED_KEYS })],

### Expected Behavior

middleware: (getDefaultMiddleware) => [...getDefaultMiddleware({ thunk: true }), save({ states: PERSISTED_KEYS })],

### Steps To Reproduce

Go to state/index.ts (50)

### Environment

```markdown
- Device: NZXT H1
- OS: Windows 10
- Browser: Microsoft Edge
- Wallet: Metamask
```

### Anything else?

https://github.com/reduxjs/redux-toolkit/issues/1324

**Comment by bariOmymen** [comment]
@Chef-Cheems may I ask why this issue isn't closed yet, the fix seems to be simple and I'd be glad to help

**Comment by ClemFournier** [comment]
@bariOmymen @Chef-Cheems I'd like to help, I just don't know if I'm able to do a pull request?
