### ISSUE TITLE
[BUG] Token showing up as "unknown" in the analytics page.

### ISSUE THREAD

**Issue by Alferdize** [pancakeswap/pancake-frontend#2647]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Info

### Current Behavior

The token name for my token on the analytics page are displayed as "unknown". Also the price doesn't match.
https://pancakeswap.finance/info/token/0xc36ce2209f1824c47bb9a6c40b43a5326a0f5c0a

### Expected Behavior

Show the correct name of token and right price.

### Steps To Reproduce

Go to https://pancakeswap.finance/info/token/0xc36ce2209f1824c47bb9a6c40b43a5326a0f5c0a

### Environment

```markdown
- Device: For everybody
- OS: For everybody
- Browser: For everybody
- Wallet: For everybody
```

**Comment by julian-molina** [comment]
Same issue with our token too. Any help will be greatly appreciated!

Superalgos $SA contract:

0xfb981ed9a92377ca4d75d924b9ca06df163924fd

Token page:

https://pancakeswap.finance/info/token/0xfb981ed9a92377ca4d75d924b9ca06df163924fd

Our liquidity pools are a few weeks old, and still the token page shows the "unknown" label.

**Comment by savcrypto0** [comment]
same issue for me
https://pancakeswap.finance/info/token/0x235d2ffd66dbdcd94ec711eb1f565c3e69eada48

Please advise, very urgent for me
