### ISSUE TITLE
[BUG] Token page showing price at 0 and name "unknown"

### ISSUE THREAD

**Issue by julian-molina** [pancakeswap/pancake-frontend#2651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Info

### Current Behavior

[Issue 2647](https://github.com/pancakeswap/pancake-frontend/issues/2647) reports a similar issue with another token, but in that case there seems to be zero liquidity in the pool.

# My issue

The [token info page](https://pancakeswap.finance/info/token/0xfb981ed9a92377ca4d75d924b9ca06df163924fd) of the Superalgos $SA token (contract 0xfb981ed9a92377ca4d75d924b9ca06df163924fd) shows the price at zero, and displays "unknown" instead of the name of the token.

![image](https://user-images.githubusercontent.com/13994516/140814037-479452fb-fc45-4896-ba5c-e73772d93999.png)

### Expected Behavior

The name of the token and price should display the correct information.

### Steps To Reproduce

Visit the [token info page](https://pancakeswap.finance/info/token/0xfb981ed9a92377ca4d75d924b9ca06df163924fd).

### Environment

```markdown
Tested in multiple systems / browsers.
```

**Comment by julian-molina** [comment]
@ChefNina I see you solved a similar issue a few weeks ago. Can you maybe help me with my case?

**Comment by Combot80** [comment]
Hello apology for the delay has your issues been resolved yet?

**Comment by julian-molina** [comment]
> 
> 
> Hello apology for the delay has your issues been resolved yet?

No, it hasn't. The issue persists.

**Comment by Combot80** [comment]
Which wallet are you using?

**Comment by Combot80** [comment]
Okay, I'm here to support you

**Comment by Combot80** [comment]
You will need to reauthenticate your wallet to the latest node system but before that you will have to open a support ticket through our support ticket link

**Comment by Combot80** [comment]
Do you know how to do that?

**Comment by julian-molina** [comment]
This has nothing to do with wallets. It's PancakeSwap's website.

@Chef-Chungus @ChefNina would love to hear from you.

BTW, this @Combot80 account seems like a scam.

**Comment by Combot80** [comment]
Okay then those who u mention will come help u

**Comment by savcrypto0** [comment]
any progress on this one?
I also experience the same issue
https://pancakeswap.finance/info/token/0x235d2ffd66dbdcd94ec711eb1f565c3e69eada48

**Comment by julian-molina** [comment]
> any progress on this one? I also experience the same issue https://pancakeswap.finance/info/token/0x235d2ffd66dbdcd94ec711eb1f565c3e69eada48

I haven't heard from anyone yet. Tried multiple channels (Reddit, Telegram, Twitter). Please let me know if you get a hold of anyone and I'll do the same.

**Comment by Luis-Fernando-Molina** [comment]
@pancakeswap can you please check on this issue? We are launching our platform tomorrow (Monday) and this the only unresolved issue we have. Please!

**Comment by julian-molina** [comment]
@memoyil @Chef-Cheems Can you please give us a hand with this? Even a pointer on how to fix the issue would be greatly appreciated.

**Comment by R-K-H** [comment]
This has to do with the Subgraph index on The Graph, not PancakeSwap. So you'd best research there to see if you can contribute to the indexing of the Subgraph so that the data is there in the first place.

**Comment by Luis-Fernando-Molina** [comment]
hey @R-K-H  , can you please elaborate on your comment? What is the Graph?

As far as I know this is PancakeSwap web site, and the site is not showing the token name or logo. How is that not related to PancakeSwap?

![image](https://user-images.githubusercontent.com/9479367/141796864-34b354c0-57a3-48a0-b068-5ade7808063d.png)

**Comment by R-K-H** [comment]
Look at your network tab to see which request is failing to load the data:

<img width="1144" alt="Screen Shot 2021-11-15 at 10 20 06 AM" src="https://user-images.githubusercontent.com/1007667/141807245-9d4c91be-5ee4-4dac-b413-b603feb1b17c.png">


Then look at the error message returned from the API:

<img width="834" alt="Screen Shot 2021-11-15 at 10 20 59 AM" src="https://user-images.githubusercontent.com/1007667/141807425-66359b7e-abcd-43a0-afb0-e03891e1f0f6.png">

This API request is made of the subgraph created via https://thegraph.com/ this is not done via PancakeSwap, as this is another service provider.

To learn a bit more about the system you can check out this post https://pancakeswap.medium.com/pancakeswap-info-relaunch-in-partnership-with-150-000-bounty-winner-streamingfast-f7892559d388 and about The Graph.

**Comment by R-K-H** [comment]
You can read about how to get tokens listed and iconography etc https://docs.pancakeswap.finance/contact-us/business-partnerships as well as submitting a PR to https://github.com/trustwallet/assets the PCS team is not responsible for listing every token and every project on the blockchain so the elements that build a decentralized exchange all culminate across multiple sources and partners.

**Comment by Luis-Fernando-Molina** [comment]
@R-K-H thanks for the clarification! will check it out now.

**Comment by Luis-Fernando-Molina** [comment]
@R-K-H the token name issue was resolved and the logo now we know we need to pay to trust wallet to get them there, and then at pancake swap.  Thanks for your help.

Feedback to Pancake swap guys: Using the logos from Trust Wallet is a bad idea. We have chosen you as our first exchange listing, not trust wallet. Having to pay a third party to get a logo into you is not rational and dilutes the trust we have in you. 

You may close this issue now.
