### ISSUE TITLE
[BUG] Multicall RPC Error (FTM chain)

### ISSUE THREAD

**Issue by ColtraneNadler** [pancakeswap/pancake-frontend#2652]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

Forked pancakeswap for FTM chain, and I get this error frequently. Some of the calls work, some don't.

inpage.js:1 MetaMask - RPC Error: Internal JSON-RPC error. 
{code: -32603, message: 'Internal JSON-RPC error.', data: {…}}
code: -32603
data: {code: -32000, message: 'execution reverted'}
message: "Internal JSON-RPC error."
[[Prototype]]: Object

It causes the token balances to disappear randomly, and other strange occurences. 

### Expected Behavior

For the multicalls to go through and not have this error.

### Steps To Reproduce

Start the project, and interact with the frontend.

### Environment

```markdown
- Device:  macbookpro/linux/windows
- OS: macos
- Browser: chrome
- Wallet: metamask
```

### Anything else?

Any ideas for debugging? Or has anyone come across this issue?

**Comment by Combot80** [comment]
Hello apology for the delay has your issues been resolved yet?
