### ISSUE TITLE
[Feature Request] Truncate Large Number

### ISSUE THREAD

**Issue by matbrgz** [pancakeswap/pancake-frontend#2663]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem you are facing?

When a token has huge supply, sometimes the frontend could break because the number is too large to display.

### Describe the solution you'd like

Truncate the number instead of exiting 1.000.000.000.000 show 1T.

More examples: 

9.900.000.000 show 9.9B
150,000,000 show 1.5M

### How does this feature benefit PancakeSwap users and CAKE holders?

Do not broken the frontend

**Comment by chef-jojo** [comment]
I agree we should truncate the large number.
Can you point out where we missed 🙂

**Comment by matbrgz** [comment]
I never see a broken frontend yet, but some tokens are creating extreme large supply may sometime it will happen.

**Comment by matbrgz** [comment]
Could I start an implementation of this?

**Comment by chef-jojo** [comment]
> Could I start an implementation of this?

Yup, we welcome any contributions!

**Comment by matbrgz** [comment]
@chef-jojo could you please reopen it?
