### ISSUE TITLE
[BUG] Failed to compile: 'pollingInterval' does not exist in type 'WalletConnectConnectorArguments'

### ISSUE THREAD

**Issue by alexndr-n** [pancakeswap/pancake-frontend#2665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

Hey! When trying to build this typescript error arises. I've checked the files and effectively the parameter types are entirely wrong inside of this file. This is the complete error.

```
TypeScript error in /home/alejandro/Desktop/pancake-frontend/src/utils/web3React.ts(17,3):
Argument of type '{ rpc: { [x: number]: string; }; qrcode: true; pollingInterval: number; }' is not assignable to parameter of type 'WalletConnectConnectorArguments'.
  Object literal may only specify known properties, and 'pollingInterval' does not exist in type 'WalletConnectConnectorArguments'.  TS2345
```

### Expected Behavior

It builds.

### Steps To Reproduce

Clone the repository.
Install packages.
Build.

### Environment

```markdown
- Device: Asus notebook
- OS: Ubuntu 21.4
- Browser: Terminal
- Wallet: Not there yet
```

**Comment by alexndr-n** [comment]
Wait, let me try master branch.

**Comment by gunrosen** [comment]
@alexndr-n  I got the same issue. Is that issue cause of @web3-react/walletconnect-connector ?

**Comment by wpzt116199** [comment]
I have the same problem

**Comment by ELHARAKA** [comment]
is this issue solved?

**Comment by chefilip** [comment]
Hmm. It's hard to debug because the issue doesn't occur on my machine.

My Environment
- Device: Macbook

**Comment by ELHARAKA** [comment]
I had to remove everything and start over with yarn instead of npm

`yarn install`
`yarn build`
`yarn run start`

Problem solved.
