### ISSUE TITLE
Compile issues on master branch

### ISSUE THREAD

**Issue by danp963** [pancakeswap/pancake-frontend#2671]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

Clone pancake-frontend repo

Yarn
Yarn start

Multiple ES Lint issues.
If ES Lint is disabled there
![Screenshot 2021-11-13 120738](https://user-images.githubusercontent.com/94201729/141643243-348942a7-8dab-45d1-a90e-774fba61cc1b.png)
 are multiple typescript issues

### Expected Behavior

Frontend to compile and run in browser

### Steps To Reproduce

1. git clone pancake-frontend
2. yarn
3. yarn start

### Environment

```markdown
- Device: Custom Windows
- OS: Windows 10 10.0.19042
- Browser: Google Chrome 95.0.4638.69
- Wallet: Metamask
```

**Comment by memoyil** [comment]
You should do `yarn install` before `yarn start`

**Comment by danp963** [comment]
I did do yarn install before yarn start, still does not work on Windows.

It does however work fine on my mac.

**Comment by chef-jojo** [comment]
There's a PR #2544 for this. Could you pull the latest code and try again?

**Comment by danp963** [comment]
Thanks, PR #2544 has fixed the issue
