### ISSUE TITLE
[BUG] IFO PORTO Claim button is missing

### ISSUE THREAD

**Issue by bossbossk20** [pancakeswap/pancake-frontend#2694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

IFO

### Current Behavior

Unable to claim IFO PORTOR in basic sale because claim button is missing
<img width="361" alt="Screen Shot 2564-11-17 at 09 53 24" src="https://user-images.githubusercontent.com/8810501/142131733-09220c56-774d-448b-a718-3596916bc94a.png">

### Expected Behavior

claim button should show in basic sale

### Steps To Reproduce

Go to IFO page and look at basic sale

### Environment

```markdown
- Device: Macbook Air M1
- OS: Monetery 12.0.1
- Browser: Chrome
- Wallet: Metamask
```

**Comment by ChefNina** [comment]
You can't see claim button because you've already claimed.
Before claiming, it is shown as the below. Please check your TX to confirm it.
![image](https://user-images.githubusercontent.com/82930772/142133284-b127f526-6f2e-4723-970b-4d4ca2b2d618.png)
