### ISSUE TITLE
Connect the wallet using WalletConnect  ,click swap to confirm that the transaction should pop up the wallet list ,However  he opens a link

### ISSUE THREAD

**Issue by wds1181977** [pancakeswap/pancake-frontend#2734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Farms

### Current Behavior

Swap module signature transaction，Connect the wallet using WalletConnect and click the confirm swap page. Instead of starting the wallet, you jump to https://gnosis-safe.io , IOS is like this. Android is fine

### Expected Behavior

Jump to the wallet app,

### Steps To Reproduce

Use iPhone x chrome to open pancake, select exchange and walletConnect to connect the wallet. After the connection is successful, click swap to confirm that the transaction should pop up the wallet list. However, he opens a link

### Environment

```markdown
- Device: Iphone X
- OS: IOS
- Browser:Chrome mobile
- Wallet:
```

**Comment by wds1181977** [comment]
> 无法重现您的问题。我遵循的步骤：
> 
> 1. 通过钱包连接连接网站
> 2. 扫描二维码
> 3. 连接的
> 4. 去交易 -> 交换
> 5. 交换
> 6. 点击交换然后确认交换
> 7. 用于扫描二维码的设备上弹出交易批准请求。

Please use the iPhone mobile browser to open, not the computer browser

**Comment by memoyil** [comment]
Ok, I tested that too, still couldn't reproduce. Device correctly shows transaction approval screen.
