### ISSUE TITLE
Remove footer and logo

### ISSUE THREAD

**Issue by hope-s** [pancakeswap/pancake-frontend#2736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem you are facing?

I want to remove the footer and logo

### Describe the solution you'd like

In which component can I delete it?

### How does this feature benefit PancakeSwap users and CAKE holders?

Feature development

**Comment by Chef-Cheems** [comment]
Issue is not related to PancakeSwap itself or its functionality/cosmetic
