### ISSUE TITLE
Suggestion for translation word Pool to Russian

### ISSUE THREAD

**Issue by Serhioromano** [pancakeswap/pancake-frontend#2745]
@ChefNina 

Привет. Я предлагаю перевести везде слово Pool не как пул а как "фонд".

За

- Слово фонд будет понятно разу всем. Для новичков это понизит порог вхождения в мир терминологии крипто. Сделает очевидным 
- В сочетании с переводом слова Стеки как вложить, то Вложить в фонд вообще очень понятное выражение. Станет вообще очевидно что такое фонд.
- Понятная терминология может привлечь новых пользователей, которые смогут быстро купить и вложить пирожки в фонд, не отчаявшись где-то по середине и не бросив все это.

Против

- Из за неграмотности большинство проектов переводят Пул как Пул. И для тех кто уже поднаторел в крипто, и прохавал что такое пулы, возможно слово фонд будет не сразу понятно что это и есть пул. 
 
   По этому в меню предлагаю перевод с аннотацией

   Фонды (Pools)

   А везде в остальных местах уже просто фонд.

Я думаю что терминология на русском только формируется, и делая правильный перевод, можно создать нормальный набор терминов, который будет понятен всем, даже новичкам. Если же будет использовать термины стейкинг, пул, то для многих это потребует объяснения что это за понятия и как это работает.

**Comment by ChefNina** [comment]
Привет!
Stake как "вложить" это хорошо, но вот pool как фонд это так себе. По такой логике и на английском надо переделывать Pool -> Fund. Давайте не будем менять пул на фонд, но "вложить" и "изъять" думаю нормально, понятней действительно 🙂

**Comment by Serhioromano** [comment]
Хорошо.
