### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by farhanali2325** [pancakeswap/pancake-frontend#2770]
Failed to compile.

src/components/ExpandableSectionButton/ExpandableSectionButton.tsx
  Line 36:3:  defaultProp "expanded" has no corresponding propTypes declaration  react/default-props-match-prop-types

src/components/Modal/ModalInput.tsx
  Line 13:3:  'placeholder' PropType is defined but prop is never used  react/no-unused-prop-types

src/components/PageSection/CurvedDivider.tsx
  Line 7:3:  'svgFill' PropType is defined but prop is never used  react/no-unused-prop-types

src/components/Toast/DescriptionWithTx.tsx
  Line 9:3:  'description' PropType is defined but prop is never used  react/no-unused-prop-types

src/views/AddLiquidity/index.tsx
  Line 251:9:  JSX props should not use functions  react/jsx-no-bind

src/views/FarmAuction/components/AuctionDetailsCard/AuctionSchedule.tsx
  Line 18:3:  'showForClosedAuction' PropType is defined but prop is never used  react/no-unused-prop-types

src/views/Farms/components/FarmTable/Row.tsx
  Line 118:34:  Must use destructuring props assignment  react/destructuring-assignment
  Line 128:63:  Must use destructuring props assignment  react/destructuring-assignment
  Line 145:27:  Must use destructuring props assignment  react/destructuring-assignment
  Line 152:29:  Must use destructuring props assignment  react/destructuring-assignment
  Line 157:26:  Must use destructuring props assignment  react/destructuring-assignment

src/views/Home/components/CompositeImage.tsx
  Line 74:3:  'animate' PropType is defined but prop is never used  react/no-unused-prop-types

src/views/PancakeSquad/components/Buttons/EndEvent.tsx
  Line 11:3:  'userStatus' PropType is defined but prop is never used  react/no-unused-prop-types

src/views/PancakeSquad/components/Buttons/Mint.tsx
  Line 18:3:  'numberTokensOfUser' PropType is defined but prop is never used  react/no-unused-prop-types

src/views/PancakeSquad/components/Header/SaleProgress.tsx
  Line 9:3:  'userStatus' PropType is defined but prop is never used  react/no-unused-prop-types

src/views/Pools/components/PoolCard/CardFooter/index.tsx
  Line 13:3:  'totalCakeInVault' PropType is defined but prop is never used  react/no-unused-prop-types

src/views/ProfileCreation/ConfirmProfileCreationModal.tsx
  Line 18:3:  'userName' PropType is defined but prop is never used  react/no-unused-prop-types

src/views/RemoveLiquidity/index.tsx
  Line 378:93:  JSX props should not use functions  react/jsx-no-bind
  Line 447:48:  JSX props should not use functions  react/jsx-no-bind
  Line 447:73:  JSX props should not use functions  react/jsx-no-bind
  Line 640:19:  JSX props should not use functions  react/jsx-no-bind

Search for the keywords to learn more about each error.

**Comment by farhanali2325** [comment]
I have done the following steps multiple times. But still getting the same error. 

- Remove node_modules
- Remove package-lock.json
- Remove yarn.lock

Then I've run the following commands:

- yarn install
- yarn start

But the issue is still the same. Please guide me

**Comment by ungaro** [comment]
this problem comes back after a while, what is the root cause, did you solve it? @farhanali2325

**Comment by ExpLife0011** [comment]
> I have done the following steps multiple times. But still getting the same error.
> 
> * Remove node_modules
> * Remove package-lock.json
> * Remove yarn.lock
> 
> Then I've run the following commands:
> 
> * yarn install
> * yarn start
> 
> Versions are:
> 
> * node -v  => v14.17.6
> * npm -v  => 6.14.15
> * yarn -v   => 1.22.15
> 
> But the issue is still the same. Please guide me

update your node to latest version will be solve it.
