### ISSUE TITLE
[BUG] Firefox / TOR extreme memory leaks

### ISSUE THREAD

**Issue by keybreak** [pancakeswap/pancake-frontend#2783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Prediction

### Current Behavior

Extreme memory leaks on clean Firefox / TOR anywhere from 1.2 to 20 Gb of RAM, renders whole thing completely unusable, can happen anywhere from 10 minutes to 24 hours of use.

After 5-10 minutes Predictions page becomes very hard to use, constantly just hangs browser.

Also happens for swap page as well.

### Expected Behavior

I want such service to work like a clock.

### Steps To Reproduce

1. Open Firefox / TOR with just Metamask and Predictions tab opened
2. Wait. You can just leave it for 10 minutes - 24 hours.

### Environment

```markdown
- Device: Any
- OS: Arch Linux
- Browser:Firefox / TOR
- Wallet: Metamask
```

### Anything else?

Please fix it, it drives me insane :upside_down_face: 
Perhaps it could be caused by constant `console.log`s?

**Comment by chef-jojo** [comment]
I can confirm it happens on production, but can't reproduce on local development mode..
There are network request stuck on pending status and response 413
It needs sometime to investigate what's going on especially in https://github.com/pancakeswap/pancake-frontend/blob/develop/src/views/Predictions/hooks/usePollPredictions.ts

**Comment by chef-jojo** [comment]
I can't reproduce in production now. Maybe solved by recently block number and multicall changes
Does it still happen on your side? @keybreak

**Comment by keybreak** [comment]
@chef-jojo 
Yesterday when left for the night i've found PancakeSwap tab crashed as always, so i doubt it, but let me check again....

**Comment by keybreak** [comment]
No, i was still able to catch it ~1.4 - 1.7 Gb leak and usual hang "This page is slowing Firefox browser"

**Comment by keybreak** [comment]
Shut up robot :robot: ! :laughing:

**Comment by immibis** [comment]
Not sure if it's the same bug but I'm seeing the whole browser slow down when on the Pools page. My hypothesis was that it could be because the page makes tons and tons of eth_call RPC requests to fetch data.

**Comment by memoyil** [comment]
> Not sure if it's the same bug but I'm seeing the whole browser slow down when on the Pools page. My hypothesis was that it could be because the page makes tons and tons of eth_call RPC requests to fetch data - each one in a separate HTTP request.

Can you test this fix? You can find deployment preview link there. But please DON'T connect your account for your own safety.

https://github.com/pancakeswap/pancake-frontend/pull/2851

**Comment by keybreak** [comment]
Shuuut up robot!!!11 :rofl:

**Comment by immibis** [comment]
Issue still exists in production.

**Comment by keybreak** [comment]
I still think it's probably related to front-end DOM, coz if you leave it running for many hours and then try to scroll with arrows it will lag like s**t, if you reload page and scrollback will be reset to no more recent than 3 cards - lags go away....That probably is connected

**Comment by memoyil** [comment]
@immibis @keybreak You can test this version https://github.com/pancakeswap/pancake-frontend/pull/3178, but please don't connect your account or make transactions just in case.

**Comment by keybreak** [comment]
@memoyil 
Sorry i can't test outside of prod occasionally (busy 24/7)
