### ISSUE TITLE
how can i use 97 env 

### ISSUE THREAD

**Issue by jiemodetang** [pancakeswap/pancake-frontend#2788]
now i connet wallet ，He is automatically connected to the main network environment

**Comment by jiemodetang** [comment]
Unhandled Rejection (Error): call revert exception (method="totalSupply()", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.5.0)

**Comment by LukeSamkharadze** [comment]
You can't use testnet wallet on pancakeswap, it will automatically redirect the network to mainnet
