### ISSUE TITLE
[BUG] Current emissions is 14.5/block at home page

### ISSUE THREAD

**Issue by dinhnhatbang** [pancakeswap/pancake-frontend#2828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

Current emissions is 14.5/block

![image](https://user-images.githubusercontent.com/17607247/144710190-4e80b27d-6ea2-41be-8d93-7147a5ba6690.png)

### Expected Behavior

But I see in https://docs.pancakeswap.finance/tokenomics/cake/cake-tokenomics currently is 14.25/block

### Steps To Reproduce

1. Goto https://pancakeswap.finance/
2. Scroll down to "CAKE makes our world go round." section.

### Environment

```markdown
- Device: Macbook
- OS: macos
- Browser: chrome
- Wallet:
```

**Comment by Chef-Cheems** [comment]
Fixed in https://github.com/pancakeswap/pancake-frontend/pull/2829
Will deploy soon.
Thanks!
