### ISSUE TITLE
[Feature Request] How to make pancakeswap frontend connect to metamask using iotex chain 

### ISSUE THREAD

**Issue by IsoftTech** [pancakeswap/pancake-frontend#2832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem you are facing?

YES

### Describe the solution you'd like

I'd cloned the pancakeswap frontend but, I am findind it hard to use other chain to connect to metamask aside from the existen ones there. I was looking to connect using the iotex chain.
Can tis be possible at all?

### How does this feature benefit PancakeSwap users and CAKE holders?

It will add to the numbers of tokens already on pancakeswap platform and the cake holders will be able to change iotex to cake if added.
However, I'd like to know hiow to add other chains on the frontend dapp myself.

### Anything else?

NO

**Comment by Chef-Cheems** [comment]
> It will add to the numbers of tokens already on pancakeswap platform and the cake holders will be able to change iotex to cake if added.

No it will not. PancakeSwap exists only on BSC. 

If you wanna fork it on Iotex you should ask this in iotex repo/forums, devs here have no idea about iotex.

Closing as its not relevant to PancakeSwap development
