### ISSUE TITLE
Can't remove liquidity

### ISSUE THREAD

**Issue by besartcana** [pancakeswap/pancake-frontend#2834]
Hello, I have some problem with liquidity removing.

Pair: 0xc4d085edb661ea503a5936c7efa26f62efda2c9e

Contract: 0x67d36b06c601393436f71f503460b0d64526a7cf

Contract is renounced to dead wallet, have no access to change anything on it.

Trading and swaping is disabled on contract and cant enable them.

Have tryed to approving spender address Pancakerouter v2, when requesting from Router v2 to remove liqudity allway falling back with error. (Pancake: TRANSFER_FAILED).

Token0 amount: 19999900000000000000000

Token1 amount: 1199990000000000000

LQ amount: 154919333848296674407

Wenn i try from webinterface (pancakeswap.finnance/liquidity) can enable transaction, wenn i click Remove its not reacting. Have trayed all options to remove bnb, wbnb, 1%, 10%,100% allways same no reaction.

Maybe someone has same problem and can tell me something more.

Regards

**Comment by ChefNina** [comment]
This is wrong place to ask such question. Please check our doc and ask the further question in our community.
doc: https://docs.pancakeswap.finance/help/troubleshooting
community: https://t.me/PancakeSwap
