### ISSUE TITLE
Button for switching currency pair not working properly

### ISSUE THREAD

**Issue by khDev01** [pancakeswap/pancake-frontend#2854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

Pressing the button to switch the currency pair (i.e the button that changes bnb/busd to busd/bnb) around does not work properly. This only works when specifically pressing the arrow within the button and not the edges of the button. 

### Expected Behavior

Pressing the button to swap currencies around should swap the currencies.

### Steps To Reproduce

1. Open any browser
2. Go to [https://pancakeswap.finance/swap](https://pancakeswap.finance/swap)
3. Click not in the center of the button which switches the currency pair around. (clicking out of the hitbox for the arrow)

### Environment

```markdown
- Device: N/A 
- OS: N/A
- Browser: Any desktop browser
- Wallet: N/A
```

**Comment by chef-jojo** [comment]
Hey! Thanks for raising this. I had a branch to fix this, but I was getting too busy that I forgot it 😅
