### ISSUE TITLE
Can't connect MetaMask wallet in Microsoft Edge

### ISSUE THREAD

**Issue by JUSTISBEN** [pancakeswap/pancake-frontend#2923]
If use Microsoft Edge will can't connect the MetaMask wallet, please check, thks.

**Comment by Abehuerta** [comment]
Make sure to follow the repot issue template when reporting a new issue:

https://github.com/pancakeswap/pancake-frontend/blob/2bdb8e82fd7fa7ab6f26558383872653941a1726/CONTRIBUTING.md#issue-reports

Connecting to Edge worked fine for me both on production and development. Make sure you have the right extension installed: https://microsoftedge.microsoft.com/addons/detail/metamask/ejbalbakoplchlghecdalmeeeajnimhm?hl=en-US 
And make sure you have the Binance Smart Chain Network added to your Metamask Wallet: https://dailydefi.org/articles/add-bsc-mainnet-to-metamask/

If you are still having issues ask other pancake swap users on reddit, telegram, or discord:  https://docs.pancakeswap.finance/contact-us/telegram
