### ISSUE TITLE
Errors while trying to implement an 97 environment

### ISSUE THREAD

**Issue by ofirthedev** [pancakeswap/pancake-frontend#2947]
hi , i'm trying to implement a testnet , changed everything to my router address,factory address,init hash code.
also changed .env to 97 and URLS to 8545 , but still getting many errors such as:
![image](https://user-images.githubusercontent.com/40031914/147402566-4379ae0f-4fd7-4082-aa14-ed2b2a35848a.png)
![image](https://user-images.githubusercontent.com/40031914/147402573-bb6e3e6a-ebf2-4314-8d87-385595df55fd.png)
![image](https://user-images.githubusercontent.com/40031914/147402576-8b32e8d1-6ac6-4863-82e3-57f827aa7032.png)
![image](https://user-images.githubusercontent.com/40031914/147402581-b344b45a-f7a3-476f-914e-852b2fc6299b.png)

What am i missing? (I did manage to fork other repositories without any problems, but also without Farms,pools & etc..)

**Comment by hoa-nguyenlexuan** [comment]
I meet the same problem and I try to delete node_module and yarn it again, then yarn start and It work for me

**Comment by crackaf** [comment]
I got the same error. Mostly this + CORS error in console. I didn't change the 56 in env files as this is used by the pancake contract. I added another environment variable =97 and used that for my contract. And while using I provided my own JSONRPC provider which is on testnet. That worked for me without errors.

**Comment by crackaf** [comment]
Related #2788

**Comment by sayedex** [comment]
Hey can you guide me how to connet pools?

**Comment by crackaf** [comment]
I haven't reached that part yet. I'm working on pancakeswap UI for some personal project. For the time being, I added my own contracts which are deployed on 97. The contracts are working and I'll be connecting them to the redux.
For pools, I don't think that's any difference. Just write the smart contract and call it from your UI. Mostly the working of the pool depends on your functions of contract. Like how would you like to save the data and get the data.

**Comment by silahomelos** [comment]
> I haven't reached that part yet. I'm working on pancakeswap UI for some personal project. For the time being, I added my own contracts which are deployed on 97. The contracts are working and I'll be connecting them to the redux. For pools, I don't think that's any difference. Just write the smart contract and call it from your UI. Mostly the working of the pool depends on your functions of contract. Like how would you like to save the data and get the data.

I'm having the same problem as above and I couldn't quite understand the solution you said. Could you please explain the solution in more detail.

**Comment by chef-jojo** [comment]
wip slowly

**Comment by chef-jojo** [comment]
testnet for swap and liquidity now available at https://testnet.pancake.run/
