### ISSUE TITLE
[BUG] `MAX` button returns 0 instead of real max value, if source coin balance is low.

### ISSUE THREAD

**Issue by a1eaiactaest** [pancakeswap/pancake-frontend#2974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

In https://pancakeswap.finance/swap, when pressing `MAX` button and having low source coin balance (e.g. `0.00289577 BNB`) it doesn't return proper max value but set's it to `0`. This may be caused by rounding floats to second or third decimal point.

### Expected Behavior

`MAX` button should return actual max value of coin in my wallet.

### Steps To Reproduce

1. Make sure you are using Metamask, don't know if it's relevant tho.
2. Go to https://pancakeswap.finance/swap
3. In my case the source coin was `BNB` and out coin was `CAKE`, those are the defaults. I've tried changing the out coin, same bug happens.
4. Have relatively low balance. In my case `0.00289577 BNB`.
5. Slippage Tolerance doesn't matter.
6. Press `MAX` button.
7. Value of source coin is now `0`.

### Environment

```markdown
- Device: MacBook Air M1 
- OS: Monterey 
- Browser: Chrome
- Wallet: Metamask
```

### Anything else?

![2022-01-02 23-18-40](https://user-images.githubusercontent.com/55894077/147890895-8af34f50-2502-4b34-beeb-ffb50d462f6a.gif)

**Comment by chef-jojo** [comment]
It is a feature preventing user send so much BNB so they end up with <.01

**Comment by a1eaiactaest** [comment]
oh ok. this makes sense until <.01 is not enough to pay the fee.
