### ISSUE TITLE
[BUG] balance gets stuck on loading when starting a liquidity pool

### ISSUE THREAD

**Issue by Wemmons831** [pancakeswap/pancake-frontend#3024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Syrup Pools

### Current Behavior

After trying to create a new liquidity pool the with custom token the balance suddenly changes to loading after inputting second value and it seems to be indefinitely stuck
![image](https://user-images.githubusercontent.com/69495081/149042188-2e5c8dc0-11ee-437c-adc6-ccff8c017a04.png)

### Expected Behavior

I expected that it would allow me to create a liquidity pool

### Steps To Reproduce

WEM coin
0x42Fb6019F34536847d3045eE63D1C81E8c25c6f1

### Environment

```markdown
- Device: custom gaming pc
- OS: Windows 11 Home Insider Preview 22526.1000
- Browser: Opera gx
- Wallet: Metamask extension
```

### Anything else?

does it have anything to do with the approve function because this contract does not have one
![image](https://user-images.githubusercontent.com/69495081/149042617-6a5aa20a-90af-4e0e-a22b-4114fc78340c.png)

**Comment by chef-jojo** [comment]
the contract does not have `allowance` function

**Comment by Wemmons831** [comment]
after adding allowance I get this when I try
![image_2022-01-12_200219](https://user-images.githubusercontent.com/69495081/149247219-1fd3be52-83d1-4b53-9509-ac676cc964bb.png)

**Comment by BitOfUniverse** [comment]
@Wemmons831 make sure your contract fully implements ERC20 interface, you can use https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol as base for you contract to be sure that your contract works with PCS pools.

**Comment by Chef-Cheems** [comment]
As others mentioned token needs to be a valid ERC20 token.
Closing this for now but feel free to reopen. Please also verify your contract on BSCScan, otherwise it is hard to debug anything to be honest.
