### ISSUE TITLE
pid: 0, points to CAKE Token Contract

### ISSUE THREAD

**Issue by jamel-86** [pancakeswap/pancake-frontend#3029]
The first farm 0 is actually not  a LP pair contract, it points to Cake Token contract, how can I create this pid 0 with the factory contract ?

**Comment by shopglobal** [comment]
PID 0 is a staking pool for CAKE(create this pool at the masterchef). So the meaning is to reward single stakers for staking CAKE with SYRUP issued through Masterchef which then gets tracked back on frontend. From there users can harvest SYRUP for CAKE and that process burns the SYRUP and mints new CAKE. Hope this helps
