### ISSUE TITLE
Wallet connect connection

### ISSUE THREAD

**Issue by RabbitDoge** [pancakeswap/pancake-frontend#318]
A lot of users complain that wallet connect doesn't work

**Comment by adaamz** [comment]
Is there any solution? How to use pancakeswap with Trust Wallet or any other wallet?

**Comment by Johann-S** [comment]
Should fix this : https://github.com/pancakeswap/pancake-frontend/pull/346

**Comment by RabbitDoge** [comment]
Indeed, #346  will fix this. We plan to release this change early next week.

**Comment by adaamz** [comment]
It works!
Minor bug is that there is no possibility to close session to WalletConnect so you need to use private tab in browser each time or remove cookies for wallet connect somehow.

**Comment by RabbitDoge** [comment]
Fixed in #528

**Comment by RabbitDoge** [comment]
An update will be released tomorrow to fix some minor bugs as well
