### ISSUE TITLE
APY vs APR

### ISSUE THREAD

**Issue by jonasman** [pancakeswap/pancake-frontend#320]
Pankake Syrup pooling used the word APY everywhere but technically it is APR as we can read here: 
https://www.investopedia.com/personal-finance/apr-apy-bank-hopes-cant-tell-difference/

> APR does not take into account the compounding of interest within a specific year. It is calculated by multiplying the periodic interest rate by the number of periods in a year in which the periodic rate is applied. It does not indicate how many times the rate is applied to the balance. 

> Unlike APR, APY does take into account the frequency with which the interest is applied—the effects of intra-year compounding.

I can easily change the code to replace APY in Syrup pools with APR if needed

**Comment by Chef-Chungus** [comment]
resolved with https://github.com/pancakeswap/pancake-frontend/pull/347
