### ISSUE TITLE
Why can't the K-line diagram be loaded

### ISSUE THREAD

**Issue by wpzt116199** [pancakeswap/pancake-frontend#3204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Trade

### Current Behavior

Why can't the K-line diagram be loaded

### Expected Behavior

Why can't the K-line diagram be loaded

### Steps To Reproduce

Why can't the K-line diagram be loaded

### Environment

```markdown
- Device:
- OS:
- Browser:
- Wallet:
```

### Anything else?

Why can't the K-line diagram be loaded

**Comment by wpzt116199** [comment]
![image](https://user-images.githubusercontent.com/38759910/153154661-fde79f84-3152-4068-8d26-9b1837b1d9f1.png)

**Comment by Chef-Cheems** [comment]
Hi!
Please open a new issue with more details, currently its unclear what kind of problem you have.
As for the screenshot - it seems that request to info site endpoint fails (public access is throttled for it to prevent abuse, please use https://pancakeswap.finance/info to see analytical data about your LP and tokens)
