### ISSUE TITLE
From origin has been blocked by CORS policy NODE Pancakeswap

### ISSUE THREAD

**Issue by Keecointoken** [pancakeswap/pancake-frontend#3212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

Access to fetch at 'https://nodes.pancakeswap.com/' from origin '' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'https://pancakeswap.finance' that is not equal to the supplied origin. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

### Expected Behavior

Access to fetch at 'https://nodes.pancakeswap.com/' from origin '' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'https://pancakeswap.finance' that is not equal to the supplied origin. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

### Steps To Reproduce

Access to fetch at 'https://nodes.pancakeswap.com/' from origin '' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'https://pancakeswap.finance' that is not equal to the supplied origin. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

### Environment

```markdown
- Device:
- OS:
- Browser:
- Wallet:
```

### Anything else?

Problem connection only europe

**Comment by CooperTheCosmonaut** [comment]
I have also been experiencing this with a site I maintain that uses PKS as its base fork. Any updates from the team on why it has suddenly appeared?

**Comment by Chef-Cheems** [comment]
Hi!
There was a problem with our node on localhost but now it is resolved.
btw, in case it happens again - you can remove `NEXT_PUBLIC_NODE_PRODUCTION` from env file and then public BSC nodes will be used.

**Comment by DexteraInstrumenta** [comment]
This problem is now on live servers !
Please fix it sooner
Thanks

**Comment by chef-jojo** [comment]
Please use RPC endpoint list in https://docs.binance.org/smart-chain/developer/rpc.html

**Comment by DexteraInstrumenta** [comment]
> Please use RPC endpoint list in https://docs.binance.org/smart-chain/developer/rpc.html

https://github.com/pancakeswap/pancake-frontend/issues/3212#issuecomment-1070489587

**Comment by DexteraInstrumenta** [comment]
We have changed "NEXT_PUBLIC_NODE_PRODUCTION" to any of them but not working in both .env files !
We have even removed it from both files (.env.production and .env.development) but not working !

**Comment by DexteraInstrumenta** [comment]
Fixed
Thanks

**Comment by HuzaifaKhanDeveloper** [comment]
mine not working

**Comment by asafheybetli** [comment]
@asfhkmoglu

Contact me on Telegram I will explain you.

HuzaifaKhanDeveloper ***@***.***>, 26 Nis 2022 Sal, 20:06
tarihinde şunu yazdı:
