### ISSUE TITLE
I am using you repo pancake frontend web 

### ISSUE THREAD

**Issue by developer-pk** [pancakeswap/pancake-frontend#3225]
I am not able to get token/coin Image please help

**Comment by Chef-Cheems** [comment]
Hi!
You need to provide more details.
Do you mean you just cloned our repo and you don't see token logos? Or have you modified something?

**Comment by developer-pk** [comment]
Hello Chef,

Thanks for reply,

Yes, I use Your Repo and the token logo

I use this URl Please help


https://pancakeswap.finance/images/tokens/${val.address}.png


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by chef-jojo** [comment]
what address you got error? 
https://pancakeswap.finance/images/tokens/0x0E09FaBB73Bd3Ade0a17ECC321fD13a19e81cE82.png

**Comment by developer-pk** [comment]
All BNB, ETH  Pancake etc all token

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by chef-jojo** [comment]
Please check if your address is checksummed. or post the image url here we can help you verify it. 
bnb/wbnb
https://pancakeswap.finance/images/tokens/0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c.png
eth
https://pancakeswap.finance/images/tokens/0x2170Ed0880ac9A755fd29B2688956BD959F933F8.png
pancake
https://pancakeswap.finance/images/tokens/0x0E09FaBB73Bd3Ade0a17ECC321fD13a19e81cE82.png

The tokens image we hosted on our website mostly used for ourself. 
you can try to use trustwallet one
`https://assets.trustwalletapp.com/blockchains/smartchain/assets/${address}/logo.png`
