### ISSUE TITLE
[BUG] <title>BUG

### ISSUE THREAD

**Issue by tianheng2017** [pancakeswap/pancake-frontend#3257]
Failed to compile.

./src/hooks/useContract.ts:47:8
Type error: Cannot find module 'config/abi/types' or its corresponding type declarations.

  45 |   Multicall,
  46 |   Weth,
> 47 | } from 'config/abi/types'
     |        ^
  48 |
  49 | // Imports below migrated from Exchange useContract.ts
  50 | import { Contract } from '@ethersproject/contracts'
error Command failed with exit code 1.

**Comment by chef-jojo** [comment]
Types are missing on your side. Try `yarn run typechain`

**Comment by tianheng2017** [comment]
> Types are missing on your side. Try `yarn run typechain`

请问下https://nodes.pancakeswap.com 这个服务是仓库哪个仓库？
