### ISSUE TITLE
[BUG] Problems I encountered in packing

### ISSUE THREAD

**Issue by liusirsir** [pancakeswap/pancake-frontend#3346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

Who can help me with the problems I encounter in packing

thanks

./src/hooks/useContract.ts:47:8
Type error: Cannot find module 'config/abi/types' or its corresponding type declarations.

  45 |   Multicall,
  46 |   Weth,
> 47 | } from 'config/abi/types'
     |        ^
  48 | 
  49 | // Imports below migrated from Exchange useContract.ts
  50 | import { Contract } from '@ethersproject/contracts'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Expected Behavior

Normal packaging

### Steps To Reproduce

yarn build

### Environment

```markdown
- Device:windows
- OS:windows 10
- Browser:
- Wallet:
```

**Comment by chef-jojo** [comment]
duplicated #3257
Try `yarn run typechain`

**Comment by liusirsir** [comment]
thanks，

But I got

./src/utils/web3React.ts:21:3
Type error: Argument of type '{ rpc: { [x: number]: string; }; qrcode: true; pollingInterval: number; }' is not assignable to parameter of type 'WalletConnectConnectorArguments'.
  Object literal may only specify known properties, and 'pollingInterval' does not exist in type 'WalletConnectConnectorArguments'.

  19 |   rpc: { [chainId]: rpcUrl },
  20 |   qrcode: true,
> 21 |   pollingInterval: POLLING_INTERVAL,
     |   ^
  22 | })
  23 | 
  24 | const bscConnector = new BscConnector({ supportedChainIds: [chainId] })
error Command failed with exit code 1.

**Comment by chef-jojo** [comment]
please check no changes on yarn.lock, remove node_modules, use yarn to install
