### ISSUE TITLE
[BUG] <Error: EISDIR: illegal operation on a directory, readlink>

### ISSUE THREAD

**Issue by GoldenSharkStudio** [pancakeswap/pancake-frontend#3373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

I'm testing the front end and when I try to build this error always happens.

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
warn  - using beta Middleware (not covered by semver) - https://nextjs.org/docs/messages/beta-middleware
info  - Creating an optimized production build .<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Unable to snapshot resolve dependencies
info  - Creating an optimized production build
Failed to compile.

Error: EISDIR: illegal operation on a directory, readlink 'J:\pancake-frontend\src\pages\404.tsx'

> Build failed because of webpack errors
error Command failed with exit code 1.

### Expected Behavior

Complete the build without the error

### Steps To Reproduce

1. I had download the repo
2. Run the command yarn to install the dependencies
3. Run the command yarn build 
4. Error happened

### Environment

```markdown
- Device: AMD Ryzen 7 3700X 8-Core Processor 3.59 GHz 32 GB DDR4
- OS: Windows 10
- Browser: Google Chrome
- Wallet: 0x8041cd4161Ee022af199Cc909A1d2DF362B069FA
```

**Comment by chef-jojo** [comment]
We have [pipelines](https://github.com/pancakeswap/pancake-frontend/actions) running without any issues. 
The EISDIR: illegal operation on a directory seems like incorrect file system permissions

What nodejs and yarn version you are running?

**Comment by GoldenSharkStudio** [comment]
Hello @chef-jojo , thanks for answering me.

My system has the versions:
Node version: 16.13.1
Yarn version: 1.22.17
NPM: 8.5.2

**Comment by chef-jojo** [comment]
I have no ideas about this error
I found some similar issues here https://github.com/vercel/next.js/issues/27650
I would suggest clone this repo to a new directory and try again

**Comment by stellantilet** [comment]
I have a same problem.

**Comment by imangi** [comment]
I'm having the same problem.

I'm using 
OS;Windows 10,
Node Version : 18.14.2 
Npm Version: 9.5.1
