### ISSUE TITLE
[Feature Request] Full working BSC testnet swap site

### ISSUE THREAD

**Issue by ultra-pool** [pancakeswap/pancake-frontend#3448]
Iv been looking for a BSC testnet pancake swap the 2 of found doesn't have any testnet cake token on them. Is there a official one that has cake testnet tokens so Im able to add my BSC testnet Token to the swap site for testing. I would like to fully test my token before pushing it to mainnet.

Thank you.

**Comment by chef-jojo** [comment]
testnet for swap and liquidity now available at https://testnet.pancake.run/
