### ISSUE TITLE
[BUG] Pancake-frontend issuing CORS header error from nodes.pancakeswap.com

### ISSUE THREAD

**Issue by bcheeves** [pancakeswap/pancake-frontend#3453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Trade

### Current Behavior

We forked the pancakeswap code and customized the frontend to only show trading for our own swap.

Now the user is unable to connect the wallet in metamask.

We haven't changed anything on this server for over 60 days, since deployed, and it stopped working at around 5am PST Mar 9th 2022.

In the browser console I'm seeing this error:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://nodes.pancakeswap.com/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 204.

I tried adding a custom header field to include this header and a value, but it's not working

### Expected Behavior

The user should be able to connect their wallet

### Steps To Reproduce

1. Fork pancakeswap code
2. Customize ui-kit and public source code pages for a custom frontend
3. Deploy on a custom VPS server using yarn
4. Install modules using yarn, yarn install
5. Build (yarn build)
6. Yarn start
7. Connect to web-ui
8. Error presents itself in the console 

### Environment

```markdown
- Device: MacBook Pro
- OS: Mac OS Catalina 10.15.17
- Browser: Chrome 99.0.4844.51, Firefox 97.0.2
- Wallet: Metamask Browser Extension, issue also presents itself in Safepal Dapp and Trustwallet dapp
```

**Comment by chef-jojo** [comment]
Please use RPC endpoint list in https://docs.binance.org/smart-chain/developer/rpc.html
