### ISSUE TITLE
Add some machanism to avoid rugpulls for keep this platfrom longterm

### ISSUE THREAD

**Issue by suneth2** [pancakeswap/pancake-frontend#3473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem you are facing?

PancakeSwap turn a blind eye and let these rugs happen. Surely they can implement some sort of measure to make it more difficult for scammers, like not allowing liquidity to be withdrawn for at least a few hours / days, or not allowing devs to sell > 50% of tokens at once or any other function, becoz 99% are facing o rugpulls on pancacke swap, in log term this will be a end of he site and cacke value.

### Describe the solution you'd like

PancakeSwap turn a blind eye and let these rugs happen. Surely they can implement some sort of measure to make it more difficult for scammers, like not allowing liquidity to be withdrawn for at least a few hours / days, or not allowing devs to sell > 50% of tokens at once or any other function, becoz 99% are facing o rugpulls on pancacke swap, in log term this will be a end of he site and cacke value.

### How does this feature benefit PancakeSwap users and CAKE holders?

PancakeSwap turn a blind eye and let these rugs happen. Surely they can implement some sort of measure to make it more difficult for scammers, like not allowing liquidity to be withdrawn for at least a few hours / days, or not allowing devs to sell > 50% of tokens at once or any other function, becoz 99% are facing o rugpulls on pancacke swap, in log term this will be a end of he site and cacke value.

### Anything else?

PancakeSwap turn a blind eye and let these rugs happen. Surely they can implement some sort of measure to make it more difficult for scammers, like not allowing liquidity to be withdrawn for at least a few hours / days, or not allowing devs to sell > 50% of tokens at once or any other function, becoz 99% are facing o rugpulls on pancacke swap, in log term this will be a end of he site and cacke value.

**Comment by suneth2** [comment]
Lots of people suffering with rugfulls including myself, It's never ending becoz token developers use various marketing tactics to attract new users daily (1000 of), so this need some solid mechanism on your platform to avoid scamming peoples hard earned money. i guess your team aware of these daytime robberies please do something to avoid those robbers.

**Comment by Ratana09** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Is your feature request related to a problem you are facing?
> PancakeSwap turn a blind eye and let these rugs happen. Surely they can implement some sort of measure to make it more difficult for scammers, like not allowing liquidity to be withdrawn for at least a few hours / days, or not allowing devs to sell > 50% of tokens at once or any other function, becoz 99% are facing o rugpulls on pancacke swap, in log term this will be a end of he site and cacke value.
> 
> ### Describe the solution you'd like
> PancakeSwap turn a blind eye and let these rugs happen. Surely they can implement some sort of measure to make it more difficult for scammers, like not allowing liquidity to be withdrawn for at least a few hours / days, or not allowing devs to sell > 50% of tokens at once or any other function, becoz 99% are facing o rugpulls on pancacke swap, in log term this will be a end of he site and cacke value.
> 
> ### How does this feature benefit PancakeSwap users and CAKE holders?
> PancakeSwap turn a blind eye and let these rugs happen. Surely they can implement some sort of measure to make it more difficult for scammers, like not allowing liquidity to be withdrawn for at least a few hours / days, or not allowing devs to sell > 50% of tokens at once or any other function, becoz 99% are facing o rugpulls on pancacke swap, in log term this will be a end of he site and cacke value.
> 
> ### Anything else?
> PancakeSwap turn a blind eye and let these rugs happen. Surely they can implement some sort of measure to make it more difficult for scammers, like not allowing liquidity to be withdrawn for at least a few hours / days, or not allowing devs to sell > 50% of tokens at once or any other function, becoz 99% are facing o rugpulls on pancacke swap, in log term this will be a end of he site and cacke value.

**Comment by chef-jojo** [comment]
Let's keep this open.

**Comment by Lucienest** [comment]
Clearly, the OP has no idea how smart contracts work.

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/

**Comment by serajam** [comment]
So you even can't make a test transaction to swap back just to be sure that ppl can return their money?
