### ISSUE TITLE
Can't remove liquidity v2 (Bounty $1500)

### ISSUE THREAD

**Issue by crowszero12** [pancakeswap/pancake-frontend#3480]
So I've come accross so many topics over the internet and hit a dead end.
this is basically a Token-BNB liquidity and it happened I can't pull it out. Pancakeswap says "ERROR, This transaction would fail", I have almost $30,000 trapped in that liquidity so I'm giving away a bounty - It's better to give something or it might end up trapped forever.

I own the contract and its interacted with PC router and Factory

Tried Solutions :
X - Receive WBNB instead of BNB
X - Tried it on multiple browsers as well as on metamask app on android
X - Tried Approving the owner to the contracts
X - Tried increaseallowance

I found someone on an old github post telling _setSwapAndLiquifyEnabled_ set to false but I happen can't find it.

Console error : 
_removeLiquidityETHWithPermit
removeLiquidityETHWithPermitSupportingFeeOnTransferTokens_

PC router
https://bscscan.com/address/0x10ed43c718714eb63d5aa57b78b54704e256024e#code

Factory
https://bscscan.com/address/0xca143ce32fe78f1f7019d7d551a6402fc5350c73#code

Kindly DM me your solutions if you have any - Thanks!

**Comment by zhyd1997** [comment]
Maybe this is your network issue.

**Comment by zhyd1997** [comment]
Check the console carefully and see what else errors are displayed, the 3rd parameter is the real error.

**Comment by zhyd1997** [comment]
Try to increment your gas fee.

**Comment by crowszero12** [comment]
tried to set the slippage up to 49% still failing.

**Comment by zhyd1997** [comment]
@crowszero12 
not slippage:

https://user-images.githubusercontent.com/31362988/158165310-3211000b-bcf4-4593-911a-d6de3b02e245.mov

**Comment by crowszero12** [comment]
> @crowszero12 not slippage:
> Screen.Recording.2022-03-14.at.19.42.22.mov

I can't get to that part since if I click confirm of removal of liquidity this pops up : 
https://i.imgur.com/HLdbXci.png

**Comment by zhyd1997** [comment]
It's not expected.
Could you show a video?

**Comment by zhyd1997** [comment]
I confirm that the gas fee can be edited just like the video shows: https://github.com/pancakeswap/pancake-frontend/pull/3166#issuecomment-1058891991

**Comment by chef-jojo** [comment]
You won't able to show metamask confirm txn (gas fee edit describe above) if we can't estimate gas fee.
It usually happens when your signature or amount is incorrect. I can't tell more without the knowing the params
maybe try different amount

**Comment by crowszero12** [comment]
I won't get through the remove>confirm(which would popup a gas confirmation on metamask) instead I get the "ERROR - This transaction could fail. I even tried to withdraw 1 token = BNB, still the fail pops up.

**Comment by zhyd1997** [comment]
@crowszero12 
Could record a video?

**Comment by crowszero12** [comment]
https://user-images.githubusercontent.com/101549980/158169809-d42a9346-2e34-4d3f-8a04-5d0b003432c7.mp4

**Comment by zhyd1997** [comment]
**Would** fail?
Let me check the source code again.

**Comment by zhyd1997** [comment]
I found the `signatureData.deadline` is `1647258361` from this comment: https://github.com/pancakeswap/pancake-frontend/issues/3480#issuecomment-1066671914.

```js
new Date(1647258361 * 1000).toString() // 'Mon Mar 14 2022 11:46:01 GMT+0000 (Coordinated Universal Time)'
```

Does that mean the `signatureData` is expired?

@chef-jojo what's your idea?

**Comment by zhyd1997** [comment]
@crowszero12 
Did you try the `v1` liquidity?

**Comment by zhyd1997** [comment]
@crowszero12 
Have you tried the other wallet instead of MetaMask?

**Comment by crowszero12** [comment]
@zhyd1997 I did, I was using binance wallet (browser) but didn't find any luck at all. However unlike metamask it prompted approve/enable button, then same result with the remove/confirm which the same error appeared

**Comment by chef-jojo** [comment]
I bet you have high fee on transfer?

**Comment by chef-jojo** [comment]
let's buy $1500 lottery

**Comment by tkandr** [comment]
> crowszero12

Have the same problem. Can you please describe a solution more precise?

**Comment by Sheikhupuri** [comment]
This is due to bug on pancakeswap and I have  solution of this.I already helped  to recover funds of other Devs . Contact me on Telegram @FiazAhmad

**Comment by Rema161** [comment]
I had the same issue you know, 
Try to increase the slippage to 49% and consider increasing the allowance of the token, if it doesn't work, follow the steps on this video https://www.youtube.com/watch?v=yph8lMt7ojc
The problem will definitely be solved

**Comment by magemore** [comment]
Don't try from youtube link over some IndigoSwap website - it's a scam.
What helped me increasing slippage to 49%. It taxed me almost 4% for removing liquidity but it worked from pancake.

**Comment by CryptoAgents** [comment]
Recently encountered the same problem, cant remove liquidity, found a video in google https://www.youtube.com/watch?v=-AipX1RBt7w, it helped me

**Comment by Michelledevops** [comment]
I had the same problem, and this video helped me - https://www.youtube.com/watch?v=_9XkZOzT9pY
