### ISSUE TITLE
Integrating another wallet

### ISSUE THREAD

**Issue by oojoseph67** [pancakeswap/pancake-frontend#3488]
Hello
I just forked pancakeswap and i'm trying to integrating another wallet (ONTO wallet) other and the ones provided but i can't seem to get an idea for where the file/code is located. Can someone please help me out

**Comment by chef-jojo** [comment]
There you go
https://github.com/pancakeswap/pancake-frontend/blob/develop/packages/uikit/src/widgets/WalletModal/config.tsx
https://github.com/pancakeswap/pancake-frontend/blob/develop/src/utils/web3React.ts

We encourage you to join our [discord](https://discord.gg/pancakeswap) for these kind of questions.

**Comment by oojoseph67** [comment]
Thanks but this is the link to the fork pancakeswap i'm using and i can't seem to locate the directory as given above

https://github.com/oojoseph67/stakd_staking

**Comment by oojoseph67** [comment]
Thanks but this is the link to the forked pancakeswap i'm using and i can't seem to locate the directory or something similar to what you provided

https://github.com/oojoseph67/stakd_staking

Also the link to the discord seems to be bad
