### ISSUE TITLE
The page cannot retrieve this route

### ISSUE THREAD

**Issue by fiboswap** [pancakeswap/pancake-frontend#3502]
lp 0x1C590eeCD372a9Fbf947D0E886d909E05BB830f1 -> lp 0x7BdC4515BA3C8B8890D4E21585865Cc5D139f3ef

beto -> xps -> usdt

The page cannot retrieve this route

**Comment by inosgun** [comment]
0x7BdC4515BA3C8B8890D4E21585865Cc5D139f3ef[https://pancakeswap.finance](https://pancakeswap.finance/swap?inputCurrency=0xc72cc401122dbdc812ec88a2150aad5a39467401)
