### ISSUE TITLE
How to run and compile on local

### ISSUE THREAD

**Issue by CryptoChannnn** [pancakeswap/pancake-frontend#3662]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

I am currently trying to compile and run PancakeSwap Frontend via localhost and I keep running into a lot of code errors that I constantly have to change bits of the frontend code, does anyone have any idea why this is happening 

### Expected Behavior

I expected the frontend to run properly on localhost as it is the exact code for PancakeSwap's frontend.

### Steps To Reproduce

1. Go into PowerShell/ cmd or your code compiler of choice
2. Type "npm run build"
3. The code will start to compile and then it'll give the errors telling you that some code is wrong, missing or not defined.

### Environment

```markdown
- Device: Dell Inspiron Gaming Laptop
- OS: Windows 10 Home
- Browser: Brave Browser
- Wallet: Metamask
```

### Anything else?

![image](https://user-images.githubusercontent.com/103395714/162650445-ffb75cde-5b69-42b9-9913-0e8043ecb586.png)

**Comment by chef-jojo** [comment]
Use yarn

**Comment by CryptoChannnn** [comment]
![image](https://user-images.githubusercontent.com/103395714/162652032-7a1c4679-30e8-4f01-831a-9c07c9809d27.png)


keep getting these errors when trying to install yarn and its required packages

**Comment by chef-jojo** [comment]
> Do I gotta uninstall npm to use yarn? or could I just run yarn without any errors?

Please check contributing guide
https://github.com/pancakeswap/pancake-frontend/blob/develop/CONTRIBUTING.md

Just need to remove the node_modules. If you don't know what and how. 
Clone the repo into a new folder and then
```
yarn
yarn dev
# if you want to build with production mode
yarn build
```
