### ISSUE TITLE
Feat: ability to filter deposited farms

### ISSUE THREAD

**Issue by wivern-co-uk** [pancakeswap/pancake-frontend#375]
**Is your feature request related to a problem? Please describe.**
As a pancakeswap user, time to time, I want to review how my staked LP tokens are doing. So I'm navigating to https://pancakeswap.finance/farms and now have to find few deposited farms out of the whole list of active farms. (Currently 57 items). It's a lot of scrolling and distraction.

**Describe the solution you'd like**
Add a `staked` button to secondary navigation. This will navigate the user to page/view with a list of farms where his/her LP tokens are staked
![Screenshot 2021-02-02 at 23 20 21](https://user-images.githubusercontent.com/2115473/106670521-73b63280-65ad-11eb-9910-800d6a805d0a.png)

**Describe alternatives you've considered**
Add a new filter bar, like the one https://app.beefy.finance/ having to filter list on the existing page.
![Screenshot 2021-02-02 at 23 23 55](https://user-images.githubusercontent.com/2115473/106670820-d3acd900-65ad-11eb-9fb0-04a033f2cbae.png)

**Additional context**
This would dramatically improve the user experience for all the stakers.

**Comment by alejoasotelo** [comment]
![imagen](https://user-images.githubusercontent.com/1103289/107818062-c9c96980-6d55-11eb-8efa-c5ffc6f1b804.png)

Done!
You can close the issue!

**Comment by wivern-co-uk** [comment]
Great, much better now! Thank you!
