### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by kingd0x** [pancakeswap/pancake-frontend#3789]
I get this error when I try to install packages in Pancake-frontend

`yarn`

`error An unexpected error occurred: "https://registry.yarnpkg.com/@reduxjs/toolkit/-/toolkit-1.8.0.tgz: getaddrinfo EAI_AGAIN registry.yarnpkg.com`

**Comment by willmacdonald** [comment]
This is normally means there was a DNS lookup error from your computer. Maybe try changing your DNS servers.

**Comment by Supportprotocol** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14232768/
