### ISSUE TITLE
Local network setup guide?

### ISSUE THREAD

**Issue by maxifom** [pancakeswap/pancake-frontend#3970]
Is there a way to setup pancakeswap with local network. I want to use only swap/liquidity features, without staking farm etc. As I set chain id other than 56 frontend errors out as 56 is hardcoded in sdk and in the farms code. Can i solve it anyhow?

**Comment by chef-jojo** [comment]
You can check the .evn.testnet
And make a copy it into .evn.local

**Comment by maxifom** [comment]
> You can check the .evn.testnet
> And make a copy it into .evn.local

I did that. But it fails with error if i don't use chain_id from mainnet or testnet (which are hardcoded and not setup from envs)

**Comment by muhammad-azam301** [comment]
I clone pancake frontens but when I am going to run on my local machine it give me the errors, even I run excat cmd that provide int the readme.md
pnpm i
pnpm dev (this cmd stuch and no response)
kindly help to resolve this issue

**Comment by Mewsxd** [comment]
> I clone pancake frontend but when I am going to run on my local machine it give me the errors, even I run exact cmd that provide into the readme.md pnpm i pnpm dev (this cmd stuck and no response) kindly help to resolve this issue

Did you ever find a solution? I'm struggling with the same thing, i think we need to clone and run more repos of pancakeswap but i am unsure
