### ISSUE TITLE
[BUG] CAKE's logo is displayed as 8pay's logo.

### ISSUE THREAD

**Issue by OhtakeChizuru** [pancakeswap/pancake-frontend#4030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Trade

### Current Behavior

Nice to meet you, great chefs!

Thank you for your wonderful system.

I found something that looks like a bug.

I would like to check it.

When I choose 8pay in Trade, firstly the CAKE's logo displays as the 8pay's logo, and after a while the 8pay's logo displays.

firstly the wrong logo is displayed.

<img width="173" alt="Pasted Graphic 5" src="https://user-images.githubusercontent.com/53688628/170871901-a3461952-4fbe-4f51-ad73-08091f4bec46.png">

after a while 8pay's logo displays.

<img width="172" alt="Pasted Graphic 4" src="https://user-images.githubusercontent.com/53688628/170872140-8994246a-87cd-4f48-9e92-33f4013110cf.png">

I checked the 8pay's logo and the CAKE logo's HTML and I was supposed to see that they are assigned the same image.

8pay's img

<img width="778" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/53688628/170872403-e1f08f9a-9432-4ced-9b0f-bfc1669224a4.png">

CAKE's img

<img width="765" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/53688628/170872431-a9e9c986-64a7-46c9-9e72-feed1b50b9d5.png">

### Expected Behavior

The 8pay logo is displayed as follows from the beginning.

<img width="314" alt="image" src="https://user-images.githubusercontent.com/53688628/170872508-54781402-c1f9-43cb-a5f7-3cab6d1b9b27.png">

### Steps To Reproduce

1. access to the pancake swap's trade page.
2. import 8pay.
3. choose 8pay.
4. when the 8pay logo displays right, if you refresh the trade page, this issue is reproduced. 

### Environment

```markdown
- Device: MacBook air
- OS: Big Sur 11.6.2
- Browser: Google chrome
- Wallet: Metamask app
```

**Comment by chef-jojo** [comment]
@OhtakeChizuru thanks for the detailed issue. but I can't reproduce it in any case. 
It looks weird that the html is exact the same, there's no way we can control it 🤔
