### ISSUE TITLE
Try again Please Help

### ISSUE THREAD

**Issue by MetaDex-M** [pancakeswap/pancake-frontend#4052]
Hi I am getting an error on our token listing on Pancake platform. It been going on for weeks now. The price wont display. Seesm to be subgraph header issue I did try open a request on github for help but no response.

Issue for tech is api subgraph index.
I tried github but no answer

ERROR
Failed to decode block.number value: `subgraph Qmc3Q7LkXbwfDpTVAoiFbaMCjGqqS6bmMQdP7MZisdWMBg has only indexed up to block number 18083597 and data for block number 18083824 is therefore not yet available.
Please can you help with this. its not displaying price for our token on pancake.

Token contract address
0x558ad2b02cE979Ca54F88206ED8597c8c740774E
Its only on the Token Info page. the swap and pools are fine

**Comment by Supportprotocol** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14232768/

**Comment by chef-jojo** [comment]
As the error said, you specified the block number but the subgraph didn't catch up to it yet.
