### ISSUE TITLE
yarn install error

### ISSUE THREAD

**Issue by lubhub612** [pancakeswap/pancake-frontend#4060]
while installing yarn packages after  cloning pancake-frontend/
below sentry/cli error , command failed error given

![image](https://user-images.githubusercontent.com/45089340/172412007-b59e4e9e-dba8-4acb-b57a-0250376ae6ce.png)
please help me out why this error given,

**Comment by lubhub612** [comment]
please help me

**Comment by hotdogchain** [comment]
vi .yarnrc 

“
registry: https://registry.npm.taobao.org 
ENTRYCLI_CDNURL: https://cdn.npm.taobao.org/dist/sentry-cli 
sentrycli_cdnurl: https://cdn.npm.taobao.org/dist/sentry-cli 
”

**Comment by hanhunhan** [comment]
https://docs.microsoft.com/zh-CN/cpp/windows/latest-supported-vc-redist?view=msvc-170     install vc++

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/
