### ISSUE TITLE
Rollup build ends up with error in pancakeswap/uikit

### ISSUE THREAD

**Issue by Kalesberg** [pancakeswap/pancake-frontend#4089]
I wanted to use this uikit repo as a base for my other project.
But when I clone the repo and go to uikit package and run `yarn build` , I end up with rollup build errors.

Can anyone help on this?

**Comment by chef-jojo** [comment]
@chefilip 
https://github.com/pancakeswap/pancake-frontend/pull/3809/files#diff-cb0a1990ba52670ab2c56f831e950ca6447a9ca43ab7028565a66d0defd034d6L5-L10

**Comment by Supportprotocol** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14232768/

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/
