### ISSUE TITLE
[BUG] Build error occurred

### ISSUE THREAD

**Issue by alfirus** [pancakeswap/pancake-frontend#4167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

It shows 

  44 |     </StyledBottomNavItem>
  45 |   ) : (
> 46 |     <StyledBottomNavItem as={linkComponent} href={href} {...props}>
     |                                               ^
  47 |       {bottomNavItemContent}
  48 |     </StyledBottomNavItem>
  49 |   );

> Build error occurred
Error: Call retries were exceeded
    at ChildProcessWorker.initialize (/home/alfirus/protorium.com/node_modules/next/dist/compiled/jest-worker/index.js:1:11661)
    at ChildProcessWorker._onExit (/home/alfirus/protorium.com/node_modules/next/dist/compiled/jest-worker/index.js:1:12599)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess.emit (node:domain:475:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  type: 'WorkerError'
}
error Command failed with exit code 1.

### Expected Behavior

Successfully build

### Steps To Reproduce

1. Download development branch
2. Extract to Home
3. Delete yarn.lock
4. run "git init"
5. run "yarn install"
6. run "yarn build"

### Environment

```markdown
OS: Ubuntu 20
Nodejs: v16.15.1
Yarn: 1.22.19
```

**Comment by supportteam99** [comment]
Contact the Support team directly to correct the issue     https://direct.lc.chat/14269734/

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/

**Comment by Ranofty** [comment]
Facing same issue

**Comment by Erkan0404** [comment]
> Aynı sorunla karşı karşıya
