### ISSUE TITLE
Add pagination in farms to optimize resources [change to enhancement please]

### ISSUE THREAD

**Issue by alejoasotelo** [pancakeswap/pancake-frontend#422]
**Is your feature request related to a problem? Please describe.**
At this moment pancakeswap have 63 farms in 3 columns, the scroll of page is large and hard to read with so many items. Also having so many elements also implies more calculations, therefore more consumption of resources for low end devices.

**Describe the solution you'd like**
Pagination of 12 or 24 items maybe? a select with options (6, 12, 24, 48)?
Less items, less resource consumption and therefore faster loading speed. 

I want to collaborate with this project but I need the REACT_APP_CROWDIN_APIKEY and REACT_APP_CROWDIN_PROJECTID. Could someone send me the keys to try to help?

Congratulations for the project and thank you for sharing pancake-frontend on github! 🥞🙌

Best!

**Comment by BaptisteGarcin** [comment]
that would be great and sorting by APY or TLV could be nice as well!

**Comment by alejoasotelo** [comment]
yes, would be great sorting too!!!

**Comment by memoyil** [comment]
@Chef-Chungus new farming page fixing those issues. I think this issue can be closed

**Comment by alejoasotelo** [comment]
The classification yes and I like it a lot but the pagination not at the moment. I count more than 50 farms. I think the page is loading a lot of farms and a lot of requests. Perhaps limiting to 20 would improve performance.

**Comment by memoyil** [comment]
can you label it as enhancement?

**Comment by alejoasotelo** [comment]
No i can't. I don't have permissions.

**Comment by noblica** [comment]
I think we can close this, since the infinite scroll PR was merged?

**Comment by Ranofty** [comment]
Hello Please I have a problem with my farms and pools i change my MasterChef I put pids in the masterChef is displaying Percentages but not approving Please someone should help me out 🥺🙏
