### ISSUE TITLE
[BUG] Tokens info aren't loading

### ISSUE THREAD

**Issue by GauthamramRavichandran** [pancakeswap/pancake-frontend#4239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Info

### Current Behavior

Tokens info on [this page](https://pancakeswap.finance/info) is not loading
<img width="1275" alt="Screenshot 2022-07-08 at 07 44 11" src="https://user-images.githubusercontent.com/30320759/177903288-39a02522-7258-4209-a458-637d3d6b3898.png">

Tested on Firefox and Safari, still the same

### Expected Behavior

Tokens info should be visible

### Steps To Reproduce

1. Open https://pancakeswap.finance/info in the browser

### Environment

```markdown
- Device: MacBook Air
- OS: Monterey 14.1
- Browser: Firefox/Safari
- Wallet: Metamask
```

**Comment by Giamme** [comment]
I have the same problem both on Windows and macOS.
This is the error message I get in the console:
```
Failed to fetch info overview Error: Failed to decode `block.number` value: `subgraph Qmc3Q7LkXbwfDpTVAoiFbaMCjGqqS6bmMQdP7MZisdWMBg has only indexed up to block number 19202800 and data for block number 19309541 is therefore not yet available`: {"response":{"errors":[{"message":"Failed to decode `block.number` value: `subgraph Qmc3Q7LkXbwfDpTVAoiFbaMCjGqqS6bmMQdP7MZisdWMBg has only indexed up to block number 19202800 and data for block number 19309541 is therefore not yet available`"}],"status":200,"headers":{"map":{"content-length":"234","content-type":"application/json"}}},"request":{"query":"query overview {\n      pancakeFactories(\n        block: { number: 19309541}\n        first: 1) {\n        totalTransactions\n        totalVolumeUSD\n        totalLiquidityUSD\n      }\n    }"}}
```
fired from ``` instrument.js:109 ```

The same problem applies to all three subpages under ```/info``` (overview, pool, tokens)

**Comment by fabseeeee** [comment]
same problem here

**Comment by chef-jojo** [comment]
Thanks for the report. It’s fixed
