### ISSUE TITLE
[BUG] <Wallet Balance not loading>

### ISSUE THREAD

**Issue by KingzRex** [pancakeswap/pancake-frontend#4272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Trade

### Current Behavior

After Building the  project, serving to localhost and connecting wallet, the wallet balance keeps loading and never loads up.,

### Expected Behavior

The dapp should be able to load wallet balances on connection to metamask

### Steps To Reproduce

yarn install 
yarn build 

You can clear build errors by moving the middleware.ts file outside of the views folder

### Environment

```markdown
- Device: gitpod code environment
- OS: ubuntu
- Browser: Chrome
- Wallet: Metamask
```

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/

**Comment by tadryanom** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Product
> Trade
> 
> ### Current Behavior
> After Building the project, serving to localhost and connecting wallet, the wallet balance keeps loading and never loads up.,
> 
> ### Expected Behavior
> The dapp should be able to load wallet balances on connection to metamask
> 
> ### Steps To Reproduce
> yarn install yarn build
> 
> You can clear build errors by moving the middleware.ts file outside of the views folder
> 
> ### Environment
> ```gfm
> - Device: gitpod code environment
> - OS: ubuntu
> - Browser: Chrome
> - Wallet: Metamask
> ```
> 
> ### Anything else?
> _No response_

I believe it is the same problem with me.

![not_load](https://user-images.githubusercontent.com/1080580/180928726-5c788ec6-5e06-43f9-96c4-9bae6768e904.png)

**Comment by Charlespate** [comment]
> I believe it is the same problem with me.
> 
> 
> 
> ![not_load](https://user-images.githubusercontent.com/1080580/180928726-5c788ec6-5e06-43f9-96c4-9bae6768e904.png)
> 
> 

Which wallet are you connect with ?

**Comment by Charlespate** [comment]
> I believe it is the same problem with me.
> 
> 
> 
> ![not_load](https://user-images.githubusercontent.com/1080580/180928726-5c788ec6-5e06-43f9-96c4-9bae6768e904.png)
> 
> 

@tadryanom which wallet are you connected with?

**Comment by KingzRex** [comment]
I solved the first issue by commenting out the pancakeswap node.

`#NEXT_PUBLIC_NODE_PRODUCTION = "https://nodes.pancakeswap.com"`

additional fixes for build errors
rename middleware.ts to _middleware.ts and the file out from the "views" dir to the "src" dir

**Comment by tadryanom** [comment]
> > I believe it is the same problem with me.
> > ![not_load](https://user-images.githubusercontent.com/1080580/180928726-5c788ec6-5e06-43f9-96c4-9bae6768e904.png)
> 
> @tadryanom which wallet are you connected with?

Apologies for the delay. I tested it with Metamask and Trust Wallet
