### ISSUE TITLE
How can I contact you？I need REACT_APP_CROWDIN_PROJECTID

### ISSUE THREAD

**Issue by Lbt777** [pancakeswap/pancake-frontend#4284]
You'll need this in order to get the i18n system to work
REACT_APP_CROWDIN_PROJECTID

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/

**Comment by chef-jojo** [comment]
you don't need `REACT_APP_CROWDIN_PROJECTID` anymore
