### ISSUE TITLE
Harvest all count

### ISSUE THREAD

**Issue by heyimbrucelee** [pancakeswap/pancake-frontend#430]
**Bug Description**
Im actually in 2 farms / 2 pools
On home : harvest all (3)

**Steps to Reproduce**

**Expected Behavior**
On home : harvest all (4)

**Additional Context**
Im in the CAKE pool / COMP
Maybe related

**Comment by Justin2997** [comment]
Hi @heyimbrucelee seems to be good task for me to start contributing. Can you commente with the current farms and pools that you have setup ?

**Comment by heyimbrucelee** [comment]
> Hi @heyimbrucelee seems to be good task for me to start contributing. Can you commente with the current farms and pools that you have setup ?

this issue was related to the COMP/CAKE pool i guess,
COMP/CAKE pool isnt active anymore , no more issue.
it may reappear for the next ???/CAKE pool if misconfigured
