### ISSUE TITLE
Nothing happens if we want to add stake in Farm or deposit tokens in pool

### ISSUE THREAD

**Issue by rohit-010** [pancakeswap/pancake-frontend#431]
![image](https://user-images.githubusercontent.com/21234961/107560616-78926c00-6bd5-11eb-99db-2572c0e22291.png)

I am using Binance Smart Chain as wallet on Chrome browser

Attached image where UI get's stuck nothing happens after approving from wallet

Steps:
Go to Farm
Example Cake-BNB LP
Click on + button to which opens Stake LP tokens 
Enter number of stake click on confirm
Which opens wallet, Approve transaction in wallet
Nothing happens after approval

Thanks

**Comment by rohit-010** [comment]
Looks like this issue is for wallet : Binance Chain wallet extension on chrome , so closing this raised defect

Thanks

**Comment by Ranofty** [comment]
Hello Please I have a problem with my farms and pools i change my MasterChef I put pids in the masterChef is displaying Percentages but not approving Please someone should help me out 🥺🙏
