### ISSUE TITLE
Remove the input component 

### ISSUE THREAD

**Issue by RabbitDoge** [pancakeswap/pancake-frontend#438]
Remove https://github.com/pancakeswap/pancake-frontend/blob/develop/src/components/Input/Input.tsx and replace it by the Input in the uikit 
https://pancakeswap.github.io/pancake-uikit/?path=/story/components-input--default

**Comment by StephTech** [comment]
Should we create a InputAdornment component in the UIKit ? The Input component alone from UIKit doesn't handle adornments props

**Comment by RabbitDoge** [comment]
Probably yes. If you want to do it, assign this issue to you, and link it in you pr.

**Comment by rickmort** [comment]
Hey! I'm working on it! =)
