### ISSUE TITLE
Made a mistake setting price on new liquidity pool, when adding my new token to pancakeswap. How do i reset?

### ISSUE THREAD

**Issue by johnrockson** [pancakeswap/pancake-frontend#449]
Made a mistake setting price for token when I was setting up a new liquidity pool. 

How do I reset the price this?

I removed the liquidity when I realized the error but now I am unable to reset the price. 

Can you remove the token from pancakeswap so that I can re-add?

Please help.

**Comment by Chef-Chungus** [comment]
There's no resetting it. you set the price and that is the price at which the liquidity provider tokens were pegged at. The only way for it to go back to normal is for it to be traded down to the normal price. 

We aren't centralized, we can't just change things in a backend, this is the blockchain.
