### ISSUE TITLE
home hero not responsive

### ISSUE THREAD

**Issue by khubaib-ak-47** [pancakeswap/pancake-frontend#4545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

IN HOME PAGE UNDER NAVBAR TEXT IS TOP ON BUNNY 633PX TO1057PX 

### Expected Behavior

FIX THIS!!

### Steps To Reproduce

1- Clone this repo
2- Install dependencies
3- Start app 
4- Open home page 

### Environment

```markdown
- Device: HP
- OS: Window
- Browser: Chrome
- Wallet: MetaMask
```

### Anything else?

![Capture](https://user-images.githubusercontent.com/104334611/185901899-a8c346fe-5a7c-40bf-ba1e-e5234e664620.PNG)

**Comment by Chef-Yogi** [comment]
got it 
let me check it
