### ISSUE TITLE
[BUG] Fraction toSignificant division by zero error on Add Liquidity page

### ISSUE THREAD

**Issue by PiotrJozefow** [pancakeswap/pancake-frontend#4559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Trade

### Current Behavior

When trying to add liquidity to newly released token, after typing in the new token input website crashes with "Something went wrong".

f.e.:
https://pancakeswap.finance/add/0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56/0x340724464cf51a551106cC6657606Ee7d87B28b9

Console shows Division by zero error.

After running `pancake-frontend` locally I noticed it's caused by `multiplyPriceByAmount` call in `useBUSDCurrencyAmount` function and the root cause is that in 
`this.adjustedForDecimals` instance of `Price`, the `denominator` value is equal to zero, therefore causing Division by zero error in toSignificant call:

```
  export class Price<TBase extends Currency, TQuote extends Currency> extends Fraction {
  ....
  public toSignificant(significantDigits: number = 6, format?: object, rounding?: Rounding): string {
    return this.adjustedForDecimals.toSignificant(significantDigits, format, rounding)
  }
```

```
  export class Fraction {
  ...

  public toSignificant(
    significantDigits: number,
    format: object = { groupSeparator: '' },
    rounding: Rounding = Rounding.ROUND_HALF_UP
  ): string {
    invariant(Number.isInteger(significantDigits), `${significantDigits} is not an integer.`)
    invariant(significantDigits > 0, `${significantDigits} is not positive.`)

    Decimal.set({ precision: significantDigits + 1, rounding: toSignificantRounding[rounding] })
    const quotient = new Decimal(this.numerator.toString())
      .div(this.denominator.toString())
      .toSignificantDigits(significantDigits)
    return quotient.toFormat(quotient.decimalPlaces(), format)
  }
```

Adding another invariant shows more descriptive error:
`invariant(Number(this.denominator.toString()) > 0, 'Denominator is not positive.')`

But it's still unclear to me why denominator ends up with zero value in the first place and what is the desired behaviour if the denominator is zero.

![Screen Shot 2022-08-23 at 09 03 09](https://user-images.githubusercontent.com/10623289/186094083-245b0818-0b0e-47dd-b3f6-b60ca23e45ef.png)

### Expected Behavior

Error should not be thrown

### Steps To Reproduce

1. Open: https://pancakeswap.finance/add/0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56/0x340724464cf51a551106cC6657606Ee7d87B28b9
2. Input any value in both fields

### Environment

```markdown
- Device: MacBook
- OS: MacOS
- Browser: Chrome
- Wallet: Metamask
```

**Comment by chef-jojo** [comment]
Thanks for the detailed issues. Seems like someone create pair without providing liquidity. will fix it soon!

**Comment by PiotrJozefow** [comment]
@chef-jojo Thank you very much for quick response!
