### ISSUE TITLE
Wallet disconnecting when going between <Trade> and other navigations in menu

### ISSUE THREAD

**Issue by adaamz** [pancakeswap/pancake-frontend#456]
**Bug Description**
Wallet disconnecting when going between <Trade> and other navigations in menu

**Steps to Reproduce**

1. Login (connect wallet)
2. Click on Trade > Exchange for example
3. You are logged off, so you need to login again

**Expected Behavior**
You are logged in whole time whenever you click in menu

**Additional Context**
Looks like wrong cookies scope as the <Trade> items navigate to exchange.pancakeswap.finance, while other items navigate to pancakeswap.finance

**Comment by RabbitDoge** [comment]
Should be fixed now. As we change the key name for persisting the login state, you'll probably have to login once again, then it will work.
