### ISSUE TITLE
[BUG] Filters are not cleared on NFT Activity Page

### ISSUE THREAD

**Issue by stvegerrad** [pancakeswap/pancake-frontend#4592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

NFT

### Current Behavior

![image](https://user-images.githubusercontent.com/108422664/186943188-a3dca5a6-8061-408c-a945-f7a2b8542efa.png)
I clicked **Clear** button but **Modified** filter was not disappeared.

### Expected Behavior

All filters should be cleared after I click the **Clear** button.

### Steps To Reproduce

1. Go to [NFT Activity Page](https://pancakeswap.finance/nfts/activity).
2. Select some filters and click **Clear** button. (At first time, it works well)
3. After filters cleared, then select some filters again.
4. Click **Clear** button

### Environment

```markdown
- Device: DELL
- OS: Windows 10
- Browser: Chrome
- Wallet: Metamask
```

### Anything else?

I fixed those issues and sent pull request. Please check it.
https://github.com/pancakeswap/pancake-frontend/pull/4591

**Comment by stvegerrad** [comment]
yeah, you are right. but I already fixed on #4591

**Comment by stvegerrad** [comment]
The issue on collection filters is also fixed.

**Comment by stvegerrad** [comment]
Deep clone is also good, but the way I used on #4591 is simple and smart.

**Comment by stvegerrad** [comment]
As a result, my pull request was declined. I wanted to be the one of the contributors but the dream was broken.
Thanks anyway.

**Comment by chef-jojo** [comment]
I'm fine with both PR. but @stvegerrad PR contains unrelated changes there.
Thanks for rising the issue anyway!
