### ISSUE TITLE
[BUG] imToken Modal height incorrect

### ISSUE THREAD

**Issue by chef-jojo** [pancakeswap/pancake-frontend#4596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

`--vh` css variable incorrect on imtoken

detail see #4566

### Expected Behavior

Modal should work as expected

### Steps To Reproduce

use latest version of imToken app.
open browser with https://pancakeswap.finance/
click trade tab
click token

### Environment

```markdown
- Device:
- OS:
- Browser:
- Wallet: imToken
```

**Comment by 0xBRL** [comment]
Hey @chef-jojo, I tried to reproduce the error locally/production but it looks like it's already fixed, right? 🤔

**Comment by chef-jojo** [comment]
> Hey @chef-jojo, I tried to reproduce the error locally/production but it looks like it's already fixed, right? 🤔

Can still reproduce in imtoken wallet
