### ISSUE TITLE
[BUG]Farm and Pool

### ISSUE THREAD

**Issue by DiornanR** [pancakeswap/pancake-frontend#4597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Farms

### Current Behavior

Good morning dear, I am presenting a small problem, I can't get how to reduce the decimals, which shows in the APR of the farm and in the pool, and in the ROI calculator it shows me infinite balance when placing an amount, if you could help me I would be grateful

here I leave some images

[img]https://i.imgur.com/NfyvagT.jpg[/img]

[img]https://i.imgur.com/4VAhkTB.jpg[/img]

### Expected Behavior

Help me please

### Steps To Reproduce

:S

### Environment

```markdown
- Device: PC
- OS: Windows 10 64bit
- Browser: Microsoft Edger
- Wallet: Metamask
```

### Anything else?

ty

**Comment by chef-jojo** [comment]
duplicated, and not a bug
for this kind of forking QA question, please use discussion instead
https://github.com/pancakeswap/pancake-frontend/discussions/4595
