### ISSUE TITLE
Lottery document is now obsolote

### ISSUE THREAD

**Issue by memoyil** [pancakeswap/pancake-frontend#462]
**Bug Description**
Lottery document is now obsolote

**Steps to Reproduce**

1. Go to lottery
2. Click on read more
3. It says Lottery Ticket Fee for 1 ticket: 10 CAKE 

**Expected Behavior**
Lottery Ticket Fee for 1 ticket: 1 CAKE  and more other changes

**Comment by Chef-Chungus** [comment]
Resolved
