### ISSUE TITLE
[Feature Request] Improving of Pottery page usability, information display and grouping of the drawing result

### ISSUE THREAD

**Issue by pandamakerdroid** [pancakeswap/pancake-frontend#4705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem you are facing?

The new pottery has a different nature compare to the lottery game. 
It could have up to 10 series of concurrent drawing happening in a day.
As of 09/09/2022, there were already 2. 

The current drawing results are flat and mixed together.
They are identified by a round index at the top of the card and the deposit date at the bottom of the card. 

This does not bring a clear outlook, whether 
- how does a caker perform with his/her deposit in a series
- how many drawings are still left for a deposit series
- a clear indication of which drawing result belongs to which deposit

### Describe the solution you'd like

1. Regroup the drawing result, and make a round relative to a pottery serie, which the pottery result becomes a multi-dimensional object which could (potentially) group the result as following
- Pottery Series# (Deposit Date 33/33/3333)
   - Round 1: date, winners
   - Round 2: date, winners
   - Round 3: date, winners
   - Round 4: date, winners
   - ...

2. At the Finished round section of the page, provide a dropdown/filter for users to select their participated pottery series, which could be a multi-col display (e.g. up to 3 per row, up to 3-4 rows), with default display only participated series

3. In the claim tab of the participated Pottery series, provide also a serie number, or at displaying serie overview (round 0-10) and the winning performance

4. For the winners of each round, it would be nice to also display their deposited cakes (rough range would be already nice, such as 1XXX), which could indicate users for the deposit amount preparation for the next Pottery serie.

### How does this feature benefit PancakeSwap users and CAKE holders?

This will deliver an improved overview of the drawing results and suggest a meaningful amount of cake to be deposited to increase the winning chance, also passively notifies user about the rounds left in a Pottery serie and the claim date

### Anything else?

[Suggestion for Claim tab](https://raw.githubusercontent.com/pandamakerdroid/pic-upload/master/pottery.drawio.png)
![pottery drawio](https://user-images.githubusercontent.com/38146321/189480250-3b046a0c-bad0-4003-a5c1-b8a0ed543655.png)

[Suggestion for drawing result](https://raw.githubusercontent.com/pandamakerdroid/pic-upload/master/potteryresult.drawio.png)
![potteryresult drawio](https://user-images.githubusercontent.com/38146321/189480268-18a21a2b-ce6a-459e-861f-6e078567cc2e.png)

**Comment by 0xBRL** [comment]
Heey @chef-jojo, I can work this on?
