### ISSUE TITLE
I add liquidity in the dex and it does not show me in poocoin

### ISSUE THREAD

**Issue by DiornanR** [pancakeswap/pancake-frontend#4706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Trade

### Current Behavior

Hello to all my dear colleagues, I am working on the launch of a new DEX and I am testing and I have added liquidity but on your poocoin platform it does not show me the graph,

Official Token SeedSwap DEX: Contract 0xd19f3f2386D8c5235259fa767c8a5a051F1e25A1

what would be the procedure for your platform to show liquidity? of the new DEX.

to the contracts that liquids were added from the new DEX are:

RMOG: 0xee33114ef9afb0779f0505c38afbb1644f4073cc

CRIPTOGADO: 0x4ffa1dfc76f74c58e7ab4838be2a7cdf4e3f2108

Here I will leave the txn hashes:

https://bscscan.com/tx/0xeb857b1deabb78391d4c0798286f3d7935311897450547f39f6f42a0baa8f5d5

https://bscscan.com/tx/0xa1fd8278776641b5ec44a47b5531534209accbe8e43ad65ebbb8c5d1fbfc60a4

https://bscscan.com/tx/0x55bd991de19097dfac536f68d221ddf2160122c763c7d0d6f68412bca8f13963

https://bscscan.com/tx/0x4fcf293a4a6504e44e05ff76aa326e76a35f4835ea1a427be75bc5cd3a38a0a2

### Expected Behavior

Hello to all my dear colleagues, I am working on the launch of a new DEX and I am testing and I have added liquidity but on your poocoin platform it does not show me the graph

### Steps To Reproduce

Ready

### Environment

```markdown
- Device:PC
- OS: Windows 10 64bit
- Browser: Chrome
- Wallet:
```

### Anything else?

ty

**Comment by chef-jojo** [comment]
poocoin?
