### ISSUE TITLE
Change Text Wallet Connect Trust Wallet

### ISSUE THREAD

**Issue by ekawibisono1** [pancakeswap/pancake-frontend#4724]
Hello,

Can you help me to change a text PancakeSwap wants to connect to your wallet?, because i find all file Not Found.

![WhatsApp Image 2022-09-13 at 03 20 37](https://user-images.githubusercontent.com/112782237/189770421-b6d3daf7-4e73-49e2-b392-24fd740df9d3.jpeg)

Thanks

**Comment by ekawibisono1** [comment]
Additional: can you tell me where this folder is located? because I've been looking for it can't be found

![image](https://user-images.githubusercontent.com/112782237/189781463-b037e018-1360-4e88-a360-bd80beae6fdd.png)

**Comment by leoDEVa** [comment]
Please see the link below to our dedicated support line:

Support :[POA Live Support](https://forumpoa.network/I/-/l/main.html#)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**
