### ISSUE TITLE
Warning when open Info->Pairs

### ISSUE THREAD

**Issue by memoyil** [pancakeswap/pancake-frontend#473]
**Bug Description**
Warning: The data on this site has only synced to Binance Smart Chain block 4928512 (out of 4932297). Please check back soon.

**Steps to Reproduce**

1. Go to Info
2. Go to Pairs

**Expected Behavior**
To see the pairs

**Comment by ChefKai** [comment]
Due to the Berry IFO, data sync is a bit delayed on the dashboard; it is catching up and will be up-to-date soon. Please check back soon.

Also the correct repository to post issue about Info is here: [pancakeswap/pancake-info](https://github.com/pancakeswap/pancake-info)
