### ISSUE TITLE
Developers Turned Scammers?

### ISSUE THREAD

**Issue by Megawatt7** [pancakeswap/pancake-frontend#475]
![image](https://user-images.githubusercontent.com/41215180/108113727-da375800-7065-11eb-9576-44fec498e24c.png)

Hello, how is it that there's $16,559,214 in volume for BUNNY/WBNB on PancakeSwap but the general public can't trade it? I'm going to be contacting lawyers soon if the situation is not resolved.

**Comment by bread-cn** [comment]
wtf

**Comment by bread-cn** [comment]
> wtf

😡😡😡
