### ISSUE TITLE
Zap in amount too low

### ISSUE THREAD

**Issue by jemshit** [pancakeswap/pancake-frontend#4775]
Hi, 
when trying to add single token to a pool using Zip feature, i get "zip in amount too low" error. But i couldn't find what is the minimum amount. Could you add it to the UI ?

**Comment by jemshit** [comment]
Figured out this error is shown when checkbox of token with zero amount is left selected.

**Comment by chef-jojo** [comment]
Hey @jemshit. thanks for raising this. I think it's a good point to show what to do. The minimum amount is `1000` btw.
I will keep this issue as an UX improvement task
