### ISSUE TITLE
UI elements wrong (lottery countdown time)

### ISSUE THREAD

**Issue by ThisAndyMason** [pancakeswap/pancake-frontend#481]
**Bug Description**
'Until ticket sale' times on lottery page are not reflecting the correct hour number (always 0).

**Steps to Reproduce**

1. Go to lottery page
2. See 'Until ticket sale' time wrong

**Expected Behavior**
Time to reflect correctly.

I am not sure what the correct time is meant to be for the ticket sale but this keeps rolling over to 59 minutes after it counts to zero. So im assuming the hour is just not reflecting correctly
Only seen on desktop. Have not checked on mobile.
MacOS, Chrome Browser version 88.0.4324.150.

![image](https://user-images.githubusercontent.com/25403673/108261398-827b1880-715b-11eb-98ba-18430ab2e158.png)

**Comment by Chef-Chungus** [comment]
Thank you, this was due to our scheduler having an issue. all resolved now. Nothing to do with the frontend.
