### ISSUE TITLE
Tust wallet connect seems to be linking to a fake chrome extension

### ISSUE THREAD

**Issue by duck-dev-go** [pancakeswap/pancake-frontend#4880]
When you try to connect to trust wallet it will send you to this chrome extension

https://chrome.google.com/webstore/detail/trust-wallet/egjidjbpglichdcondbcbdnbeeppgdph/related

Which seems to have been commited here

https://github.com/pancakeswap/pancake-frontend/blob/168f5b4c0d0bf6c7ea78cbaaec8ef38c357a79ad/src/config/wallet.ts

The chrome extension appears to be fake.

**Comment by chef-jojo** [comment]
not a fake one. they are in beta phase.
you can use wallet connect if you have concerns about it
