### ISSUE TITLE
[solved] liquidity remove not working

### ISSUE THREAD

**Issue by chymian** [pancakeswap/pancake-frontend#496]
for 2 days, I was trying to remove a liquidity-Pair, which was not going through, because the confirm-button did nothing.

it boild down to a false date/time in that linux/debian VM, which I use for crypto-realted stuff only (walltes, & isolated browser).
the KVM-VM did get suspended at one time and did not reset the time to actual when it came online again.
there was no error-msg or hint from PCS-wsite. 
after fixing this issue, rebooted the VM, every thing went back to normal.
might this info help sb, and/or maybe you guys can prg. some error-msg into your fabulous WS.

![PC-Swap_2021-02-20_06-30](https://user-images.githubusercontent.com/1899961/108586124-afdae880-734c-11eb-9929-0b0633f193b4.png)

thx a lot for your dedication & work
guenter

**Comment by Chef-Chungus** [comment]
Thank you for updating the Issue and letting us know the problem
