### ISSUE TITLE
Fetcher class in SDK V2

### ISSUE THREAD

**Issue by andreyLed** [pancakeswap/pancake-frontend#5002]
Why was the Fetcher and TokenAmount class removed from the SDK?

**Comment by aress31** [comment]
Can you please reopen this ticket, the `UniSwap SDK` provides a `Fetcher`, is there any reason why `PCS` doesn't?

**Comment by 0xhohenheim** [comment]
Why is this closed? From what I can tell the `Fetcher` class is the only way to get a `Pair` for creating a `Route`
Unless there's an alternative, isn't this a major issue?
