### ISSUE TITLE
[Bounty] Update slider component to new design

### ISSUE THREAD

**Issue by Chef-Chungus** [pancakeswap/pancake-frontend#530]
**Reward allocation:** 
$250 in CAKE

**Description:**
Our current site slider component is a little boring, we want to add some fun to it. 
Task is to replace the existing slider component with the bunny version (please see figma for more design details)
You will need to do this in the UI Kit & apply it to the respective areas on the website (exchange & main site)
**Design:**
![image](https://user-images.githubusercontent.com/71833681/109262115-4e32e680-7844-11eb-8c71-83cfeb3d0274.png)

**Resources:**
https://www.figma.com/file/q5dKq3BuQZ4YzV5pR0Mt2M/Design-System-UI?node-id=3840%3A95164

**Comment by maroon-sunlight** [comment]
hello, I will be working on this. Will open a PR when it's ready.
