### ISSUE TITLE
I don't see a QR code or anything else when I click on "connect" -> "Binance Chain Wallet".

### ISSUE THREAD

**Issue by erlandvr** [pancakeswap/pancake-frontend#533]
**Bug Description**
A clear and concise description of the bug.

**Steps to Reproduce**

1. Go to "Connect"
2. Click on "Binance Chain Wallet"

**Expected Behavior**
I Think there should be a QR code that pops up to connect your wallet.

**Additional Context**
Up to date Chrome Browser on Mac OS

**Comment by Chef-Chungus** [comment]
Binance chain wallet is a browser extension.
https://chrome.google.com/webstore/detail/binance-chain-wallet/fhbohimaelbohpjbbldcngcnapndodjp?hl=en

No QR needed, just add it to your browser

**Comment by erlandvr** [comment]
Thank you for the super fast response.
