### ISSUE TITLE
UI Card border-radius divergence

### ISSUE THREAD

**Issue by meddou** [pancakeswap/pancake-frontend#538]
Hi, is there any reason for the card's shadow rainbow animation to have a different border-radius than the card itself ? (16px for the background and 32px for the card).
Reddit post talking about it : https://www.reddit.com/r/pancakeswap/comments/lpeibm/this_is_the_worst_thing_about_pancakeswap/
I totally agree with the post, it makes the shadow weird.

I think this is basically a one line tweak, I can submit a PR.

Let me know 🥞

**Comment by RabbitDoge** [comment]
Feel free to open a pr.
Don't forget to reference this issue.
