### ISSUE TITLE
[Feature Request] Add Infinity Wallet Connector

### ISSUE THREAD

**Issue by InfinityWallet** [pancakeswap/pancake-frontend#5449]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem you are facing?

Yes, we have hundreds of thousands of users accessing the Infinity Wallet and receive daily reports regarding connecting with the Infinity Wallet Web3 Desktop Browser to PancakeSwap. This is an issue for both users of PancakeSwap and users of the Infinity Wallet. 

We have tried reaching out to the PancakeSwap team a couple of times since their inception, however have had no luck of getting a reply, hence why we are now opening a issue here due to the increased demand from our users.

### Describe the solution you'd like

What we are requesting is the integration of the Infinity Wallet Connector, this will allow both PancakeSwap users and Infinity Wallet users to easily access PancakeSwap via the Infinity Wallet, which was the first web3 desktop browser in the space launched in 2019 and supporting hundreds of thousands of BSC users.

With your permission we can integrate the connector for you and make a pull request.

### How does this feature benefit PancakeSwap users and CAKE holders?

Infinity Wallet is one of the leading desktop wallets in the space supporting hundreds of thousands of users. Integrating the Infinity Wallet connector will allow PancakeSwap to be more easily accessed on desktop with in the first desktop web3 browser, additionally it will also allow PancakeSwap to be integrate into our web3 app store driving further exposure/awareness and adoption to PancakeSwap.

**Comment by InfinityWallet** [comment]
Hello @chef-jojo, we are following up regarding the proposal. Thanks

**Comment by roymoses07** [comment]
Done

**Comment by InfinityWallet** [comment]
Hello, we are following up again. We have been trying to partner with Pancakeswap for over a year now and have had near to no luck in getting a reply. We are one of the largest desktop wallets in the space, supporting hundreds of thousands of BSC users and have a high demand to support PancakeSwap. However this will only be possible if you are able to integrate our connector?

**Comment by alinagomez6616** [comment]
I will be taking a look at this issue.

**Comment by InfinityWallet** [comment]
Hello, we are following up regarding this issue. Thanks
