### ISSUE TITLE
I wanna see stacked amount value in cake or in USD

### ISSUE THREAD

**Issue by julienbourgainpro** [pancakeswap/pancake-frontend#545]
**Is your feature request related to a problem? Please describe.**
as a user, I want to view the evolution of the value of my stacked assets.

**Describe the solution you'd like**

I wanna see the current value of my coin in a pool or liquidity pair in a farm.
Example : 
![image](https://user-images.githubusercontent.com/62098507/109484451-bcfc8380-7a80-11eb-8b24-9873492775de.png)

It could be an awesome to see the evolution of every assets.

In farm it would be nice to see the value of pairs in cake to remember how much i have stacked on this or this farm

So ! pancakeswap is awesome ! Thanks you so much

**Comment by Chef-Chungus** [comment]
This is planned in a future update.
Estimated release ~ 2 weeks.

**Comment by memoyil** [comment]
@Chef-Chungus Issue can be closed

**Comment by stetorm** [comment]
I started last version on develop branch but I can't see. I was speaking about Liquidity Pool not Syrup Pool; and by the way launching locally I see only 2 of my 3 staked pool (which I can see on official url).
![Schermata del 2021-05-07 14-00-26](https://user-images.githubusercontent.com/3285138/117446880-09f74d00-af3d-11eb-8215-60e8ac10b031.png)

**Comment by memoyil** [comment]
The first picture that you showed is taken from pools instead of farms, thats why i said it is implemented already

**Comment by stetorm** [comment]
Yes it think he showed how he would have the same information also in liquidity pool. So what do you want to do with this issue and this feature? I available to try to implement it even it would be my first one, I'd like to collaborate, let me know.

**Comment by stetorm** [comment]
Ok thanks @memoyil ! So what do u think @Chef-Chungus ?

**Comment by ChefNina** [comment]
Let me close it as the implementation is done. Please check them in farms/pools!
https://pancakeswap.finance/farms
https://pancakeswap.finance/pools
Thanks @julienbourgainpro for flagging!
