### ISSUE TITLE
Infite loop on binance chain wallet - can't approve contract

### ISSUE THREAD

**Issue by loic-roux-404** [pancakeswap/pancake-frontend#554]
**Bug Description**
Can't approve contract in `farm` space

**Steps to Reproduce**

1. Go to [/farms](https://pancakeswap.finance/farms)
2. Click unlock wallet
3. if previouss step work Click on approve contract
> On capture approve contact has been clicked
<img width="313" alt="Screenshot 2021-03-02 at 14 38 04" src="https://user-images.githubusercontent.com/47380500/109656640-edb5e900-7b64-11eb-843d-4970c16a0497.png">

Here the console (network tab):

<img width="1141" alt="Screenshot 2021-03-02 at 14 40 44" src="https://user-images.githubusercontent.com/47380500/109656988-49807200-7b65-11eb-9aed-ea88b8c0c009.png">

5. Approve contract on binance chain wallet extension appear after about 5 min

   ...

**Expected Behavior**

Enter an amount of CAKE and start farm.

**Additional Context**
 - Chrome 88 on Mac OS Big sur 11.2.2
 - Ublock origin sometimes enabled

**Comment by martaGonz** [comment]
I have a similar problem, none of my transactions work with binance wallet (compound, harvest or unstake LP tokens)

**Comment by bogdanIuga** [comment]
any updates? happens the same when I try to deposit CAKE.

Brave browser

![image](https://user-images.githubusercontent.com/26706013/111631411-09272200-87fc-11eb-8378-e5e2784a5d0c.png)

**Comment by aaronash** [comment]
People seem to have been having similar issues with the Binance wallet, do you have the same issue with Metamask?

**Comment by bogdanIuga** [comment]
> People seem to have been having similar issues with the Binance wallet, do you have the same issue with Metamask?

works ok with metamask for me

**Comment by aaronash** [comment]
It sounds like this could be a wallet issue rather than pancake - I believe all wallets communicate over the same interface

**Comment by RabbitDoge** [comment]
does anyone still have this problem ?

**Comment by RabbitDoge** [comment]
No update so I close, feel free to reopen is the problem persists
