### ISSUE TITLE
[Bounty] Add link to add token to Metamask in Pool card details

### ISSUE THREAD

**Issue by Chef-Chungus** [pancakeswap/pancake-frontend#584]
Reward: $150 USD in CAKE

**Description:**
Add "Add {Token name} to MetaMask" to the details section of the Pool card.
We may need to add the earn token contract address to `src/config/constants/pools.ts` in order to make this work. 

**Important notes:**
MUST BE THE EARNING TOKEN, NOT THE STAKING TOKEN.

**Resources:**
Metamask Docs: https://docs.metamask.io/guide/registering-your-token.html#code-free-example
![image](https://user-images.githubusercontent.com/71833681/110076863-85674180-7dc8-11eb-9c56-2ad324c984d1.png)

**Comment by rickmort** [comment]
hey! I'm working on this issue =)

**Comment by Tomcat88** [comment]
Working on it!

Questions:

- According to the MetaMask doc an url must be provided for the token icon, it is optional (a placeholder will be showed), is it ok if i leave it optional in the PoolConfig type?

**Comment by Tomcat88** [comment]
Ah it seems that @rickmort was faster than me :)

**Comment by josemtm** [comment]
im working on it but it will some changes in the pool config interface like you said chef

**Comment by Chef-Chungus** [comment]
approved - @rickmort's PR #593. Bounty to go to RickMort
