### ISSUE TITLE
After rejecting the wallet connect request by clicking close button, It cannot be shown again until restart

### ISSUE THREAD

**Issue by memoyil** [pancakeswap/pancake-frontend#594]
**Bug Description**
After rejecting the wallet connect request by clicking close button. It cannot be shown again until restart in PC

**Steps to Reproduce**

1. Click Connect
2. Click Wallet Connect
3. Click close button without using qr
4. See User rejected popup
5. Then try to click WalletConnect again, you will see nothing happens
6. After restart the page, first thing that you would see is the qr code strangely.

**Expected Behavior**
A consistent behaviour that everytime I should see the wallet connect qr code.

**Additional Context**
It is reproducible in pc

**Comment by chokosunny** [comment]
Maybe the problem is due to this:
https://docs.metamask.io/guide/provider-migration.html#replacing-window-web3
 ?

**Comment by RabbitDoge** [comment]
> Maybe the problem is due to this:
> https://docs.metamask.io/guide/provider-migration.html#replacing-window-web3
> ?

We don't use window.web3
