### ISSUE TITLE
Unnecessary trade checks with loop

### ISSUE THREAD

**Issue by nonseodion** [pancakeswap/pancake-frontend#5956]
The [useTradeExactIn](https://github.com/pancakeswap/pancake-frontend/blob/0951de4607ba239190fa543b1113914465673fc1/apps/web/src/hooks/Trades.ts#L98) and [useTradeExactOut](https://github.com/pancakeswap/pancake-frontend/blob/0951de4607ba239190fa543b1113914465673fc1/apps/web/src/hooks/Trades.ts#L135) functions use a loop to check for best trades from 1 to a max of 3 hops using `Trade.bestTradeExactIn()`, and `Trade.bestTradeExactOut()` for each iteration. The first and second iterations consider the same trades as the third iteration. So doing only the third iteration i.e 3 hops without the loop should cover checking for all 1, 2, and 3 trade hops. 

There's a [check](https://github.com/pancakeswap/pancake-frontend/blob/0951de4607ba239190fa543b1113914465673fc1/apps/web/src/hooks/Trades.ts#L157) which I assume is the reason why there's an iteration in the first place, to ensure the best trade from a current iteration must have a better execution price of at least 50 BIPS(pips) higher than the current best trade with a lesser number of hops. I don't see why it's needed considering the 50 BIPS check is really low.

PS: If this is a valid issue I can help with the PR.

**Comment by nonseodion** [comment]
@chef-jojo can this be considered a legitimate issue?

**Comment by chef-jojo** [comment]
Yeah it is. The loop seems unnecessary, feel free to open a PR 👍

**Comment by nonseodion** [comment]
Opened a pr [here](https://github.com/pancakeswap/pancake-frontend/pull/6190)
