### ISSUE TITLE
install on localhost but cant run on testnet

### ISSUE THREAD

**Issue by EricGerbers** [pancakeswap/pancake-frontend#599]
when I clone to my pc, install and run in testnet, Farms functions not work. I cant Approve LP

this is my config:
1) in **.env.development**
REACT_APP_NODE_1 = "https://data-seed-prebsc-1-s1.binance.org:8545"
REACT_APP_NODE_2 = "https://data-seed-prebsc-2-s1.binance.org:8545"
REACT_APP_NODE_3 = "https://data-seed-prebsc-1-s2.binance.org:8545"

2) config Metamask run with BSC Testnet and ready have some BNB token

Please let me know why ? I want research this projects.
Thanks so much.

**Comment by hannawaffle** [comment]
Don't forget to also change the chain id

Where it says

```
REACT_APP_CHAIN_ID = "56"
```

Use the one from the docs
https://docs.binance.org/smart-chain/developer/rpc.html#testnetchainid-0x61-97-in-decimal

**Comment by EricGerbers** [comment]
Yes, I was change to 97

**Comment by EricGerbers** [comment]
and I see in file **src/state/farms/fetchFarms.ts** line 72
this code have an error but I dont know why.

![image](https://user-images.githubusercontent.com/8712206/110318289-e3518e80-803f-11eb-97b7-3b27f62c462f.png)

**Comment by RabbitDoge** [comment]
A lot of contract don't have a testnet address , check the config files
