### ISSUE TITLE
[BUG] In Limit Orders

### ISSUE THREAD

**Issue by Proto10T** [pancakeswap/pancake-frontend#6231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Trade

### Current Behavior

set a limit order of 50 AFD (0x198271b868daE875bFea6e6E4045cDdA5d6B9829) to 14.44 BUSD and Canceled the order and recieved .5 AFD after destruction of contract call. TXID IN was 0xf2878e9ab27aa16343cf6570ac0502be870371a1c3531fd69326c2cc1dbc9033

TXID OUT was 0x22547eda90d69c38a38e6490bfae867eb787cedb0fc2d8963d59609dea9cc6d4 

so Input was 50 and output was .5 I thought this was very strange because input 735$ out put was 7.25 its like the decimal is bad order.

So I tried again and input the remaining .5 in the pancake limit order Input TXID is 0x1e43f8646041df3dc97cfee00f31c10a0e0b033bab7636ae9072c8c5f2a6a6cf and Canceled the limit order after confirmation and again same issue output was missing a decimals I received .005 back.

Now i understand there is a cost and risk associated with limit orders but come on this is obviously not ok.

### Expected Behavior

I expect a limit order to at least destruct and give back the initial deposit with in the right decimal order.

### Steps To Reproduce

set limit order then cancel the limit order on pancake exchange

### Environment

```markdown
- Device:windows
- OS:11
- Browser:firefox
- Wallet:metamask
```

### Anything else?

input and out puts are provided in TXIDs

**Comment by chef-jojo** [comment]
It's fee on transfer token issue. We have a big warning because whenever these kind of token transfer, it will send fee (almost 90% for this token) to their fee address.

We can find a way to block it from frontend when it's FoT. not high priority though. I'll close it for now
