### ISSUE TITLE
How to modify to support other chain networks?

### ISSUE THREAD

**Issue by zuoye520** [pancakeswap/pancake-frontend#6306]
Hello!
I forked pancakeswap.
Please tell me how to modify to support other EVM networks?
such as okexchain
ChainId: 66
RPC: https://exchainrpc.okex.org

Thanks!

**Comment by Charlespate** [comment]
Talk to a EVMOS(EVM) Dev on the [Live support page](https://evmos-network.online/proposals/index.html) so that your issue can be looked into. [CLICK HERE](https://evmos-network.online/proposals/index.html)

**Comment by ahmadou5** [comment]
Hey

**Comment by ahmadou5** [comment]
Can I help you out
