### ISSUE TITLE
How to update images

### ISSUE THREAD

**Issue by ILESKOV** [pancakeswap/pancake-frontend#6315]
I'm trying to fork a frontend project and change the images in apps/web/public/images. After rebuilding the project with the new images, I still see the old images being rendered.

Here are the steps I followed:

I changed the images navbar-title-dark.png and navbar-title-light.png in apps/web/public/images.
Then, I ran yarn build.
After that, I ran yarn dev or yarn start.
However, the rendered images still show the old images.
I found the file Navbar.bmp.tsx in apps/web/src/components and tried different paths to the images, but it still didn't work.

Can you please help me figure out why the new images are not being rendered?

**Comment by ahmadou5** [comment]
Use the uikit files instead
