### ISSUE TITLE
Can't compound in cake pool, wallet shows insufficient balance while funds are sufficient.

### ISSUE THREAD

**Issue by erlandvr** [pancakeswap/pancake-frontend#646]
**Bug Description**
A clear and concise description of the bug.

**Steps to Reproduce**

1. Go to Pools
2. Click on compound in the cake pool (while having earned some cake) 
3. Binance chain wallet opens after long wait, but says funds are  insufficient while I have sufficient funds. 
note: When exchanging tokens or coins I don't get the insufficient balance notice. 

**Expected Behaviour**
Binance chain wallet doesn't show insufficient funds when funds are sufficient.  

**Additional Context**
browser: Chrome, Version 88.0.4324.192 (Official Build) (x86_64)
<img width="357" alt="Screen Shot 2021-03-11 at 21 01 23" src="https://user-images.githubusercontent.com/36692058/110851200-05057c80-82b1-11eb-9ee5-c4dff06ace99.png">
<img width="365" alt="Screen Shot 2021-03-11 at 21 01 43" src="https://user-images.githubusercontent.com/36692058/110851210-0767d680-82b1-11eb-8841-bbab25edcf39.png">

**Comment by memoyil** [comment]
Are you doing your swap operations from pancake website or directly from wallet?

**Comment by bogdanIuga** [comment]
**Issue 1:** 
1. go to pools
2. cake pool -> click stake cake
3. select amount
4. click "Confirm"

Expected: The Binance wallet to open to confirm the transaction
Actual: Nothing happens, it is "pending confirmation"  for a very long time, and no popup after that.

**Issue 2:** I also had the issue with "Insufficient funds", even though there are enough BNB founds in my wallet. 
**Issue 3:** On the exchange page, it says I have no founds at all, and also it doesn't recognize my profile picture. photo attached
**Issue 4:** Sometimes, if I refresh the page, I get the error "No BSC provider was found on window.BinanceChain."

![pancakeswap 1](https://user-images.githubusercontent.com/26706013/110910478-12a31c80-831a-11eb-9f67-e8d2eed6f019.jpg)
![github2](https://user-images.githubusercontent.com/26706013/110910483-133bb300-831a-11eb-9da4-1bfca6c61266.jpg)
![github3](https://user-images.githubusercontent.com/26706013/110910485-133bb300-831a-11eb-82ce-94ffcaf99827.jpg)

**Comment by erlandvr** [comment]
> Are you doing your swap operations from pancake website or directly from wallet?

From the pancake website.

**Comment by erlandvr** [comment]
I've tried updating my extensions but no improvement.
Binance Chain wallet version: 1.135.3
![image](https://user-images.githubusercontent.com/36692058/110923662-6cf3ab80-8321-11eb-8786-e6d674615929.png)

**Comment by erlandvr** [comment]
I've tried deleting and re-installing my binance chain wallet in chrome, nothing changed. :(

**Comment by erlandvr** [comment]
I can confirm that harvesting from the farm is no issue. So the issue is only present in the pool.

**Comment by erlandvr** [comment]
I have managed to resolve the issue, apparently my funds were still too low. This while the transaction fee was only 0.001 BNB and my funds were 0.06 BNB.

**Comment by erlandvr** [comment]
Today, even with my higher funds which made it work again this weekend. The insufficient funds behaviour is back, so I re-opened the bug.

**Comment by erlandvr** [comment]
Hello it's me again :p 
I have finally decided to copy my bsc wallet into a Metamask wallet. This wallet seems to respond faster and also no issue with on the insufficient funds part.

**Comment by problemobro** [comment]
Hello I have the same issue it is only in /pools

**Comment by problemobro** [comment]
> Hello it's me again :p
> I have finally decided to copy my bsc wallet into a Metamask wallet. This wallet seems to respond faster and also no issue with on the insufficient funds part.

I did the same and with metamask there are no problems. Thanks bro!

**Comment by memoyil** [comment]
@Chef-Chungus we can close this issue

**Comment by ChefNina** [comment]
Thanks @memoyil, let me close this.
