### ISSUE TITLE
Unable To Find Route on Existing Liquidity  <One WAy SWAP only>

### ISSUE THREAD

**Issue by sandwizard** [pancakeswap/pancake-frontend#6525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Trade

### Current Behavior

An imported Token  0x37Ac5F3bfd18a164Fc6cF0f0f0ECD334D9179d57 VPK ,
swap FROM BUSD > VPK cannot Find Route to TRADE even Though Sufficient Liquidity Exist,
Where As SWAP From VPK TO BUSD is able to Find THE ROUTE, after recent updated issue arose
 A Similar Contract Byte Code BTL has No issues 0x708955Db0d4c52FFBf9AA34aF7f3CA8bf07390a8
SWAP :BUSD > VPK goes through on direct contract interaction and Dex Aggregrators
VPK> BUSD
<img width="290" alt="Screenshot 2023-04-06 181323" src="https://user-images.githubusercontent.com/35904512/230375661-359c102d-f4eb-41df-b92b-e8a4007a31ee.png">

BUSD > VPK
<img width="283" alt="image" src="https://user-images.githubusercontent.com/35904512/230375826-c64bb8ba-90e8-4c97-ab30-66b2078fe4a8.png">

on the router reserves are adequate
<img width="594" alt="image" src="https://user-images.githubusercontent.com/35904512/230376405-df8907be-f2a4-4aea-ae91-bba70ff980d2.png">

### Expected Behavior

SWAP From Both BUSD TO VPK and VPK to BUSD without Issues

### Steps To Reproduce

1. import VPK token to token list on PancakeSwap.finance 
2. set trade from BUSD TO VPK 
3. clear cache with ctrl + shift + R
4. enter  BUSD amount

### Environment

```markdown
- Device: Windows Surface Laptop 4
- OS: Windows 11 Home 
- Browser: Chrome
- Wallet: Metamask
```

**Comment by chefjackson** [comment]
Thanks for the report. Will be fixed in the next release #6528
