### ISSUE TITLE
Lottery past draws search button shows arrows when hover which is not usable

### ISSUE THREAD

**Issue by memoyil** [pancakeswap/pancake-frontend#655]
**Bug Description**
Lottery past draws search button shows arrows underneath when hover

**Steps to Reproduce**

1. Go to lottery
2. Click on past draws
3. Hover search button
4. See arrows underneath which is not usable

**Expected Behavior**
No arrows

**Comment by Chef-Chungus** [comment]
![image](https://user-images.githubusercontent.com/71833681/111032472-bfcb8100-844f-11eb-862f-d40452492fa9.png)
Screenshot for context
