### ISSUE TITLE
How to getMaxAmountOut by using V3?

### ISSUE THREAD

**Issue by icyice80** [pancakeswap/pancake-frontend#6551]
What's the proper way to getRouteResult and maxAmountOut, if only passes inputAmount for tokenA, destinationToken, TradeType.Exact_Input like uniswapV3 does, In uniswapv3 I can initialize AlphaRouter, then call smarter.route with the parameters mentioned above to get the routes and maxAmountOut. Does pancakeSwap v3 provide something similar? thanks.

**Comment by chefjackson** [comment]
Hey sorry for the late reply.

We do have a package for swap quoting, but we're still working on the document. You can refer to the code here
https://github.com/pancakeswap/pancake-frontend/blob/develop/packages/smart-router/evm/v3-router/getBestTrade.ts#L21

**Comment by icyice80** [comment]
thanks, how about the actual swap operation after obtaining the routes info?

**Comment by mosesojero** [comment]
Seen remove stale label

**Comment by chefjackson** [comment]
Sorry for the late reply. Please checkout our smart router usage example for more information https://github.com/pancakeswap/smart-router-example
