### ISSUE TITLE
Site not working - Certificate verification error on site

### ISSUE THREAD

**Issue by rajeevbarde** [pancakeswap/pancake-frontend#663]
**Bug Description**
site not working

![image](https://user-images.githubusercontent.com/6995156/111170744-486e2c80-85ca-11eb-9067-e23a34a2637d.png)

**Comment by Chef-Chungus** [comment]
Please don't access the site right now, the DNS has been hijacked and we are in the process of recovering
https://twitter.com/PancakeSwap/status/1371471934999777281
