### ISSUE TITLE
Existence of bugs and non-implementation of the project

### ISSUE THREAD

**Issue by mohammadhrad** [pancakeswap/pancake-frontend#6696]
Hello

System OS: Linux Ubuntu 22.04
Node: v18.10.0
npm: v8.19.2
Yarn: v1.22.19

Problem:
The yarn command is executed without error.
The yarn dev command encounters an error.
The yarn build and yarn start commands have lines.

Attached files contain project implementation errors:

command yarn dev Error Photo:
https://postimg.cc/XG1CTSF6

command yarn build Error Photo:
https://postimg.cc/KR6sdCrT

command yarn start Error Photo:
https://postimg.cc/HckSwmHq

How are these things solved?
It should be mentioned that the Ubuntu version 20.04 has been retested and contains the same errors.

**Comment by chef-jojo** [comment]
duplicated #6696
