### ISSUE TITLE
[BUG On The Run Project] 

### ISSUE THREAD

**Issue by mohammadhrad** [pancakeswap/pancake-frontend#6704]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

Hello

System OS: Linux Ubuntu 22.04
Node: v18.13.0
npm: v8.19.3
Yarn: v1.22.19

Problem:
The yarn dev command encounters an error.
The yarn build and yarn start commands have lines.
**Even in this command yarn test:ci and yarn test:config, errors are evident.**

please guide me!

### Expected Behavior

We also tweaked the operating system and even looked at different versions of Node. These errors were not resolved.
It is necessary to check and fix the problem

### Steps To Reproduce

Run Command: yarn
Result: It runs without any problem and is finished
_________
Run Command: yarn dev
Result: It warns about the packages/wagmi folder and does not allow the process to continue.
_________
Run Command: yarn start
Result: It warns about the apps/web folder and does not allow the process to continue.
_________
It should be noted that there are errors even in the test commands.

### Environment

```markdown
- Device:Linux Ubuntu 
- OS: 22.04 and Ubuntu 20
- Browser: N/A
- Wallet: N/A
```

### Anything else?

Attached files contain project implementation errors:

Error Command yarn dev:
https://postimg.cc/SXrGqCMx

Error Command test:ci:
https://postimg.cc/342Ydr3N

Error Command test:config:
https://postimg.cc/WFct9H3D

**Comment by mohammadhrad** [comment]
This disturbance of versions and code inside this project is not normal at all:
https://postimg.cc/JHWqHcTG
and :
https://postimg.cc/V5DgkMqL

This disturbance of versions and code inside this project is not normal at all...
@chef-jojo
@memoyil 
@ChefMomota 
@Woody810

**Comment by chef-jojo** [comment]
the dev 137 exit code looks like it's because out of memory. 

Cannot find any useful error message from other command

**Comment by mohammadhrad** [comment]
What does the web error and exit code 1 mean?
Command yarn start error photo:
https://postimg.cc/HckSwmHq

The descriptions included for implementation are very short and concise.
If these are updated and are a detailed and complete guide, everyone will be helped and many additional questions will be avoided.

**Comment by mohammadhrad** [comment]
Yes, it gives the error of not finding .next 
This project is installed on Apache localhost Ubuntu

How can this error be fixed? I have been trying for a long time, but I did not get a good result

**Comment by mohammadhrad** [comment]
one question
Where is the config file in which the port of the project is specified? @chef-jojo

**Comment by mohammadhrad** [comment]
This error is definitely related to the project.
There is a lot of memory. Error code 1 should not be given.
The error that exists: command failed

error photo:
https://postimg.cc/grNDdZYB

@chef-jojo

**Comment by mohammadhrad** [comment]
Another error that was detected:
https://postimg.cc/f3RT9yty
