### ISSUE TITLE
Remove liquidity pancakeswap This Transaction would fail

### ISSUE THREAD

**Issue by CryptoAgents** [pancakeswap/pancake-frontend#6706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Trade

### Current Behavior

![Screenshot_9](https://user-images.githubusercontent.com/131606394/233851507-42906c3c-70f5-4fb2-a8f5-6736aea8e2f8.png)

**Hello, when I try to remove liquidity from panecakeswap I get an error: this transaction would fail.**

Tried to reset via metamask. Still nothing helped.

Is my liquidity stuck on panecakeswap?

Remove liquidity Pancakeswap confirm not working

I will like to provide 15% of Liquidity as bounty for someone who can help me

### Expected Behavior

 remove liquidity panecakeswap

### Steps To Reproduce

1. Connect Metamask on pancakeswap
2. Go to https://exchange.pancakeswap.finance/#/pool > Your Liquidity > Remove > 100% > Approve > Sign in Metamask > Remove > Confirm

### Environment

```markdown
- Device: PC
- OS: Windows
- Browser: Chrome
- Wallet: Metamask
```

**Comment by mohammadhrad** [comment]
The liquidity lock inside the exchange depends on the type of token encoding that you intend to withdraw from its pool.
The JSON RBC error is related to your Metamask wallet.

**Comment by Altanb21** [comment]
Increase gas price

**Comment by CryptoAgents** [comment]
Recently encountered the same problem, this transaction would fail, found a video in google - https://www.youtube.com/watch?v=-AipX1RBt7w, it helped me
