### ISSUE TITLE
[BUG] computePoolAddress returns a different address compared to the one from PancakeV3Factory#getPool

### ISSUE THREAD

**Issue by b1acKr0se** [pancakeswap/pancake-frontend#6790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Trade

### Current Behavior

Currently, address computed from v3-sdk's `computePoolAddress` is different from address returned by `PancakeV3Factory#getPool`. For example consider this pool:

```
tokenA: 0x152649ea73beab28c5b49b26eb48f7ead6d4c898
tokenB: 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
fee: 2500
```

`PancakeV3Factory#getPool` returns `0x517F451b0A9E1b87Dc0Ae98A05Ee033C3310F046` (valid CAKE pool)
`computePoolAddress` returns `0x53D6C61B54435eb7Ed94c367dBE5e0decA2140EC` (EOA)

I have written a simple contract to compute the address onchain using `PoolAddress.sol` from [`QuoterV2` contract by PancakeSwap](https://etherscan.io/address/0xb048bbc1ee6b733fffcfb9e9cef7375518e25997#code) and it returns the invalid address `0x53D6C61B54435eb7Ed94c367dBE5e0decA2140EC` as well.

<details>
  <summary>PoolAddressTest.sol</summary>

```solidity
// SPDX-License-Identifier: MIT

pragma solidity =0.7.6;

/// @title Provides functions for deriving a pool address from the factory, tokens, and the fee
library PoolAddress {
    bytes32 internal constant POOL_INIT_CODE_HASH =
        0x6ce8eb472fa82df5469c6ab6d485f17c3ad13c8cd7af59b3d4a8026c5ce0f7e2;

    /// @notice The identifying key of the pool
    struct PoolKey {
        address token0;
        address token1;
        uint24 fee;
    }

    /// @notice Returns PoolKey: the ordered tokens with the matched fee levels
    /// @param tokenA The first token of a pool, unsorted
    /// @param tokenB The second token of a pool, unsorted
    /// @param fee The fee level of the pool
    /// @return Poolkey The pool details with ordered token0 and token1 assignments
    function getPoolKey(
        address tokenA,
        address tokenB,
        uint24 fee
    ) internal pure returns (PoolKey memory) {
        if (tokenA > tokenB) (tokenA, tokenB) = (tokenB, tokenA);
        return PoolKey({token0: tokenA, token1: tokenB, fee: fee});
    }

    /// @notice Deterministically computes the pool address given the factory and PoolKey
    /// @param deployer The PancakeSwap V3 deployer contract address
    /// @param key The PoolKey
    /// @return pool The contract address of the V3 pool
    function computeAddress(address deployer, PoolKey memory key)
        internal
        pure
        returns (address pool)
    {
        require(key.token0 < key.token1);
        pool = address(
            uint256(
                keccak256(
                    abi.encodePacked(
                        hex"ff",
                        deployer,
                        keccak256(abi.encode(key.token0, key.token1, key.fee)),
                        POOL_INIT_CODE_HASH
                    )
                )
            )
        );
    }
}

contract PoolAddressTest {
    function computePoolAddress(
        address factory,
        address tokenIn,
        address tokenOut,
        uint24 fee
    ) external view returns (address pool) {
        pool = PoolAddress.computeAddress(
            factory,
            PoolAddress.getPoolKey(tokenIn, tokenOut, fee)
        );
    }
}
```
</details>

I wonder if the actual deployed code of `PancakeV3Pool` was changed and the bytecode no longer matched the provided `POOL_INIT_CODE_HASH`? Or I simply made a mistake somewhere?

### Expected Behavior

Pool address returned from ` PancakeV3Factory#getPool` matched the one computed by `computePoolAddress`

### Steps To Reproduce

1. `computePoolAddress` code:

```typescript
computePoolAddress({
  deployerAddress: "0x0bfbcf9fa4f9c56b0f40a671ad40e0805a091865",
  tokenA: new Token(
    1,
    "0x152649ea73beab28c5b49b26eb48f7ead6d4c898",
    18,
    "CAKE",
    "CAKE"
  ),
  tokenB: new Token(
    1,
    "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
    18,
    "WETH",
    "Wrapped Ether"
  ),
  fee: 2500,
})
```

2. Get pool address from PancakeV3Factory, with above configs https://etherscan.io/address/0x0BFbCF9fa4f9C56B0F40a671Ad40E0805A091865#readContract

3. Compare the 2 addresses

### Environment

```markdown
Doesn't matter.
```

**Comment by b1acKr0se** [comment]
I figured it out. From the [PancakeFactoryV3](https://etherscan.io/address/0x0BFbCF9fa4f9C56B0F40a671Ad40E0805A091865#code) code on etherscan, the deployer of the pool is not the factory itself like UniswapV3, but is a separate address (`poolDeployer`):

```solidity
 pool = IPancakeV3PoolDeployer(poolDeployer).deploy(address(this), token0, token1, fee, tickSpacing);
```

Using this address in the `computePoolAddress` function yields the correct pool address.

Is there any plan to upload the smart contracts code to Github? It's quite hard to navigate and debug on etherscan.

**Comment by chef-jojo** [comment]
should be open 
https://github.com/pancakeswap/pancake-v3-contracts

**Comment by ludekvodicka** [comment]
@b1acKr0se Thanks very much for sharing the solution. After two hours of searching through contracts and google I finally solved it thanks to your post.

**Comment by b1acKr0se** [comment]
@ludekvodicka You are welcome, I'm glad it helped :)
