### ISSUE TITLE
[BUG] PancakeSwap Safe App is no longer working

### ISSUE THREAD

**Issue by troggy** [pancakeswap/pancake-frontend#6899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

Pancakeswap Safe App which was previously working if added on https://app.safe.global/apps?safe= is no longer working. Pancake frontend fails to load completely in Safe's iframe being blocked by browser

### Expected Behavior

PancakeSwap Safe App continues to work as it used to do recently.

### Steps To Reproduce

1. Go to https://app.safe.global/
2. Make sure you have connected wallet (Metamask or other)
3. Create a safe or use the existing one
4. Go to https://app.safe.global/apps
5. Find Pancake Swap in the list of apps, click on it
6. Click "Open Safe App" in the side drawer
7. Accept Disclaimer
8. Notice that the page inside the Safe frame failed to load

### Environment

```markdown
- Device: 
- OS: Ventura 13.3 / Windows 10
- Browser: Chrome / Firefox / Brave
- Wallet: Tally Ho / Metamask
```

### Anything else?

I believe it was broken in this commit which adds `X-Frame-Options: DENY` as Safe uses iframe to show apps:
https://github.com/pancakeswap/pancake-frontend/commit/310b4a1c6a23b87439ba27b52954cd959510b2bd#diff-6aa78b1c0e55dbfe59ebe097a8976bcc007627796cc9e1cb854531e0de043047R18

**Comment by chefjackson** [comment]
Hey thanks for the report. We've whitelisted safe app domain and this issue should be fixed now.

For more details pls refer to #6912
