### ISSUE TITLE
[BUG] Cannot harvest from old finished farm

### ISSUE THREAD

**Issue by troggy** [pancakeswap/pancake-frontend#7040]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Farms

### Current Behavior

I have a BTC-BNB Farm which is owned by multisig on Gnosis Safe. It used to work fine for me.
Yesterday when I click Harvest button on the farms page (https://pancakeswap.finance/farms/history) to get the rewards I got an error "An unknown RPC error occured". No transaction created.

If I click "Harvest" on the main page the empty multicall transaction was created and executed. The transaction was empty, no tokens transferred and the main page kept showing my rewards.

### Expected Behavior

When I click Harvest on finished farm, the transaction claiming my CAKE rewards should be created.

### Steps To Reproduce

I'm not sure how exactly to reproduce it as it is my production setup.

I had the following: LP tokens for BTC-BNB pool staked in a farm which is finished.

### Environment

```markdown
- Device: Macbook Air M1
- OS: Ventura
- Browser: Brave
- Wallet: Taho / Metamask
```

### Anything else?

The bug was introduced in one of the recent changes to the frontend as I was able to create and submit my transaction (and get my CAKE rewards) with the older version of the frontend running locally. The revision of the frontend that worked for me is 6b071303d673cb1f4bbe39016f1a9c730c5b7685, but I haven't checked the latter commits.

**Comment by chef-jojo** [comment]
tracking on https://github.com/safe-global/safe-apps-sdk/issues/480

**Comment by troggy** [comment]
still relevant

**Comment by Anup9444** [comment]
I am still getting this error , 
![image](https://github.com/rainbow-me/rainbowkit/assets/110972959/25e7056d-b41e-4861-b32a-1dfea4db975f)
