### ISSUE TITLE
[BUG] Wallet Connect v2 Cannot sendTransaction as gasLimit and gasPrice is not being sent

### ISSUE THREAD

**Issue by pavs94** [pancakeswap/pancake-frontend#7171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Trade

### Current Behavior

Swap function for Pancakeswap is not working with Wallet Connect v2. 
This is because the payload in sendTransaction is:
```
{
"data": "0x5ae401d.....xxxx",
"gas": "0x2bab0",
"to": "0x13f4EA83D0bd40E75C8222255bc855a974568Dd4",
"value": "0x2386f26fc10000"
}
```

### Expected Behavior

The expected payload is:

```
{ "from": "0xeC65818Ff0F8b071e587A0bBDBecC94DE739B6Ec", "to": "0xeC65818Ff0F8b071e587A0bBDBecC94DE739B6Ec", "data": "0x", "nonce": "0x36", "gasPrice": "0x035458af00", "gasLimit": "0x5208", "value": "0x00" }
```

### Steps To Reproduce

1. Connect to a wallet that has implemented Wallet Connect v2
2. Create a swap on Pancakeswap v2
3. Check the swap function payload being sent 
4. Swap does not work as Wallet Connect v2 transactions are being rejected.

### Environment

```markdown
- Device: Macbook Pro
- OS: MacOS Ventura 13.4
- Browser: Chrome
- Wallet: WalletConnect v2
```

**Comment by pavs94** [comment]
I have changed "gas" to "gasLimit" and it works

**Comment by chef-jojo** [comment]
which wallet you are using?
