### ISSUE TITLE
[BUG] Liquidity modal not showing full elements 

### ISSUE THREAD

**Issue by zubeirom** [pancakeswap/pancake-frontend#7223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Trade

### Current Behavior

![image](https://github.com/pancakeswap/pancake-frontend/assets/38444073/b5a8b263-1a2c-45af-ae34-d1877ea26dbf)

### Expected Behavior

To see all elements and inputs

### Steps To Reproduce

1. Go to liquidity
2. Select a token that does not have a pool

### Environment

```markdown
- Device: Macbook air
- OS: MacOS
- Browser: MS Edge
- Wallet:
```

**Comment by lyzergic** [comment]
Can I take this one ?

**Comment by chef-jojo** [comment]
Hey @lyzergic yes sure, feel free to take it

@zubeirom can you share the zoo address to help reproduce?

**Comment by lyzergic** [comment]
Environment

```
- Device: Macbook Pro
- OS: MacOS
- Browser: Ms Edge
- Wallet: 
```

Unable to reproduce.

<img width="1285" alt="Screenshot 2023-07-14 at 14 42 55" src="https://github.com/pancakeswap/pancake-frontend/assets/45937542/b017f79c-1bdc-48ea-b756-03c7743a59de">

**Comment by zubeirom** [comment]
Closing this issue, when the bug appeared I was using the MS Edge Dev Version, which updates every week. The actual MS Edge Stable Release Version doesn't have this bug. Sorry for the inconvenience!
