### ISSUE TITLE
[QA] Pool Cards rework

### ISSUE THREAD

**Issue by Chef-Chungus** [pancakeswap/pancake-frontend#732]
QA for - [WIP] Pool cards updates #629 

[  ] Earned token does not show USD value equivalent - Need to use price from API to calculate this information. All token prices should be available. If you have questions about how to obtain these, please consult @RabbitDoge 
![image](https://user-images.githubusercontent.com/71833681/112267096-4c7c0780-8cb8-11eb-9ae9-6a5f5a532c7d.png)

[   ] Update `Finish` to `End Block` and sort by the amount of remaining end blocks descending.
![image](https://user-images.githubusercontent.com/71833681/112267195-6fa6b700-8cb8-11eb-86b4-3cd8a3e64dc3.png)

[  ] Staked only toggle doesn't work for finished pools (also farms).
![image](https://user-images.githubusercontent.com/71833681/112267546-f8255780-8cb8-11eb-95db-211d9a50dfbc.png)

[  ] Harvesting should be based on the earningToken, not the stakingToken
![image](https://user-images.githubusercontent.com/71833681/112269199-666b1980-8cbb-11eb-853e-05ff00e454a6.png)

[  ] Unable to test, but flagging based on the above bug. Staking should be based on the stakingToken and the maxStaking amount (if defined), please confirm this is the current behaviour.

[  ] Cake in wallet, but getting "no cake balance" error.
 - Side note, this check should be done not only on cake, but specifically on the stakingToken balance in the wallet. As some pools do not use CAKE to stake
![image](https://user-images.githubusercontent.com/71833681/112269636-fa3ce580-8cbb-11eb-9c06-0877d97b2148.png)

**Comment by cbunnydev** [comment]
@Chef-Chungus 

Issues posted above are resolved on the pull request.

https://github.com/pancakeswap/pancake-frontend/pull/629

**Comment by Chef-Chungus** [comment]
1. The Percentage attached to the bunny is placed incorrectly
![image](https://user-images.githubusercontent.com/71833681/112800267-664b8f00-90aa-11eb-8067-989a989f02ed.png)

2. The Icon in the `Confirming` state is the wrong color
![image](https://user-images.githubusercontent.com/71833681/112800329-75cad800-90aa-11eb-8412-290e866f6b7f.png)

3. spacing between cards should be 32px, effective max body to be 1120 which is 1200-40px padding on each side
![image](https://user-images.githubusercontent.com/71833681/112800348-7ebba980-90aa-11eb-8aee-937a0b535304.png)

4. 
![image](https://user-images.githubusercontent.com/71833681/112800430-9a26b480-90aa-11eb-9485-31971effe6a8.png)

5. Sort by APR does not work at all
![image](https://user-images.githubusercontent.com/71833681/112800969-4ec0d600-90ab-11eb-9c1d-79354bc98f24.png)

6. Total Staked should be stakingTokenName
![image](https://user-images.githubusercontent.com/71833681/112801152-83349200-90ab-11eb-917a-f39d00aa7ac1.png)

**Comment by cbunnydev** [comment]
Issues resolved

Need a pr in ui kit to get merged in.

https://github.com/pancakeswap/pancake-toolkit/pull/36/files

**Comment by ChefKai** [comment]
This is live as of today, closing.
