### ISSUE TITLE
[Feature Request] Centralization risk of smart-router

### ISSUE THREAD

**Issue by simone1999** [pancakeswap/pancake-frontend#7500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem you are facing?

Risk of centralization due to smart-router not working anymore when subgraph endpoint is down

### Describe the solution you'd like

Add an fallback for the router that fetches all data from on chain. These routing results will very likely be less advanced, but way better to have a less advanced routing as fallback than trading completely halting due to The Graph issues. Especially as PancakeSwap wants to expand to more chains, making The Graph an optional routing improvement instead of an absolute necessity for the platform to be usable seems wise.

### How does this feature benefit PancakeSwap users and CAKE holders?

reduces risk of PancakeSwap becoming completely unusable for a period of time.

**Comment by simone1999** [comment]
even the V2 router now is dependant on the Graph.

**Comment by chefjackson** [comment]
Hey thanks for your insight. Actually we do have fallback for smart router so we're not completely relying services from the graph. Pls refer to https://github.com/pancakeswap/pancake-frontend/blob/develop/packages/smart-router/evm/v3-router/providers/poolProviders/getV3CandidatePools.ts#L130 for more details

**Comment by e4coder** [comment]
When the subgraph endpoint becomes unusable, would there be any performance issue with the router?
How big of difference of latency is there between "onChain" fallback and the subgraph endpoint?

**Comment by chefjackson** [comment]
There won't be performance issue regarding the fallback endpoint, as we have edge level of cache for that.

A simple way to verify is to block the subgraph domain on your end and try out the swap

**Comment by simone1999** [comment]
It looks like the fallback is getting the candidate pools from the routing API, which itself uses the subgraph. Is this observation incorrect?

**Comment by chefjackson** [comment]
> It looks like the fallback is getting the candidate pools from the routing API, which itself uses the subgraph. Is this observation incorrect?

The routing API doesn't rely on subgraph directly. It reads data from its own persistent storage. So it will continue to provide service even if subgraph is down

**Comment by chefjackson** [comment]
Open to discussion if there's any questions regarding this topic. Close for now
