### ISSUE TITLE
[BUG] pnpm Build fails with permission Error: EPERM: operation not permitted

### ISSUE THREAD

**Issue by zorglob21** [pancakeswap/pancake-frontend#7729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Trade

### Current Behavior

Trying to clone then follow instructions:
run pnpm i (ok)
run pnpm dev (ok)
(in another terminal) run pnpm build : works well until it fails with
`web:build: uncaughtException [Error: EPERM: operation not permitted, open 'C:\Users\USERNAME\Desktop\front\pancake-frontend\apps\web\.next\trace'] {
web:build:   errno: -4048,
web:build:   code: 'EPERM',
web:build:   syscall: 'open',
web:build:   path: 'C:\\Users\\USERNAME\\Desktop\\front\\pancake-frontend\\apps\\web\\.next\\trace'
web:build: }
web:build:  ELIFECYCLE  Command failed with exit code 1.
web:build: ERROR: command finished with error: command (C:\Users\USERNAME\Desktop\front\pancake-frontend\apps\web) pnpm run build exited (1)
command (C:\Users\USERNAME\Desktop\front\pancake-frontend\apps\web) pnpm run build exited (1)`

### Expected Behavior

Would expect the build to run correctly and be able to deploy (i managed to do this 10 days agos)

### Steps To Reproduce

git clone then run all npmp

### Environment

```markdown
- Device:acer aspire 3 A317
- OS:windows 11
- Browser:
- Wallet:
```

### Anything else?

The trace file in apps/webs/.next/trace canno't be opened or deleted (permissions)

**Comment by chefjackson** [comment]
I think it's an os permission related issue. Close as not related to the codebase
