### ISSUE TITLE
`useConfig` must be used within `WagmiConfig

### ISSUE THREAD

**Issue by albin1212** [pancakeswap/pancake-frontend#7768]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

  packages\wagmi\dist\index.mjs (6:30) @ useNetwork

4 | 
  5 | function useWeb3React() {
> 6 | const { chain } = useNetwork();
    |                            ^
  7 | const { address, connector, isConnected, isConnecting } = useAccount();
  8 | return {
  9 |   chainId: chain == null ? void 0 : chain.id,

### Expected Behavior

Any idea about this to resolve

### Steps To Reproduce

Forked the repo then cloned it and make some changes and pushed to our repo. Then cloned it and trying to run we are getting this error

### Environment

```markdown
- Device:HP
- OS:Windows
- Browser:chrome
- Wallet:Metamask app
```

**Comment by albin1212** [comment]
import { Chain, Connector, useAccount, useNetwork } from 'wagmi'

export function useWeb3React(): {
  chainId: number | undefined
  account: `0x${string}` | null | undefined
  isConnected: boolean
  isConnecting: boolean
  chain: (Chain & { unsupported?: boolean | undefined }) | undefined
  connector: Connector | undefined
} {
  const { chain } = useNetwork()
  const { address, connector, isConnected, isConnecting } = useAccount()

  return {
    chainId: chain?.id,
    account: isConnected ? address : null, // TODO: migrate using `isConnected` instead of account to check wallet auth
    isConnected,
    isConnecting,
    chain,
    connector,
  }
}


entire file which getting this error

**Comment by chefjackson** [comment]
do you have trouble running the original codebase?

**Comment by albin1212** [comment]
no. only on the updated code

**Comment by kiran-bhalerao** [comment]
im also getting the same issue, any solution?

**Comment by chefjackson** [comment]
We've updated the lockfile recently. Please upgrade pnpm to the latest version and try reinstall
