### ISSUE TITLE
[UX] Confusing navigation, `Teams and Profiles`

### ISSUE THREAD

**Issue by kyranjamie** [pancakeswap/pancake-frontend#777]
Hi all, sorry if this isn't the place to share UI feedback but feel this is important.

<details>
<summary>Related UI Screenshot</summary>

![image](https://user-images.githubusercontent.com/1618764/113392622-b326b280-9395-11eb-8104-76471e5b55b8.png)
</details>

While I gather you're trying to attract attention to the _Teams and Profile_ page, it's extremely confusing as the visual weight of this navigation item trumps that of the active page's nav item.

I'd suggest attracting attention to this page in another manner.

**Comment by RabbitDoge** [comment]
@ChefBugs

**Comment by ChefBugs** [comment]
yes aware and agreed

**Comment by Chef-Chungus** [comment]
Resolved yesterday
