### ISSUE TITLE
[BUG] @pancakeswap/smart-router module unsupport esmodule

### ISSUE THREAD

**Issue by yvvw** [pancakeswap/pancake-frontend#7860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

Node.js v18.16.0 
**Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'xxx/node_modules/lodash/flatMap' imported from xxx/node_modules/@pancakeswap/smart-router/dist/evm.mjs** when import `@pancakeswap/smart-router` in esmodule project

```json
// package.json
{
  "name": "example",
  "type": "module",
  "dependencies": {
    "@pancakeswap/smart-router": "^4.8.5"
  }
}
```

```js
// main.mjs
import { SmartRouter } from '@pancakeswap/smart-router/evm'
```

```sh
node main.mjs
```

```sh
// log
node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'xxx/node_modules/lodash/flatMap' imported from xxx/node_modules/@pancakeswap/smart-router/dist/evm.mjs
Did you mean to import lodash/flatMap.js?
    at new NodeError (node:internal/errors:399:5)
    at finalizeResolution (node:internal/modules/esm/resolve:326:11)
    at moduleResolve (node:internal/modules/esm/resolve:945:10)
    at defaultResolve (node:internal/modules/esm/resolve:1153:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v18.16.0
}
```

### Expected Behavior

null

### Steps To Reproduce

null

### Environment

```markdown
null
```

**Comment by chef-jojo** [comment]
I recall have to add .js at the end somehow for lodash subparh🤔 another solution could be fixed by tsconfig. @chefjackson 

Here i added .js at that time was working 

https://github.com/pancakeswap/pancake-frontend/blob/develop/packages/smart-router/evm/v3-router/functions/getBestRouteCombinationByQuotes.ts#L5


Missing .js
https://github.com/pancakeswap/pancake-frontend/blob/develop/packages/smart-router/evm/v3-router/functions/getPairCombinations.ts#L2

**Comment by chefjackson** [comment]
hmm I think it's because of the nodejs esm implementation requires [mandatory file extensions](https://nodejs.org/api/esm.html#mandatory-file-extensions)

**Comment by chefjackson** [comment]
https://github.com/pancakeswap/pancake-frontend/pull/7879

**Comment by chefjackson** [comment]
@yvvw kindly try out the [latest version](https://github.com/pancakeswap/pancake-frontend/releases/tag/%40pancakeswap%2Fsmart-router%404.8.6)
