### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by albin1212** [pancakeswap/pancake-frontend#7991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

I have cloned the repo run pnpm i then run pnpm build. Build is getting failed

web:build: 47:24  Warning: unchecksumed address  address/addr-type
web:build:
web:build: info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
web:build:  ELIFECYCLE  Command failed with exit code 1.
web:build: ERROR: command finished with error: command (C:\projects\accubits\updatedPan\pancake-frontend\apps\web) pnpm run build exited (1)
command (C:\projects\accubits\updatedPan\pancake-frontend\apps\web) pnpm run build exited (1)

 Tasks:    12 successful, 13 total
Cached:    12 cached, 13 total
  Time:    46.911s
Failed:    web#build

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.

### Expected Behavior

build should be success

### Steps To Reproduce

run pnpm build

### Environment

```markdown
- Device:HP
- OS:Windows
- Browser:chrome
- Wallet:Metamask app
```

**Comment by chefjackson** [comment]
could you provide the entire error message?
