### ISSUE TITLE
Expecting Pancake Swap on Mind Smart Chain 

### ISSUE THREAD

**Issue by nnlgsakib** [pancakeswap/pancake-frontend#8043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem you are facing?

.

### Describe the solution you'd like

Dear Pancake Swap Team,

I am Sakib, Chief Developer at Mind Smart Chain. We are considering the deployment of Pancake Swap on our network. Is Pancake Swap interested in exploring this collaboration?

For more details, please visit our website at mindchain.com or explore our mainnet at mainnet.mindscan.info.

Thank you for your consideration.

Best regards,
Sakib

### How does this feature benefit PancakeSwap users and CAKE holders?

.

**Comment by chefjackson** [comment]
Hey pls check out our [business partnership doc](https://docs.pancakeswap.finance/ecosystem-and-partnerships/business-partnerships) for more information
