### ISSUE TITLE
Contact a dev if you need these values.

### ISSUE THREAD

**Issue by devsingh123** [pancakeswap/pancake-frontend#808]
REACT_APP_CROWDIN_APIKEY = ""
REACT_APP_CROWDIN_PROJECTID = ""

**Comment by devsingh123** [comment]
> REACT_APP_CROWDIN_APIKEY = ""
> REACT_APP_CROWDIN_PROJECTID = ""

Do these id required for the installation of App ??

**Comment by Chef-Chungus** [comment]
We are going to be reworking out localization system, so we won't be handing out these keys for now. You won't need them later once we refactor it

**Comment by devsingh123** [comment]
We need features 
Exchange (Trade)
Farms

**Comment by devsingh123** [comment]
Have you completed refactoring the same ?

**Comment by Chef-Chungus** [comment]
the refactoring is in progress. 

You don't need these values to run a copy of the site though.
