### ISSUE TITLE
[BUG] web:dev: Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'projects/pancake-frontend/apps/web/node_modules/@pancakeswap/next-config/dist/withWebSecurityHeaders' imported from /Users/user/Desktop/projects/pancake-frontend/apps/web/next.config.mjs>

### ISSUE THREAD

**Issue by rahulcs1988** [pancakeswap/pancake-frontend#8154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Trade

### Current Behavior

web:dev: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/user/Desktop/projects/pancake-frontend/apps/web/node_modules/@pancakeswap/next-config/dist/withWebSecurityHeaders.js' imported from /Users/user/Desktop/projects/pancake-frontend/apps/web/next.config.mjs
web:dev:     at new NodeError (node:internal/errors:387:5)
web:dev:     at finalizeResolution (node:internal/modules/esm/resolve:330:11)
web:dev:     at moduleResolve (node:internal/modules/esm/resolve:907:10)
web:dev:     at defaultResolve (node:internal/modules/esm/resolve:1115:11)
web:dev:     at nextResolve (node:internal/modules/esm/loader:163:28)
web:dev:     at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
web:dev:     at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
web:dev:     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
web:dev:     at link (node:internal/modules/esm/module_job:75:36) {
web:dev:   type: 'Error',
web:dev:   code: 'ERR_MODULE_NOT_FOUND'
web:dev: }

### Expected Behavior

It should run without error

### Steps To Reproduce

pnpm i and run pnpm dev

### Environment

```markdown
- Device:
- OS:
- Browser:
- Wallet:
```

**Comment by chefjackson** [comment]
`@pancakeswap/next-config` is an internal package, so please make sure you have `pnpm install` run and have the package hard-linked to the node_modules folder under the web application

**Comment by kiran-bhalerao** [comment]
try,
pnpm clean
pnpm i
pnpm build
pnpm dev

**Comment by Solniechniy** [comment]
<img width="830" alt="image" src="https://github.com/pancakeswap/pancake-frontend/assets/26657914/39a6d777-41d7-49b2-ada3-c65cf55cab3e">
<img width="966" alt="image" src="https://github.com/pancakeswap/pancake-frontend/assets/26657914/73101d24-69e4-44f0-b4c3-383f2d41bd27">
<img width="881" alt="image" src="https://github.com/pancakeswap/pancake-frontend/assets/26657914/e5513e04-1239-4f11-bbec-0b306d1cf8ee">

**Comment by truecode112** [comment]
@kiran-bhalerao  Thanks. It worked for me

**Comment by chefjackson** [comment]
@rahulcs1988 hi we've identified the issue and pushed a [fix](https://github.com/pancakeswap/pancake-frontend/commit/ac6ef44db880b1689a0669d82719d58996da3ca1) to the repo. Should be good with the latest develop branch. Sorry for the trouble and thanks for the report!
