### ISSUE TITLE
[BUG] <How to remove V3>

### ISSUE THREAD

**Issue by rahulcs1988** [pancakeswap/pancake-frontend#8163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Trade

### Current Behavior

Currently, we can see V3 in many places across the platform. Is there any way to remove it?

### Expected Behavior

Need to remove V3 from the entire platform

### Steps To Reproduce

Clone the repo, run and navigate to swap, liquidity, etc

### Environment

```markdown
- Device:
- OS:
- Browser:
- Wallet:
```

**Comment by chefjackson** [comment]
sorry it's part of our core feature and we can't remove it
