### ISSUE TITLE
Lottery "You won!" card does not disappear after collection rewards.

### ISSUE THREAD

**Issue by Chef-Cheems** [pancakeswap/pancake-frontend#828]
**Bug Description**
When you collect your lottery prize the "You won!" card does not go away after collection.

**Steps to Reproduce**

1. Go to lottery
2. Win the lottery
3. Collect your prize
4. After transaction is completed and you got your cake - you still see the "You won!" card. Clicking on "Collect" again does nothing.

**Expected Behavior**
After you collected your prize you "You won!" card should disappear (or change to something else).

**Comment by memoyil** [comment]
Win the lottery step makes me happy :)

**Comment by Chef-Cheems** [comment]
Reopening because this just happened again. 🤔

**Comment by memoyil** [comment]
I am checking
