### ISSUE TITLE
Build issue with pnpm dev 

### ISSUE THREAD

**Issue by Jeanclaudech98** [pancakeswap/pancake-frontend#8437]
**Is there an existing issue for this?**
Exact issue no, I have tried the other methods to solve build problems, but mine is different. 

**Current Behavior** 

• Packages in scope: @pancakeswap/chains, @pancakeswap/farms, @pancakeswap/hooks, @pancakeswap/ifos, @pancakeswap/localization, @pancakeswap/multicall, @pancakeswap/next-config, @pancakeswap/pools, @pancakeswap/position-managers, @pancakeswap/sdk, @pancakeswap/smart-router, @pancakeswap/swap-sdk-core, @pancakeswap/token-lists, @pancakeswap/tokens, @pancakeswap/tsconfig, @pancakeswap/ui-wallets, @pancakeswap/uikit, @pancakeswap/utils, @pancakeswap/v3-sdk, @pancakeswap/wagmi, @pancakeswap/widgets-internal, web
• Running dev in 22 packages
• Remote caching disabled
@pancakeswap/next-config:build: cache miss, executing 90f6bc1ec6aff9cd
@pancakeswap/next-config:build: 
@pancakeswap/next-config:build: > @pancakeswap/next-config@0.0.1 build /mnt/c/Users/Jclau/Desktop/pancake-frontend/packages/next-config
@pancakeswap/next-config:build: > npx tsc
@pancakeswap/next-config:build:
@pancakeswap/next-config:build: The file cannot be accessed by the system.
@pancakeswap/next-config:build:  ELIFECYCLE  Command failed with exit code 1.
@pancakeswap/next-config:build: ERROR: command finished with error: command (/mnt/c/Users/Jclau/Desktop/pancake-frontend/packages/next-config) pnpm run build exited (1)
command (/mnt/c/Users/Jclau/Desktop/pancake-frontend/packages/next-config) pnpm run build exited (1)

 Tasks:    0 successful, 1 total
Cached:    0 cached, 1 total
  Time:    5m0.364s
Failed:    @pancakeswap/next-config#build

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.

**Environment:**
Device and OS: ASUS, Windows 11 running WSL2
Browser:Chrome

**Steps to reproduce:**
run pnpm dev

**Expected result:**

build successfully 

**Anything else?** 

I also tried running it on Powershell cmd, and tried multiple node versions but still same issue.

**Comment by chefjackson** [comment]
From the error message looks like permission issue. Not related to the codebase

**Comment by Jeanclaudech98** [comment]
Hey chefjackson, Thanks for your answer. I tried running "ls -l" and "mount" and I checked all permissions and all seemed good, I know it doesn't make sense but that's what has been troubling me.
