### ISSUE TITLE
[BUG] BNB liquidity (v2) prioritized over CZUSD liquidity (v2), even with very high slippage

### ISSUE THREAD

**Issue by PlasticDigits** [pancakeswap/pancake-frontend#8443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Trade

### Current Behavior

This is a follow up from https://github.com/pancakeswap/pancake-frontend/issues/7909.

With this temporary fix, the LSDT and DGOD pairs are trading normally. However, for the GEM pair, the BNB liquidity is prioritized over the CZUSD liquidity in spite of very high (99%) slippage. This is dangerous since if a user were to buy GEM on the BNB liquidity, they will take a large loss which would be seized by bots.

GEM LP pair: 0x9321907037fa062b52b3f564b3350adf935bf698

### Expected Behavior

The Pancakeswap router should swap through CZUSD if the price after accounting for slippage is better than on the BNB-GEM pair.

### Steps To Reproduce

1. Check the slippage on CZUSD - GEM on Pancakeswap with 20 CZUSD trade. Should be less than 1%: https://pancakeswap.finance/swap?inputCurrency=0xE68b79e51bf826534Ff37AA9CeE71a3842ee9c70&outputCurrency=0x701F1ed50Aa5e784B8Fb89d1Ba05cCCd627839a7
2. Check the slippage on BNB - GEM with 0.1 BNB trade. Expected to show less than 1% slippage and routing through CZUSD; Actual behavior is it shows 99% slippage.
![Screenshot from 2023-11-24 11-45-27](https://github.com/pancakeswap/pancake-frontend/assets/83603340/775a0a9e-21e7-475f-9eea-e29e1692a8b1)
![Screenshot from 2023-11-24 11-46-45](https://github.com/pancakeswap/pancake-frontend/assets/83603340/dee14d7a-42df-41f2-9dee-68d2be49c2d9)

### Environment

```markdown
- Device: PC
- OS: Ubuntu
- Browser: Chrome
- Wallet: Metamask
```

**Comment by Kyle-GreenMiner** [comment]
Thank you to @PlasticDigits for bringing this to light! As the GreenMiner (GEM) owner this will be huge for us! Thank you @chef-jojo and @chefjackson for getting LSDT, and DOGEGOD working. Please work your magic for us at GEM too!

**Comment by Akronmayor** [comment]
I would also much appreciate it if this fix was applied to GEM as well! Thanks!

**Comment by dingolingus** [comment]
Please fix this issue. As an investor, i would like others to have easy access to this token.  This would benefit BNB and GEM.  Thank you.

**Comment by IHatePancakeSwap** [comment]
I am also seeing this issue. Are you able to expedite a fix here?

**Comment by goteam123469** [comment]
I'm also running into this issue. Are you able to fix?

**Comment by JsizzlTheCnote** [comment]
![Screenshot_20231129-184600_Trust Wallet](https://github.com/pancakeswap/pancake-frontend/assets/94065387/5b171e57-44f2-4cc8-b202-1bad8e7491df)
Many new investors GreenMiner onboarding to pcs network are having trouble and will go elsewhere

**Comment by Akronmayor** [comment]
I would greatly appreciate a fix as well! Please and thank you!

**Comment by chefjackson** [comment]
We've whitelisted the token for better multihop swap quoting. Please see https://github.com/pancakeswap/pancake-frontend/pull/8489

However, please be aware that this is a temporary solution and we're still working on better solution to resolve issues like this, and thank you for the report

**Comment by Kyle-GreenMiner** [comment]
@chefjackson thank you so much for this! We know you all are working on a longterm solution, but this temporary fix is huge for us! THANK YOU!

**Comment by JsizzlTheCnote** [comment]
![Screenshot_20231129-213112_Trust Wallet](https://github.com/pancakeswap/pancake-frontend/assets/94065387/b21438fb-6c48-484d-8bdd-993a9803886a)
Rad. ChefJoJo & chefjackson Thank you for your work, your diligence for the future, & allowing our protocol to be accessed. This will solidify our commitment to having a home on pcs as we continue to grow to other chains.
