### ISSUE TITLE
Need Installation Guide Pancakeswap 

### ISSUE THREAD

**Issue by devsingh123** [pancakeswap/pancake-frontend#851]
Hi,

I need the installation guide which help me setup the pancakeswap so, that I can test.

Next during setup what type of keys are required.

Please help & guide.  You help in this regards will be highly appriciated.

**Comment by memoyil** [comment]
https://github.com/pancakeswap/pancake-frontend/blob/develop/CONTRIBUTING.md

**Comment by devsingh123** [comment]
Thanks for your quick response. 

I read this but, I don't know where to find the developer email id for these two values so, that I can email and get these value ? Please help.

REACT_APP_CROWDIN_APIKEY = ""
REACT_APP_CROWDIN_PROJECTID = ""

**Comment by memoyil** [comment]
You don't need them unless you need translations

**Comment by devsingh123** [comment]
I actually, need only two features exchange and farms will those work without these two keys ?

**Comment by memoyil** [comment]
Yes they will work without those keys

For exchange you need to fork this repo

https://github.com/pancakeswap/pancake-swap-interface

**Comment by devsingh123** [comment]
thanks you @Memoyil for you quick response. It was confusing for me earlier but, you made it clear.

**Comment by Chef-Chungus** [comment]
resolved
