### ISSUE TITLE
uikit source code is not working with storybook

### ISSUE THREAD

**Issue by wXyz0326** [pancakeswap/pancake-frontend#8625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

I am trying now to run uikit source code with storybook.

### Expected Behavior

![Screenshot_2](https://github.com/pancakeswap/pancake-frontend/assets/81634285/b75ffd0d-ee88-4223-8555-f3940cf7bd9b)

I am run pnpm storybook. but i got that screen. How can i fix that.

### Steps To Reproduce

1. pnpm install
2. pnpm storybook

### Environment

```markdown
- Device:
Dell
- OS:
Windows 10
- Browser:
Chrome
- Wallet:
Meatamsk
```

**Comment by chef-jojo** [comment]
fixed by removing the outdated storybook plugins https://github.com/pancakeswap/pancake-frontend/pull/8661/files#diff-5baead4c16ae31e6d7af79a39495fef8a95d0060433d446885dec7eb043410b9
