### ISSUE TITLE
pnpm build 

### ISSUE THREAD

**Issue by yu2230440650** [pancakeswap/pancake-frontend#8645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

pnpm dev is normal. But when executing pnpm build, no new folders are generated when building. Shouldn't static files like build or dist be generated?

### Expected Behavior

Generate static file package

### Steps To Reproduce

Run "pnpm build"

### Environment

```markdown
- Device:
- OS:
- Browser:
- Wallet:
```

**Comment by chefjackson** [comment]
Static files are under `.next` folders. For more detailed information please refer to nextjs documentation website
