### ISSUE TITLE
[BUG] Please bump 0xsquid/widget version to latest

### ISSUE THREAD

**Issue by kaliubuntu0206** [pancakeswap/pancake-frontend#8815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

Bumping 0xsquid/widget would solve ledger patch issue so that we could remove manual patch

### Expected Behavior

Bumping 0xsquid/widget to 1.6.31

### Steps To Reproduce

Bumping 0xsquid/widget to 1.6.31

### Environment

```markdown
- Device: Latest
- OS:
- Browser:
- Wallet:
```

**Comment by chef-jojo** [comment]
Keep the issue
