### ISSUE TITLE
[BUG] Farms page 

### ISSUE THREAD

**Issue by heyimbrucelee** [pancakeswap/pancake-frontend#900]
i guess you are aware of it, farms page doesn't works
also $cake price in sidebar not displaying

js errors : 

3.abd0cd99.chunk.js:1 Uncaught (in promise) Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.
    at l.decodeParametersWith (3.abd0cd99.chunk.js:1)
    at l.decodeParameters (3.abd0cd99.chunk.js:1)
    at R.h._decodeMethodReturn (3.abd0cd99.chunk.js:1)
    at h.outputFormatter (3.abd0cd99.chunk.js:1)
    at h.formatOutput (3.abd0cd99.chunk.js:1)
    at s (3.abd0cd99.chunk.js:1)
    at 3.abd0cd99.chunk.js:1
    at XMLHttpRequest.i.onreadystatechange (3.abd0cd99.chunk.js:1)

js translations error : 

Access to XMLHttpRequest at 'https://api.crowdin.com/api/v2/projects/422458/languages/en/translations?fileId=8&limit=400' from origin 'https://pancakeswap.finance' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by memoyil** [comment]
Js translation error is because english one has too many request. If you check the options request before that you will see 429 Too Many Request response. But it fallbacks to english ones that is defined in code
