### ISSUE TITLE
[BUG] Installing the latest @pancakeswap/smart-router 4.14.3 fails

### ISSUE THREAD

**Issue by pekichu** [pancakeswap/pancake-frontend#9014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

Currently, when trying to install the latest version of `@pancakeswap/smart-router@4.14.3` fails.

### Expected Behavior

There should be no issue installing the package.

### Steps To Reproduce

Steps to reproduce:

1. `mkdir pancake-router-test`
2. `npm init -y`
3. `npm install @pancakeswap/smart-router`

```
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@pancakeswap%2fgauges - Not found
npm ERR! 404 
npm ERR! 404  '@pancakeswap/gauges@0.0.8' is not in this registry.
```

### Environment

```markdown
- Device: PC
- OS: Any
- Browser: N/A
- Wallet: N/A
```

**Comment by chefjackson** [comment]
Hi, thanks for the report and sorry for the trouble. Could you try upgrade to use `@pancakeswap/smart-router@4.14.4`? Let us know if this issue still exists

**Comment by pekichu** [comment]
Hey, just updated to the latest version and works good now. Thanks for the fix!
