### ISSUE TITLE
[BUG] Pancakeswap Smart Router - Compatibility Error with Newer versions of "viem" library

### ISSUE THREAD

**Issue by oviniciusfeitosa** [pancakeswap/pancake-frontend#9107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

When utilizing Pancakeswap Smart Router alongside newer versions of the "viem" library, type incompatibility errors occur. For instance, `SmartRouter.createQuoteProvider({ onChainProvider: () => publicClient })` triggers an error specifically with version `2.7.11` of the "viem" library. However, using version `^1.19.11` mitigates this error.

### Expected Behavior

The integration of Pancakeswap Smart Router with the `viem` library should not result in type incompatibility errors regardless of the version used. Users should be able to seamlessly utilize the Smart Router functionality without encountering such issues.

### Steps To Reproduce

1. Follow the steps outlined in [Pancakeswap Smart Router documentation](https://github.com/pancakeswap/pancake-frontend/tree/develop/packages/smart-router).
2. Execute the command `pnpm add viem ....` as specified in `Readme.md`.
3. Observe the type incompatibility error when utilizing `SmartRouter.createQuoteProvider({ onChainProvider: () => publicClient })` with version `2.7.11` of the "viem" library.

### Environment

```markdown
- **OS**: Ubuntu 23.04
- **PNPM Version**: 8.15.2
- **Node version**: v20.11.0
- **package.json dependencies**:
  - "@pancakeswap/sdk": "^5.7.7"
  - "@pancakeswap/tokens": "^0.6.6"
  - "@pancakeswap/smart-router": "^4.14.9"
  - "viem": "^1.19.11" (compatible)
  - "viem": "^2.7.11" (incompatible)
```

### Additional Context
The issue arises in the integration of Pancakeswap Smart Router with the "viem" library, particularly with version `2.7.11`. It's noteworthy that following the provided steps and downloading the latest version of the library through `pnpm add viem ...` still leads to the occurrence of the error.

Suggested resolution:
- **Option 1**: Set the recommended version of "viem" to `^1.19.11` to ensure compatibility with Pancakeswap Smart Router.
- **Option 2**: Implement necessary updates to the Smart Router or "viem" library codebase to mitigate type incompatibility issues across versions.

### Anything else?
If you find this issue helpful or want to buy me a cup of coffee, feel free to send any amount of crypto to my wallet address: `0xB0fc1C69447984B5B712EE63f4DE8F16D6aa65F4`. Remember, every Satoshi counts! :smile::sparkles::rocket:

**Comment by oviniciusfeitosa** [comment]
I noticed that the same thing happens for `graphql-request`. In version `5.0.0` it works, but in the current version (6.1.0) it doesn't work.

**Comment by chefjackson** [comment]
Hi, thanks for raising this. Yes as you mentioned currently the sdk is built on top of viem `1.x` version. We're planning to migrate to v2 but probably won't be ready in short term. Sorry for the trouble

**Comment by chefjackson** [comment]
We've specified the dependency versions in the doc. For detailed information please refer to https://github.com/pancakeswap/pancake-frontend/tree/develop/packages/smart-router
