### ISSUE TITLE
Rules details text and icon are not aligned 

### ISSUE THREAD

**Issue by tzoeov** [pancakeswap/pancake-frontend#928]
**Bug Description**
Text and icon should be centered.

**Steps to Reproduce**
1. Go to Team Battle
2. Scroll down to the rules

**Additional Context**
![image](https://user-images.githubusercontent.com/4741200/115141953-c8fbcf00-a047-11eb-824b-f75252e6882c.png)

**Comment by Chef-Chungus** [comment]
Thanks!
