### ISSUE TITLE
[Routers] <bnb - usdt - Czusd - GEM - DGOD - CZR >

### ISSUE THREAD

**Issue by JsizzlTheCnote** [pancakeswap/pancake-frontend#9427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Trade

### Current Behavior

$CZUsd liquidity pool is paired with binance smart chain $Usdt and has given grief to traders for $GEM, $DGOD, & $CZR.
Czusd address - 0xE68b79e51bf826534Ff37AA9CeE71a3842ee9c70
Please update pcs routers so traders can use pcs for $CZUsd products. 
![Screenshot_20240326_154822_Trust Wallet](https://github.com/pancakeswap/pancake-frontend/assets/94065387/0c35a614-8440-491e-b6f0-ae46d94e7186)

### Expected Behavior

Present router behavior results in Extreme price impact resorting in loss of funds for traders. 

### Steps To Reproduce

1. Open pcs
2. Input any Czusd pair
3. Select any bnb asset
4. Experience high impact currency deterioration 

### Environment

```markdown
- Device:all devices 
- OS:all
- Browser:all browsers
- Wallet:trust
```

### Anything else?

Appreciate Chef-JoJo and staff for your resolution when Czusd was paired to bnb and look forward to your resolution with our current router issues on v3. Bless

**Comment by Kyle-GreenMiner** [comment]
@chef-jojo we come again after a necessary update in the CZUSD ecosystem has put us back in this situation. We greatly appreciate you all fixing this for us a few months ago. It really helped out our project. When you try to purchase $GEM (contract: 0x701F1ed50Aa5e784B8Fb89d1Ba05cCCd627839a7 ) it results is massive price difference. Currently 1 BNB should purchase around 390 GEM. We’ve had people unknowingly buy with this price impact and receive 2-3 GEM per BNB. If you could help us out, we would greatly appreciate it!

**Comment by PlasticDigits** [comment]
The primary czusd liquidity is czusd/usdt v3 1% @ 0xb0669fdfd105bc29878da388c30914fe4496f383

To fix this issue temporarily on the cz.cash pcs frontend fork, I disabled BUSD liquidity routing. Obviously this is a temporary solution. Im not sure what is causing this issue of routes going through BUSD instead of USDT when the slippage is very high on BUSD pairs.

**Comment by Kyle-GreenMiner** [comment]
> The primary czusd liquidity is czusd/usdt v3 1% @ 0xb0669fdfd105bc29878da388c30914fe4496f383
> 
> To fix this issue temporarily on the cz.cash pcs frontend fork, I disabled BUSD liquidity routing. Obviously this is a temporary solution. Im not sure what is causing this issue of routes going through BUSD instead of USDT when the slippage is very high on BUSD pairs.

Thank you @PlasticDigits that is better than the explanation I could give @chef-jojo !

**Comment by chefjackson** [comment]
Hi, we're introducing a new routing algo lately. Could you try enable the "Fast routing" in the swap settings?

**Comment by Kyle-GreenMiner** [comment]
> Hi, we're introducing a new routing algo lately. Could you try enable the "Fast routing" in the swap settings?

Thanks for the reply! I switched to fast routing, and basically the same. Here is a screenshot. 

![IMG_3562](https://github.com/pancakeswap/pancake-frontend/assets/152041535/3942ef6d-d5dd-4beb-be70-044daa3b0f32)

**Comment by chef-jojo** [comment]
Need 4 hops?

**Comment by JsizzlTheCnote** [comment]
Just tested and route is better. One wallet I did not need to select fast route, on another I did. Either way Thank you chefjackson and JoJo if you on this. We will inform our community until it processes without the fast selection. 
![Screenshot_20240401_113424_Trust Wallet](https://github.com/pancakeswap/pancake-frontend/assets/94065387/df6d9007-1eba-4379-ae52-b43d2c629543)
Bless

**Comment by chefjackson** [comment]
Hi @PlasticDigits @Kyle-GreenMiner @JsizzlTheCnote 

I just tried with fast routing on, and the route looks good. Please let me know if you're having trouble picking the optimal route with fast routing on.

**Comment by Kyle-GreenMiner** [comment]
> Hi @PlasticDigits @Kyle-GreenMiner @JsizzlTheCnote
> 
> I just tried with fast routing on, and the route looks good. Please let me know if you're having trouble picking the optimal route with fast routing on.

Thank you, just checked all routing options and they all look good. Thank you all again for your help!

**Comment by JsizzlTheCnote** [comment]
> Hi @PlasticDigits @Kyle-GreenMiner @JsizzlTheCnote
> 
> I just tried with fast routing on, and the route looks good. Please let me know if you're having trouble picking the optimal route with fast routing on.

Can we get four hops on $CZR chefj? BNB -> USDT -> CZUSD -> CZR.

0x5cd0c2C744caF04cda258Efc6558A3Ed3defE97b

Selected fast option with no resolve. Is there another option that could help with this?
