### ISSUE TITLE
Exchange CORS error with api.crowdin.com translations

### ISSUE THREAD

**Issue by ciruz** [pancakeswap/pancake-frontend#951]
**Bug Description**
Noticed a CORS error with api.crowdin.com translations.

**Steps to Reproduce**

1. Go to https://exchange.pancakeswap.finance/#/
2. Check the console
```console
Access to XMLHttpRequest at 'https://api.crowdin.com/api/v2/projects/422458/languages/en/translations?fileId=6&limit=200' from origin 'https://exchange.pancakeswap.finance' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

```
![image](https://user-images.githubusercontent.com/987947/115413120-36009780-a1f5-11eb-9413-5067892de49e.png)

**Comment by memoyil** [comment]
Currently there too many request, Options request before that one returns 429 Too Many Requests. That is the root cause of that issue

**Comment by memoyil** [comment]
@hachiojidev We can close this issue since we changed our implementation
