### ISSUE TITLE
Can't find LP tokens in liquidity pool V1 to remove them

### ISSUE THREAD

**Issue by idkw** [pancakeswap/pancake-frontend#997]
solved

**Comment by idkw** [comment]
I can confirm this is definitely a bug affecting Brave.
I wan able to remove the tokens from the v1 pool using Firefox with the same metamask wallet.

**Comment by menino898** [comment]
I've been through that. I know how to solve and help you recover 100% of your BNB.

My telegram:

@mito99

**Comment by ChefNina** [comment]
I close it as the reporter found the solution by themself.
